import type { FaqLocaleOverlay } from "./types";

/** Supplemental FAQ copy for es — merged after marketing-home-below-fold partial FAQ. */
export const faqEs: FaqLocaleOverlay = {
  general04Q: "¿Qué es el «calendario de aceptación»?",
  general04A: "Tras una ausencia deberías volver a una lista corta que merezca acción — entrevistas y perfiles que aceptas o rechazas de un movimiento — no miles de CV en bruto ni spam aleatorio. Matching, consentimiento, trabajo asíncrono, aceptación por lotes y exportación/sincronización de calendario sirven a ese resultado.",
  general05Q: "¿Y la privacidad y el RGPD?",
  general05A: "Das consentimiento explícito al registrarte. Los datos del perfil alimentan el ranking y las funciones. Retención, exportación y derechos están en la Política de privacidad. Minimizamos contacto sorpresa del empleador; la verificación de placement es self-serve en producto por defecto.",
  candidates01Q: "¿Cómo funciona el matching de ofertas?",
  candidates01A: "Hoy: las ofertas de portales activos se guardan, deduplican y clasifican según señales de perfil (habilidades, preferencias, historial). Las explicaciones mejoran por fases públicas — el objetivo es menos falsos positivos, no máximo volumen.",
  candidates02Q: "¿Qué portales de empleo están soportados?",
  candidates02A: "Fase 1: portales polacos como pracuj.pl y rocketjobs.pl, más LinkedIn si está configurado. Tú eliges fuentes; en beta los scrapers pueden estar en allowlist de ops. Más portales cuando compliance y fiabilidad lo permitan.",
  candidates03Q: "¿Qué es auto-apply — y está activo?",
  candidates03A: "La auto-aplicación nocturna solo tras consentimiento explícito y donde el flujo del portal se automatiza con seguridad. Está en el repo con Celery — trátala como beta: no toda oferta es elegible. Puedes revisar envíos y estado en tu pipeline.",
  candidates04Q: "¿Puede TWIN adaptar mi CV a un rol?",
  candidates04A: "Sí — Career Assistant incluye optimización de CV orientada a ATS para un trabajo concreto cuando tienes CV en perfil. Borradores para revisar; no reemplazamos tu CV maestro sin tu decisión.",
  candidates05Q: "¿Qué incluye Career Assistant?",
  candidates05A: "Hoy: intel de empresa, borradores de carta, insights de hiring manager, prep de entrevista, briefs de negociación, emails de seguimiento y sugerencias LinkedIn — con datos de perfil y uso explícito. Las funciones evolucionan; mira etiquetas in-app.",
  candidates06Q: "¿Cómo funcionan calendario y reservas de entrevista?",
  candidates06A: "Disponible: OAuth Google Calendar (ocupado + holds donde configurado), enlaces WebCal y exportación ICS. Microsoft 365 vía Graph con OAuth cuando hay credenciales API. Usuarios Apple suelen usar WebCal/ICS — no hay un único «Iniciar sesión con Apple Calendar».",
  candidates07Q: "¿Qué es la cola de aceptación del candidato?",
  candidates07A: "Lista corta en el panel de holds y coincidencias fuertes para mantener, reprogramar o rechazar — calendario intencional. Complementa slots propuestos por reclutadores; no es una segunda bandeja de spam.",
  candidates08Q: "¿Cómo funciona la verificación de placement para candidatos?",
  candidates08A: "Autodeclaración in-app, magic link de email laboral opcional y enlaces de atestación del empleador en un clic — sin bucles de email «¿ya firmaste?». Máquina de estados y billing completos son por fases; ver docs/PLACEMENT_VERIFICATION.md.",
  candidates09Q: "¿Cómo es el precio para candidatos?",
  candidates09A: "Checkout de candidato con Stripe para planes de pago; campañas de lista fundadora pueden dar acceso gratuito a cohortes tempranas. Revisa billing tras login — sin tarifas ocultas en FAQ.",
  candidates10Q: "¿TWIN sustituye a los reclutadores?",
  candidates10A: "No. Menos ruido: candidatos con movimientos más acertados; reclutadores con aceptación por lotes y señales ATS en lugar de inundación de CV. Las personas deciden contrataciones; el software ordena ranking, papeleo e higiene de calendario.",
  candidates11Q: "¿Qué hacer antes de confiar en la automatización por fases?",
  candidates11A: "Completa perfil, sube CV, conecta calendario si quieres holds, activa solo portales de confianza y lee el consentimiento de auto-apply. Empieza con guardados y aplicaciones manuales. Auto-apply está en pausa en producción hoy — primero paquetes prepare-only.",
  recruiters01Q: "¿Qué es la bandeja de aceptación del reclutador?",
  recruiters01A: "Superficie piloto para slug de empresa: cola corta de solicitudes para aceptar entrevista o rechazar sin usar el email como sistema. Necesitas token de reclutador del enlace piloto TWIN — no bandeja pública abierta.",
  recruiters02Q: "¿En qué difiere la aceptación por lotes de una bandeja ATS normal?",
  recruiters02A: "Aceptación por lotes sobre filas pre-cualificadas: acepta o pasa en una pantalla hacia pasos listos para calendario. No maximizamos volumen bruto — calidad y barra de match primero.",
  recruiters03Q: "¿Puedo publicar ofertas en TWIN?",
  recruiters03A: "Sí — publicación de empleos del empleador en workspaces de reclutador ligados a un slug. Las ofertas alimentan matching y aplicaciones como trabajos scrapeados donde esté configurado.",
  recruiters04Q: "¿Qué integraciones ATS existen hoy?",
  recruiters04A: "Webhooks de contratación para Greenhouse, Lever y Ashby marcan placements verificados con external_ats_id vinculado. Botones OAuth Greenhouse/Lever si las env API están configuradas; si no, webhooks manuales. Integración técnica — no reemplazo ATS completo.",
  recruiters05Q: "¿Cómo vincular solicitudes a Greenhouse?",
  recruiters05A: "Guarda external_ats_id y external_ats_provider (greenhouse, lever, ashby) en la fila de aplicación TWIN para reconciliar eventos hire. Ver ATS_WEBHOOKS.md y la página de webhooks ATS in-app.",
  recruiters06Q: "¿Qué etapas de pipeline rastrea TWIN?",
  recruiters06A: "Candidatos ven estado en un pipeline; reclutadores colas orientadas a aceptación y flujos de atestación. Sincronización profunda de etapas ATS es roadmap — hoy foco en hand-offs listos para aceptación.",
  recruiters07Q: "¿Cómo se facturan los asientos de reclutador?",
  recruiters07A: "Asientos B2B por factura (no checkout Stripe de candidato). El contrato define asientos, slug de empresa e inclusión de webhooks ATS o enlaces de atestación.",
  recruiters08Q: "¿Puede el empleador confirmar contratación sin cuenta TWIN?",
  recruiters08A: "Sí — el candidato puede compartir URL de atestación del empleador en un clic (nonce, expira) para que el hiring manager confirme sin login. Verificación asistida por máquina en lugar de ping-pong por email.",
  recruiters09Q: "¿Qué no está live aún para reclutadores?",
  recruiters09A: "SSO enterprise completo, sincronización bidireccional profunda de etapas ATS y gobernanza multi-tenant pulida siguen en hardening. Pilotos deben esperar bandeja por token y hooks ATS webhook-first.",
  companies01Q: "¿Qué compran las empresas a TWIN?",
  companies01A: "Programas B2B anuales: cobertura de sourcing, asientos de reclutador, verificación webhook ATS opcional y economía de placement alineada a contrataciones verificadas — no spam pay-per-CV. SKU de procurement separados de suscripciones de candidato.",
  companies02Q: "¿Cómo suele empezar procurement?",
  companies02A: "Ruta estándar: cuestionario de seguridad, DPA, order form anual y slug(s) de empresa definidos. Flujos de datos (scraping, AI, calendario) en packs legales; finanzas confidenciales fuera del sitio público.",
  companies03Q: "¿Cómo verifican placement para honorarios?",
  companies03A: "Por defecto: declaración self-serve del candidato, prueba de email laboral opcional, atestación del empleador o webhooks hire ATS — eventos append-only, sin equipo persiguiendo «¿firmado?». Disputas a cola de excepciones, no ping-pong manual.",
  companies04Q: "¿Puede nuestro ATS ser fuente de verdad?",
  companies04A: "Para confirmación de contratación sí — webhooks Greenhouse, Lever o Ashby son el perfil preferido si está contratado. TWIN sigue mostrando discovery y match a candidatos; el ATS puede liderar el ciclo de requisition.",
  companies05Q: "¿Qué datos salen de nuestro perímetro?",
  companies05A: "Perfiles de candidatos, eventos de aplicación y metadatos de calendario opcionales que autorices. Clics de atestación del empleador registran confirmación sin cuentas TWIN completas. Subprocesadores y regiones en Política de privacidad y DPA B2B.",
  companies06Q: "¿Contactan a empleados o candidatos por sorpresa?",
  companies06A: "Sin campañas outbound sorpresa al empleador. Email transaccional solo en flujos con consentimiento (magic links, atestación iniciada por candidato). Marketing a tu plantilla no es default B2B.",
  companies07Q: "¿Qué hay en la roadmap enterprise?",
  companies07A: "Calendario Microsoft a escala, SSO más rico, HRIS más allá de webhooks ATS y elegibilidad de factura automática ligada a la máquina de estados de placement. Enviamos cuando la auditabilidad es clara — no cuando un slide dice «sistema completo».",
  investors01Q: "¿Dónde está la sala de datos para inversores?",
  investors01A: "Workspace de inversor tras login: pack de tracción público (dashboard de métricas, JSON MVP, OpenAPI, status, exportación de calculadora) más placeholders para cap table y finanzas auditadas. Solicita acceso para descargas confidenciales.",
  investors02Q: "¿Hay NDA antes de materiales confidenciales?",
  investors02A: "Un stub NDA en sesión de navegador desbloquea placeholders de vista previa hoy; cap table, finanzas y legal completos requieren acceso firmado vía contacto. Registro de documentos activo; subida S3 presigned depende de env API.",
  investors03Q: "¿Qué métricas sin reunión?",
  investors03A: "Métricas MVP en vivo y dashboards de inversor (empleos validados, señales de salud del sistema, uso de producto donde esté instrumentado). Números beta, no finanzas auditadas — esas detrás de acceso confidencial.",
  investors04Q: "¿Cómo pensáis la economía de verificación de placement?",
  investors04A: "Evitamos el «ping-pong CS» de marketplaces — verificación in-product asistida por máquina con atestación del empleador y webhooks ATS opcionales. Escala mejor el margen bruto que bucles manuales de email, con excepciones solo donde haga falta.",
  investors05Q: "¿Qué es defendible frente a portales de empleo?",
  investors05A: "Normalización cross-board, automatización con consentimiento, UX orientada a aceptación en ambos lados y resultados sincronizados al calendario. Los portales optimizan anuncios; TWIN optimiza el camino de discovery a placement verificado con menos ruido.",
  investors06Q: "¿Fase actual y tracción honesta?",
  investors06A: "MVP fase 1: FastAPI + Celery + Postgres, scrapers de portales PL, matching, aplicaciones, auto-apply y calendario tempranos, superficies multi-persona. Tracción en forma de piloto — valida en /status, métricas y design partners, no volumen vanidad.",
  investors07Q: "¿Cómo solicitar una llamada de diligence más profunda?",
  investors07A: "Usa flujos de solicitud de acceso confidencial en la data room o contactos del workspace de inversor. Trae checklist — preferimos preguntas concretas de seguridad y unit economics a tours genéricos de deck.",
  investors08Q: "Soy angel — ¿qué dilución y cap table esperar?",
  investors08A: "Pre-ronda institucional: sin cap table público en el sitio de marketing. Materiales confidenciales y términos de ronda tras NDA y fit mutuo. Tracción y profundidad de producto inspeccionables sin reunión vía métricas live y demo.",
  investors09Q: "Somos VC — ¿cuál es la cuña Polonia + UE?",
  investors09A: "Fase 1 en portales polacos (pracuj.pl, rocketjobs.pl) con roles remote UE en el feed, consentimiento GDPR-first y UX de calendario de aceptación en EN y PL. Expansión adapter-driven (registro de portales + compliance), no clon mono-país.",
  investors10Q: "Somos PE — ¿hay ingresos y finanzas auditadas?",
  investors10A: "Respuesta honesta: tracción MVP temprana, no ingresos escala PE ni estados auditados en sitio público. Programas enterprise y economía de verificación de placement son la historia de margen que construimos; finanzas en diligence confidencial cuando corresponda.",
  investors11Q: "¿Puedo ver unit economics antes de reunión con partner?",
  investors11A: "Sí — la calculadora de escenario inversor es ilustrativa (sensibilidad success fee, costes de equipo, infra). Modelo de diligence, no forecast ni oferta. Agregados de uso live en /investor/metrics con etiqueta beta.",
  investors12Q: "¿Qué deberían abrir primero los partners de YC?",
  investors12A: "Empieza en /for-investors/yc: demo interactiva, JSON de métricas MVP, dashboard de métricas y sign-in de workspace para exportaciones. Preferimos preguntas concretas de producto a walk genérico de deck.",
};
