import type { FaqLocaleOverlay } from "./types";

/** Supplemental FAQ copy for fr — merged after marketing-home-below-fold partial FAQ. */
export const faqFr: FaqLocaleOverlay = {
  general04Q: "Qu'est-ce que le « calendrier d'acceptation » ?",
  general04A: "Après une absence, vous devriez revenir à une courte liste qui vaut la peine — entretiens et profils à accepter ou refuser en un geste — pas des milliers de CV bruts ni du spam aléatoire. Matching, consentement, travail asynchrone, acceptation par lot et export/sync calendrier servent ce résultat.",
  general05Q: "Et la confidentialité / RGPD ?",
  general05A: "Vous donnez un consentement explicite à l'inscription. Les données de profil alimentent le classement et les fonctions. Conservation, export et droits sont dans la Politique de confidentialité. Nous minimisons le contact employeur surprise ; la vérification placement est self-serve en produit par défaut.",
  candidates01Q: "Comment fonctionne le matching d'offres ?",
  candidates01A: "Aujourd'hui : les offres des sites activés sont stockées, dédupliquées et classées selon les signaux de profil (compétences, préférences, historique). Les explications s'améliorent par phases publiques — l'objectif est moins de faux positifs, pas le volume maximum.",
  candidates02Q: "Quels job boards sont pris en charge ?",
  candidates02A: "Phase 1 : sites polonais comme pracuj.pl et rocketjobs.pl, plus LinkedIn si configuré. Vous choisissez les sources ; en bêta les scrapers peuvent être sur allowlist ops. D'autres sites quand compliance et fiabilité le permettent.",
  candidates03Q: "Qu'est-ce que l'auto-candidature — et est-ce live ?",
  candidates03A: "L'auto-candidature nocturne seulement après consentement explicite et où le flux du site est automatisable en sécurité. Dans le repo avec Celery — traiter en bêta : toutes les offres ne sont pas éligibles. Vous pouvez revoir les envois et le statut dans votre pipeline.",
  candidates04Q: "TWIN peut-il adapter mon CV à un poste ?",
  candidates04A: "Oui — Career Assistant inclut l'optimisation CV orientée ATS pour un job précis quand vous avez un CV au profil. Brouillons à relire ; nous ne remplaçons pas le CV maître sans votre choix.",
  candidates05Q: "Que comprend Career Assistant ?",
  candidates05A: "Live : intel entreprise, brouillons de lettre, insights hiring manager, prep entretien, briefs négociation, e-mails de suivi et suggestions LinkedIn — avec données profil et usage explicite. Les fonctions évoluent ; voir les labels in-app.",
  candidates06Q: "Comment fonctionnent calendrier et créneaux d'entretien ?",
  candidates06A: "Livré : OAuth Google Calendar (occupé + holds si configuré), liens WebCal et exports ICS. Microsoft 365 via Graph avec OAuth quand les credentials API sont définis. Utilisateurs Apple utilisent souvent WebCal/ICS — pas de « Se connecter avec Apple Calendar » unique.",
  candidates07Q: "Qu'est-ce que la file d'acceptation candidat ?",
  candidates07A: "Courte liste dashboard de holds et matchs forts à garder, reprogrammer ou refuser — calendrier intentionnel. Complète les créneaux proposés par le recruteur ; pas une deuxième boîte spam.",
  candidates08Q: "Comment fonctionne la vérification placement pour les candidats ?",
  candidates08A: "Auto-déclaration in-app, magic link e-mail pro optionnel et liens d'attestation employeur en un clic — pas de boucles e-mail « déjà signé ? ». Machine à états et billing complets sont phasés ; voir docs/PLACEMENT_VERIFICATION.md.",
  candidates09Q: "À quoi ressemble la tarification candidat ?",
  candidates09A: "Checkout candidat via Stripe pour plans payants ; campagnes liste fondateurs peuvent donner accès gratuit aux cohortes early. Vérifiez billing après connexion — pas de frais cachés en FAQ.",
  candidates10Q: "TWIN remplace-t-il les recruteurs ?",
  candidates10A: "Non. Moins de bruit : candidats avec des mouvements plus pertinents ; recruteurs avec acceptation par lot et signaux ATS au lieu de flux de CV. Les humains décident des embauches ; le logiciel gère classement, paperasse et hygiène calendrier.",
  candidates11Q: "Que faire avant de compter sur l'automatisation par phases ?",
  candidates11A: "Complétez le profil, uploadez un CV, connectez le calendrier pour les holds, activez seulement les sites de confiance et lisez le consentement auto-candidature. Commencez par sauvegardes et candidatures manuelles. Auto-candidature en pause en production aujourd'hui — d'abord paquets prepare-only.",
  recruiters01Q: "Qu'est-ce que la boîte d'acceptation recruteur ?",
  recruiters01A: "Surface pilote pour un slug entreprise : courte file de candidatures à accepter en entretien ou refuser sans e-mail comme système. Token recruteur du lien pilote TWIN requis — pas boîte publique ouverte.",
  recruiters02Q: "En quoi l'acceptation par lot diffère d'une boîte ATS classique ?",
  recruiters02A: "Acceptation par lot sur lignes pré-qualifiées : accepter ou passer sur un écran vers étapes prêtes pour le calendrier. Pas de maximisation du volume brut — qualité et barre de match d'abord.",
  recruiters03Q: "Puis-je publier des offres dans TWIN ?",
  recruiters03A: "Oui — publication d'offres employeur pour workspaces recruteur liés à un slug. Les annonces alimentent matching et candidatures comme les jobs scrapés si configuré.",
  recruiters04Q: "Quelles intégrations ATS existent aujourd'hui ?",
  recruiters04A: "Webhooks hire pour Greenhouse, Lever et Ashby marquent placements vérifiés quand external_ats_id est lié. Boutons OAuth Greenhouse/Lever si env API définies ; sinon webhooks manuels. Plomberie d'intégration — pas remplacement ATS complet.",
  recruiters05Q: "Comment lier les candidatures à Greenhouse ?",
  recruiters05A: "Stockez external_ats_id et external_ats_provider (greenhouse, lever, ashby) sur la ligne candidature TWIN pour réconcilier les events hire. Voir ATS_WEBHOOKS.md et page webhooks ATS in-app.",
  recruiters06Q: "Quels stades de pipeline TWIN suit-il ?",
  recruiters06A: "Candidats voient le statut dans un pipeline ; recruteurs files orientées acceptation et flux d'attestation. Sync profonde des stades ATS est roadmap — aujourd'hui focus sur hand-offs prêts à accepter.",
  recruiters07Q: "Comment la facturation recruteur fonctionne-t-elle ?",
  recruiters07A: "Sièges recruteur B2B sur facture (pas checkout Stripe candidat). Le contrat définit sièges, accès slug entreprise et inclusion webhooks ATS ou liens d'attestation.",
  recruiters08Q: "L'employeur peut-il confirmer l'embauche sans compte TWIN ?",
  recruiters08A: "Oui — le candidat peut partager une URL d'attestation employeur en un clic (nonce, expire) pour que le hiring manager confirme sans login. Vérification assistée machine plutôt que ping-pong e-mail CS.",
  recruiters09Q: "Quoi n'est pas encore live pour les recruteurs ?",
  recruiters09A: "SSO enterprise complet, sync bidirectionnelle profonde des stades ATS et gouvernance multi-tenant polie sont encore en durcissement. Les pilotes doivent s'attendre à boîte sur token et hooks ATS webhook-first.",
  companies01Q: "Que achètent les entreprises chez TWIN ?",
  companies01A: "Programmes B2B annuels : couverture sourcing, sièges recruteur, vérification webhook ATS optionnelle et économie placement alignée sur embauches vérifiées — pas spam pay-per-CV. SKU procurement séparés des abonnements candidat.",
  companies02Q: "Comment le procurement démarre-t-il habituellement ?",
  companies02A: "Parcours standard : questionnaire sécurité, DPA, order form annuel et slug(s) entreprise définis. Flux de données (scraping, AI, calendrier) dans packs légaux ; finances confidentielles hors site public.",
  companies03Q: "Comment le placement est-il vérifié pour les frais ?",
  companies03A: "Par défaut : déclaration candidat self-serve, preuve e-mail pro optionnelle, attestation employeur ou webhooks hire ATS — events append-only, pas d'équipe qui chasse « signé ? ». Litiges en file d'exceptions, pas ping-pong manuel.",
  companies04Q: "Notre ATS peut-il être source de vérité ?",
  companies04A: "Pour confirmation d'embauche oui — webhooks Greenhouse, Lever ou Ashby sont le profil préféré si contracté. TWIN montre toujours discovery et match aux candidats ; l'ATS peut mener le cycle requisition.",
  companies05Q: "Quelles données quittent notre périmètre ?",
  companies05A: "Profils candidats, events candidature et métadonnées calendrier optionnelles que vous autorisez. Clics attestation employeur loggent confirmation sans comptes TWIN complets. Sous-traitants et régions dans Politique de confidentialité et DPA B2B.",
  companies06Q: "Contactez-vous nos employés ou candidats par surprise ?",
  companies06A: "Pas de campagnes outbound employeur surprises. E-mail transactionnel seulement dans flux consentis (magic links, attestation initiée par candidat). Marketing vers vos effectifs n'est pas le défaut B2B.",
  companies07Q: "Quoi sur la roadmap enterprise ?",
  companies07A: "Calendrier Microsoft à l'échelle, SSO plus riche, HRIS au-delà des webhooks ATS et éligibilité facture automatique liée à la machine à états placement. Nous livrons quand l'auditabilité est claire — pas quand une slide dit « système complet ».",
  investors01Q: "Où est la data room investisseur ?",
  investors01A: "Workspace investisseur connecté : pack traction public (dashboard métriques, JSON MVP, OpenAPI, page status, export calculateur) plus placeholders pour cap table et finances auditées. Demandez l'accès pour téléchargements confidentiels.",
  investors02Q: "Y a-t-il une NDA avant matériaux confidentiels ?",
  investors02A: "Un stub NDA en session navigateur débloque les placeholders preview aujourd'hui ; cap table, finances et legal complets exigent accès signé via contact. Enregistrement documents actif ; upload S3 presigned dépend de l'env API.",
  investors03Q: "Quelles métriques sans réunion ?",
  investors03A: "Stats MVP live et dashboards métriques investisseur (jobs validés, signaux santé système, usage produit où instrumenté). Traction bêta, pas finances auditées — celles-ci derrière accès confidentiel.",
  investors04Q: "Comment pensez-vous l'économie de vérification placement ?",
  investors04A: "Nous évitons le « ping-pong CS » marketplace — vérification in-product assistée machine avec attestation employeur et webhooks ATS optionnels. Mieux pour la marge brute que boucles e-mail manuelles, avec exceptions seulement si besoin.",
  investors05Q: "Qu'est-ce qui est défendable vs les job boards ?",
  investors05A: "Normalisation cross-board, automatisation avec consentement, UX orientée acceptation des deux côtés et résultats synchronisés au calendrier. Les boards optimisent les annonces ; TWIN optimise le chemin discovery → placement vérifié avec moins de bruit.",
  investors06Q: "Phase actuelle et traction honnête ?",
  investors06A: "MVP phase 1 : FastAPI + Celery + Postgres, scrapers boards PL, matching, candidatures, auto-candidature et calendrier early, surfaces multi-persona. Traction en pilote — validez sur /status, pages métriques et design partners, pas volume vanité.",
  investors07Q: "Comment demander un appel diligence plus profond ?",
  investors07A: "Utilisez les flux demande d'accès confidentiel dans la data room ou contacts du workspace investisseur. Apportez votre checklist — nous préférons questions concrètes sécurité et unit economics aux tours de deck génériques.",
  investors08Q: "Je suis angel — quelle dilution et cap table ?",
  investors08A: "Pré-round institutionnel : pas de cap table public sur le site marketing. Matériaux confidentiels et termes de round après NDA et fit mutuel. Traction et profondeur produit inspectables sans réunion via métriques live et demo.",
  investors09Q: "Nous sommes VC — quel est le wedge Pologne + UE ?",
  investors09A: "Phase 1 sur boards polonais (pracuj.pl, rocketjobs.pl) avec rôles remote UE dans le feed, consentement GDPR-first et UX calendrier d'acceptation EN et PL. Expansion adapter-driven (registre boards + compliance), pas clone mono-pays.",
  investors10Q: "Nous sommes PE — y a-t-il revenus et finances auditées ?",
  investors10A: "Réponse honnête : traction MVP early, pas revenus échelle PE ni états audités sur le site public. Programmes enterprise et économie vérification placement sont l'histoire marge que nous construisons ; finances en diligence confidentielle quand approprié.",
  investors11Q: "Puis-je voir les unit economics avant un partner meeting ?",
  investors11A: "Oui — le calculateur scénario investisseur est illustratif (sensibilité success fee, coûts équipe, infra). Modèle diligence, pas forecast ni offre. Agrégats usage live sur /investor/metrics avec label bêta.",
  investors12Q: "Que devraient ouvrir d'abord les partners YC ?",
  investors12A: "Commencez sur /for-investors/yc : demo interactive, JSON métriques MVP, dashboard métriques et sign-in workspace pour exports. Nous préférons questions produit concrètes à walk deck générique.",
};
