import type { FaqLocaleOverlay } from "./types";

/** Supplemental FAQ copy for zh — merged after marketing-home-below-fold partial FAQ. */
export const faqZh: FaqLocaleOverlay = {
  general04Q: "什么是「接受日历」？",
  general04A: "离开后你应回到一份值得行动的短列表 — 可一键接受或拒绝的面试与档案 — 而不是成千上万份原始简历或随机面试垃圾邮件。匹配、同意、异步工作、批量接受界面与日历导出/同步都服务于这一结果。",
  general05Q: "隐私与 GDPR 呢？",
  general05A: "注册时你给予明确同意。档案数据驱动排序与产品功能。保留、导出与权利见隐私政策。我们尽量减少对雇主的意外联系；安置验证默认为产品内自助流程。",
  candidates01Q: "职位匹配如何工作？",
  candidates01A: "已上线：启用招聘板的职位会存储、去重并按档案信号（技能、偏好、历史）排序。匹配说明在公开阶段持续改进 — 目标是更少误报，而非最大投递量。",
  candidates02Q: "支持哪些招聘板？",
  candidates02A: "阶段 1：波兰板如 pracuj.pl、rocketjobs.pl，以及配置的 LinkedIn。你可选择来源；测试期爬虫可能在运维白名单上。合规与可靠性允许时增加更多板。",
  candidates03Q: "什么是自动投递 — 是否已上线？",
  candidates03A: "夜间自动投递仅在明确同意且招聘板流程可安全自动化时运行。仓库内已有 Celery 调度 — 视为测试版：并非每个职位都符合资格。你可在管道中查看发送与状态。",
  candidates04Q: "TWIN 能否为职位定制简历？",
  candidates04A: "可以 — 职业助手在档案有简历时提供针对具体职位的 ATS 导向简历优化。输出为草稿供你审阅；未经你选择不会静默替换主简历。",
  candidates05Q: "职业助手包含什么？",
  candidates05A: "已上线：公司情报、求职信草稿、招聘经理洞察、面试准备、谈判要点、跟进邮件与 LinkedIn 建议 — 均需档案数据与明确使用。功能在演进；以应用内标签为准。",
  candidates06Q: "日历与面试预留如何工作？",
  candidates06A: "已交付：Google Calendar OAuth（忙碌时间 + 配置的预留）、WebCal 订阅链接与 ICS 导出。配置 API 凭证后通过 Graph 接入 Microsoft 365 OAuth。Apple 用户通常用 WebCal/ICS — 没有统一的「用 Apple 日历登录」。",
  candidates07Q: "什么是候选人接受队列？",
  candidates07A: "仪表板上的短列表：面试预留与强匹配可保留、改期或拒绝 — 让日历更有意图。补充招聘方提议时段；不是第二个垃圾收件箱。",
  candidates08Q: "候选人安置验证如何工作？",
  candidates08A: "应用内自声明、可选工作邮箱魔法链接与雇主一键证明链接 — 而非 endless「签了吗？」邮件循环。完整状态机与计费分阶段上线；见 docs/PLACEMENT_VERIFICATION.md。",
  candidates09Q: "候选人定价如何？",
  candidates09A: "付费计划通过 Stripe 结账；创始候补活动可按公布条款为早期队列提供免费访问。登录后查看计费 — FAQ 不报价隐藏费用。",
  candidates10Q: "TWIN 会取代招聘方吗？",
  candidates10A: "不会。减少双方噪音：候选人获得更少但更合适的动作；招聘方获得批量接受与 ATS 友好信号而非盲目简历洪流。录用仍由人决定；软件处理排序、文书与日程卫生。",
  candidates11Q: "依赖分阶段自动化前应做什么？",
  candidates11A: "完善档案、上传简历、需要预留则连接日历、仅启用信任的招聘板并仔细阅读自动投递同意。从收藏与手动申请开始。生产环境今日暂停自动投递 — 先准备仅准备包。",
  recruiters01Q: "什么是招聘方接受收件箱？",
  recruiters01A: "公司 slug 的试点界面：短队列申请可接受面试或拒绝，不以邮件为系统记录。需要 TWIN 试点链接的招聘方令牌 — 非公开开放收件箱。",
  recruiters02Q: "批量接受与普通 ATS 收件箱有何不同？",
  recruiters02A: "批量接受针对预限定行：一屏接受或跳过，导向日历就绪的下一步。不追求最大申请量 — 质量与匹配门槛优先。",
  recruiters03Q: "我能在 TWIN 发布职位吗？",
  recruiters03A: "可以 — 绑定公司 slug 的招聘方工作区可发布雇主职位。在配置下与抓取职位共用匹配与申请对象。",
  recruiters04Q: "目前有哪些 ATS 集成？",
  recruiters04A: "Greenhouse、Lever、Ashby 的录用 webhook 可在申请关联 external_ats_id 时标记安置已验证。设置 API 环境变量时显示 Greenhouse/Lever OAuth；否则手动配置 webhook。集成管道 — 非完整 ATS 替代。",
  recruiters05Q: "如何将申请关联到 Greenhouse？",
  recruiters05A: "在 TWIN 申请行存储 external_ats_id 与 external_ats_provider（greenhouse、lever、ashby）以核对录用事件。见仓库 ATS_WEBHOOKS.md 与应用内 ATS webhook 页面。",
  recruiters06Q: "TWIN 跟踪哪些管道阶段？",
  recruiters06A: "候选人见单一管道中的申请状态；招聘方见面向接受的队列与雇主证明流程。更深 ATS 阶段同步在路线图中 — 今日聚焦接受就绪交接。",
  recruiters07Q: "招聘方席位如何计费？",
  recruiters07A: "招聘方席位为发票导向的 B2B SKU（非候选人 Stripe 结账）。合同约定席位数、公司 slug 访问及是否含 ATS webhook 或证明链接。",
  recruiters08Q: "雇主能否在没有 TWIN 账户时确认录用？",
  recruiters08A: "可以 — 候选人可分享一键雇主证明 URL（nonce，过期）供招聘经理无需登录确认。机器辅助验证替代客服邮件乒乓。",
  recruiters09Q: "招聘方还有哪些未上线？",
  recruiters09A: "完整企业 SSO、深度双向 ATS 阶段同步与成熟多租户治理仍在加固。试点客户应预期基于令牌的收件箱与 webhook 优先的 ATS 钩子。",
  companies01Q: "企业从 TWIN 购买什么？",
  companies01A: "年度 B2B 计划：寻源覆盖、招聘方席位、可选 ATS webhook 验证与对齐已验证录用的安置经济 — 非按简历付费垃圾。采购友好 SKU 与候选人订阅分离。",
  companies02Q: "采购通常如何启动？",
  companies02A: "标准路径：安全问卷、DPA、年度订单表与定义的公司 slug。数据流（抓取、AI、日历）在法律包中；机密财务不在公开站。",
  companies03Q: "费用相关的安置如何验证？",
  companies03A: "默认：自助候选人声明加可选工作邮箱证明与雇主证明或 ATS 录用 webhook — 仅追加事件，无团队追逐「签了吗？」邮件。争议进异常队列，非手动乒乓。",
  companies04Q: "我们的 ATS 能否为真相来源？",
  companies04A: "录用确认可以 — 合同约定时 Greenhouse、Lever 或 Ashby webhook 为首选。TWIN 仍为候选人展示发现与匹配；ATS 可主导 requisition 生命周期。",
  companies05Q: "哪些数据离开我们边界？",
  companies05A: "候选人档案、申请事件与你授权的 optional 日历元数据。雇主证明点击记录确认无需完整 TWIN 账户。子处理方与区域见隐私政策与 B2B DPA。",
  companies06Q: "会意外联系我们的员工或候选人吗？",
  companies06A: "无意外雇主外呼活动。事务邮件限于同意流程（魔法链接、候选人发起的证明请求）。向员工营销非 B2B 默认。",
  companies07Q: "企业路线图上有什么？",
  companies07A: "规模化 Microsoft 日历、更丰富 SSO、ATS webhook 之外的 HRIS，以及与安置状态机绑定的自动发票资格。审计清晰时交付 — 非幻灯片说「完整系统」。",
  investors01Q: "投资者数据室在哪里？",
  investors01A: "登录后投资者工作区：公开牵引包（指标仪表板、MVP 统计 JSON、OpenAPI、状态页、计算器导出）加 cap table 与审计财务的门控占位。申请访问以下载机密材料。",
  investors02Q: "机密材料前是否有 NDA？",
  investors02A: "浏览器会话 NDA 存根今日可解锁预览占位；完整 cap table、财务与法律仍需通过联系签署访问。文档注册可用；S3 预签名上传依赖 API 环境配置。",
  investors03Q: "不开会能看到哪些指标？",
  investors03A: "实时 MVP 统计与投资者指标仪表板（已验证职位数、系统健康信号、已埋点的产品使用）。视为 beta 牵引，非审计财务 — 后者在机密访问后。",
  investors04Q: "如何看待安置验证的经济性？",
  investors04A: "我们避免市场常见的「客服乒乓」 — 产品内机器辅助验证，可选雇主证明与 ATS webhook。比手动邮件循环更易扩展毛利，争议仅走例外路径。",
  investors05Q: "相对招聘板何谓可防御？",
  investors05A: "跨板规范化、同意门控自动化、双方面向接受的 UX 与日历同步结果。招聘板优化列表；TWIN 优化从发现到已验证安置的路径并减少噪音。",
  investors06Q: "当前阶段与诚实牵引？",
  investors06A: "阶段 1 MVP：FastAPI + Celery + Postgres、波兰板爬虫、匹配、申请、早期自动投递与日历集成、多角色界面。试点形态牵引 — 在 /status、指标页与设计伙伴处验证，非虚荣量。",
  investors07Q: "如何申请更深入的尽调通话？",
  investors07A: "使用数据室机密访问流程或投资者工作区联系路径。带上清单 — 我们偏好具体安全与单位经济问题，而非泛泛 deck 巡游。",
  investors08Q: "我是天使 — 稀释与 cap table 如何？",
  investors08A: "机构轮前：营销站无公开 cap table。NDA 与双方契合后分享机密材料与轮次条款。可通过实时指标与演示路径不开会检视牵引与产品深度。",
  investors09Q: "我们是 VC — 波兰 + 欧盟楔子是什么？",
  investors09A: "阶段 1 在波兰板（pracuj.pl、rocketjobs.pl）上线，信息流含欧盟远程职位、GDPR 优先同意与中英波接受日历 UX。扩张靠适配器（板注册表 + 合规），非单国招聘板克隆。",
  investors10Q: "我们是 PE — 有收入与审计财务吗？",
  investors10A: "诚实回答：早期 MVP 牵引，非 PE 规模收入或公开站审计报表。企业计划与安置验证经济是我们正在构建的毛利故事；财务在适当时机密尽调中。",
  investors11Q: "合伙人会议前能看单位经济吗？",
  investors11A: "可以 — 投资者情景计算器为示意（成功费敏感度、团队成本、基础设施）。尽调模型，非预测或要约。实时使用汇总在 /investor/metrics，带 beta 标签。",
  investors12Q: "YC 合伙人应先打开什么？",
  investors12A: "从 /for-investors/yc 开始：交互演示、实时 MVP 统计 JSON、指标仪表板与工作区登录导出。我们偏好具体产品问题，而非泛泛 deck 巡游。",
};
