import type { JobListing } from "@/lib/career/job-types";

/** Sample listings across IT, Sales, Marketing, HR, CS, Engineering, Product. */
export const MOCK_JOBS: JobListing[] = [
  {
    id: "mock-1",
    jobBoard: "rocketjobs",
    title: "Senior Python Developer",
    company: "FinFlow",
    location: "Warsaw, Poland",
    city: "Warsaw",
    workFormat: "hybrid",
    seniority: "senior",
    department: "Engineering",
    salaryMin: 22000,
    salaryMax: 28000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Python", "FastAPI", "PostgreSQL"],
    description: "Build payment APIs and internal tooling.",
    url: "https://example.com/jobs/1",
    scrapedAt: "2026-05-20T10:00:00Z",
    isValidated: true,
  },
  {
    id: "mock-2",
    jobBoard: "pracuj",
    title: "Account Executive — SaaS",
    company: "ScalePL",
    location: "Kraków, Poland",
    city: "Kraków",
    department: "Sales",
    seniority: "mid",
    salaryMin: 12000,
    salaryMax: 18000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Salesforce", "B2B"],
    description: "Own mid-market SaaS pipeline.",
    url: "https://example.com/jobs/2",
    scrapedAt: "2026-05-19T10:00:00Z",
  },
  {
    id: "mock-3",
    jobBoard: "justjoin",
    title: "Growth Marketing Manager",
    company: "Nova Apps",
    location: "Remote",
    city: "Remote",
    workFormat: "remote",
    department: "Marketing",
    seniority: "senior",
    salaryMin: 15000,
    salaryMax: 22000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["SQL", "Figma", "GA4"],
    url: "https://example.com/jobs/3",
    scrapedAt: "2026-05-18T10:00:00Z",
  },
  {
    id: "mock-4",
    jobBoard: "pracuj",
    title: "IT Recruiter",
    company: "PeopleFirst",
    location: "Wrocław, Poland",
    city: "Wrocław",
    department: "HR",
    seniority: "mid",
    salaryMin: 9000,
    salaryMax: 13000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Greenhouse", "LinkedIn"],
    url: "https://example.com/jobs/4",
    scrapedAt: "2026-05-17T10:00:00Z",
  },
  {
    id: "mock-5",
    jobBoard: "rocketjobs",
    title: "Customer Success Manager",
    company: "CloudDesk",
    location: "Gdańsk, Poland",
    city: "Gdańsk",
    department: "Customer Success",
    seniority: "mid",
    salaryMin: 11000,
    salaryMax: 15000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Zendesk", "SQL"],
    url: "https://example.com/jobs/5",
    scrapedAt: "2026-05-16T10:00:00Z",
  },
  {
    id: "mock-6",
    jobBoard: "justjoin",
    title: "Staff Software Engineer",
    company: "DataRail",
    location: "Remote",
    city: "Remote",
    workFormat: "remote",
    department: "Engineering",
    seniority: "lead",
    salaryMin: 30000,
    salaryMax: 38000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Go", "Kubernetes", "PostgreSQL"],
    url: "https://example.com/jobs/6",
    scrapedAt: "2026-05-15T10:00:00Z",
    isValidated: true,
  },
  {
    id: "mock-7",
    jobBoard: "pracuj",
    title: "Product Manager — B2B",
    company: "LedgerOne",
    location: "Warsaw, Poland",
    city: "Warsaw",
    department: "Product",
    seniority: "senior",
    salaryMin: 18000,
    salaryMax: 26000,
    salaryCurrency: "PLN",
    salaryPeriod: "monthly",
    skills: ["Roadmapping", "Jira"],
    url: "https://example.com/jobs/7",
    scrapedAt: "2026-05-14T10:00:00Z",
  },
];
