import type { Locale } from "@/lib/i18n";

type Overlay = { investorDataRoom: Record<string, string> };

const es: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Sala de datos para inversores",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const it: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Data room investitori",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const fr: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Data room investisseurs",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const de: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Investor Data Room",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const zh: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "投资者数据室",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const ar: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "غرفة بيانات المستثمرين",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const ja: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "投資家向けデータルーム",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

export const INVESTOR_DATA_ROOM_OVERLAYS: Record<Exclude<Locale, "en" | "pl">, Overlay> = { es, it, fr, de, zh, ar, ja };
