import type { Locale } from "@/lib/i18n";

type Overlay = { investorDataRoom: Record<string, string> };

const es: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Sala de datos para inversores",
    "lead": "Documentación pública en GitHub, superficies de producto verificables y marcadores confidenciales — solicita acceso para cap table y estados financieros auditados.",
    "transparencyTitle": "Transparencia antes del hype",
    "transparencyBody": "Sin cifras de tracción inventadas ni enlaces ocultos a archivos sensibles en esta página. Los materiales públicos están enlazados; cap table y finanzas requieren NDA firmado y confirmación del fundador.",
    "publicDocsTitle": "Documentos públicos (repositorio)",
    "publicDocsLead": "Markdown auditable en GitHub — no descargas opacas.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Superficies en vivo",
    "liveSurfacesLead": "Métricas y estado que puedes verificar tú mismo — no capturas estáticas.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const it: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Data room investitori",
    "lead": "Documentazione GitHub pubblica, superfici prodotto verificabili e placeholder riservati — richiedi accesso per cap table e bilanci auditati.",
    "transparencyTitle": "Trasparenza prima dell'hype",
    "transparencyBody": "Nessun numero di trazione inventato né link nascosti a file sensibili su questa pagina. I materiali pubblici sono collegati; cap table e finanze richiedono NDA firmato e conferma del founder.",
    "publicDocsTitle": "Documenti pubblici (repository)",
    "publicDocsLead": "Markdown verificabile su GitHub — non download opachi.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Superfici live",
    "liveSurfacesLead": "Metriche e stato che puoi verificare tu — non screenshot statici.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const fr: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Data room investisseurs",
    "lead": "Docs GitHub publics, surfaces produit vérifiables et placeholders confidentiels — demandez l'accès pour cap table et états financiers audités.",
    "transparencyTitle": "Transparence avant le hype",
    "transparencyBody": "Pas de chiffres de traction inventés ni de liens cachés vers des fichiers sensibles sur cette page. Les matériaux publics sont liés ; cap table et finances exigent un NDA signé et confirmation du fondateur.",
    "publicDocsTitle": "Documents publics (dépôt)",
    "publicDocsLead": "Markdown auditable sur GitHub — pas de téléchargements opaques.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Surfaces en direct",
    "liveSurfacesLead": "Métriques et statut que vous pouvez vérifier vous-même — pas de captures statiques.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const de: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "Investor Data Room",
    "lead": "Öffentliche GitHub-Dokumentation, verifizierbare Produktflächen und vertrauliche Platzhalter — Zugang für Cap Table und geprüfte Finanzen anfragen.",
    "transparencyTitle": "Transparenz vor Hype",
    "transparencyBody": "Keine erfundenen Traktionszahlen und keine versteckten Links zu sensiblen Dateien auf dieser Seite. Öffentliche Materialien sind verlinkt; Cap Table und Finanzen erfordern unterzeichnetes NDA und Founder-Bestätigung.",
    "publicDocsTitle": "Öffentliche Dokumente (Repository)",
    "publicDocsLead": "Prüfbares Markdown auf GitHub — keine undurchsichtigen Downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live-Oberflächen",
    "liveSurfacesLead": "Metriken und Status, die Sie selbst prüfen können — keine statischen Screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const zh: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "投资者数据室",
    "lead": "公开 GitHub 文档、可验证的产品界面与保密占位 — 申请访问 cap table 与经审计财务报表。",
    "transparencyTitle": "务实透明优先",
    "transparencyBody": "本页无虚构增长数字，也无敏感文件隐藏链接。公开材料已链接；cap table 与财务需签署 NDA 及创始人确认。",
    "publicDocsTitle": "公开文档（仓库）",
    "publicDocsLead": "GitHub 上可审计的 Markdown — 非不透明下载。",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "实时界面",
    "liveSurfacesLead": "可自行验证的指标与状态 — 非静态截图。",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const ar: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "غرفة بيانات المستثمرين",
    "lead": "مستندات GitHub عامة وأسطح منتج قابلة للتحقق وعناصر سرية مؤقتة — اطلب الوصول لجدول رأس المال والبيانات المالية المدققة.",
    "transparencyTitle": "الشفافية قبل الضجيج",
    "transparencyBody": "لا أرقام جذب مُختلَقة ولا روابط مخفية لملفات حساسة في هذه الصفحة. المواد العامة مرتبطة؛ جدول رأس المال والمالية يتطلبان NDA موقّعًا وتأكيد المؤسس.",
    "publicDocsTitle": "مستندات عامة (المستودع)",
    "publicDocsLead": "Markdown قابل للتدقيق على GitHub — ليس تنزيلات غامضة.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "أسطح حية",
    "liveSurfacesLead": "مقاييس وحالة يمكنك التحقق منها بنفسك — ليست لقطات ثابتة.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

const ja: Overlay = {
  "investorDataRoom": {
    "eyebrow": "Due diligence",
    "title": "投資家向けデータルーム",
    "lead": "Public GitHub docs, live product surfaces you can verify, and confidential placeholders — request access for cap table and audited financials.",
    "transparencyTitle": "Transparency before hype",
    "transparencyBody": "No invented traction numbers and no hidden links to sensitive files on this page. Public materials are linked; cap table and financials require a signed NDA and founder confirmation.",
    "publicDocsTitle": "Public documents (repository)",
    "publicDocsLead": "Auditable Markdown on GitHub — not opaque downloads.",
    "docDueDiligencePack": "CTO / investor due diligence pack",
    "docDemoRunbook": "Investor demo runbook",
    "docPlacementVerification": "Placement verification design",
    "docQaTop10": "Investor top-10 Q&A",
    "liveSurfacesTitle": "Live surfaces",
    "liveSurfacesLead": "Metrics and status you can verify yourself — not static screenshots.",
    "liveMetrics": "Metrics dashboard",
    "liveStatus": "System status",
    "liveCalculator": "Scenario calculator",
    "liveOpenApi": "OpenAPI schema",
    "confidentialTitle": "Confidential (on request)",
    "confidentialLead": "Placeholders without URLs — access follows review of your request.",
    "confidentialCap": "Cap table & dilution",
    "confidentialFin": "Financial statements",
    "confidentialLegal": "Legal & compliance pack",
    "confidentialPlaceholderNote": "Available after signed access — no direct link on this page.",
    "founderTitle": "Founder contact",
    "founderLead": "Email with your fund, stage, and diligence timeline; we reply with next steps.",
    "requestAccessCta": "Request access by email",
    "contactFormCta": "Contact form",
    "backInvestor": "Investor workspace",
    "mailtoSubject": "TWIN — investor data room access request",
    "mailtoBody": "Hi TWIN team,\\n\\nI would like access to the confidential data room.\\n\\nFund / organization:\\nStage & check size:\\nDiligence timeline:\\n\\nThanks,"
  }
};

export const INVESTOR_DATA_ROOM_OVERLAYS: Record<Exclude<Locale, "en" | "pl">, Overlay> = { es, it, fr, de, zh, ar, ja };
