"""Epic 2.24 — Candidate-controlled TOTP MFA constants.

MFA_DEFAULT=OFF; MFA_ENROLLMENT=OPT_IN_ONLY; MANDATORY_MFA=OFF.
PASSKEYS_WEBAUTHN=DEFERRED_NOT_STARTED. No SMS/email OTP.
"""

from __future__ import annotations

FACTOR_SCHEMA_ID = "twin.candidate_mfa_factor/v1"
ENROLLMENT_SCHEMA_ID = "twin.candidate_mfa_enrollment/v1"
CHALLENGE_SCHEMA_ID = "twin.candidate_mfa_challenge/v1"
RECOVERY_CODE_SET_SCHEMA_ID = "twin.candidate_mfa_recovery_code_set/v1"
SESSION_ASSURANCE_SCHEMA_ID = "twin.candidate_mfa_session_assurance/v1"
CONTRACT_ID = "candidate_totp_mfa_v1"
FIRST_VALUE_CONTRACT = "pilot_first_value_v1"

MFA_DEFAULT = "OFF"
MFA_ENROLLMENT = "OPT_IN_ONLY"
MANDATORY_MFA = "OFF"
PASSKEYS_WEBAUTHN = "DEFERRED_NOT_STARTED"

PARALLEL_MFA_STORE = "NONE"
PARALLEL_SESSION_STORE = "NONE"
CANONICAL_SESSION_AUTHORITY = "twin.candidate_auth_session"

FIRST_VALUE_SATISFIED_BY_MFA = False
FINGERPRINTING = False
BEHAVIORAL_SCORING = False
TRUSTED_DEVICES = False
EIGHTH_PRIMARY_NAV = False

PROVIDER_REUSE_GATE = "USE_MATURE_RFC6238_LIBRARY_PYOTP"
TOTP_LIBRARY = "pyotp"

# State machine
STATE_DISABLED = "DISABLED"
STATE_PENDING_FACTOR = "PENDING_FACTOR"
STATE_FACTOR_VERIFIED = "FACTOR_VERIFIED"
STATE_RECOVERY_CODES_PRESENTED = "RECOVERY_CODES_PRESENTED"
STATE_ENABLED = "ENABLED"
STATE_REVOKED = "REVOKED"

CHALLENGE_TTL_SECONDS = 5 * 60
TOTP_DIGITS = 6
TOTP_INTERVAL = 30
TOTP_VALID_WINDOW = 1  # ±1
TOTP_SECRET_BITS = 160

RECOVERY_CODE_COUNT = 10
RECOVERY_CODE_LENGTH = 10

ASSURANCE_AAL1 = "AAL1_PRIMARY"
ASSURANCE_AAL2_TOTP = "AAL2_TOTP"
ASSURANCE_AAL2_RECOVERY = "AAL2_RECOVERY_CODE"

PURPOSE_MFA_ENROLL = "MFA_ENROLL"
PURPOSE_MFA_DISABLE = "MFA_DISABLE"
PURPOSE_MFA_REPLACE = "MFA_REPLACE"
PURPOSE_MFA_RECOVERY_RESET = "MFA_RECOVERY_RESET"

MFA_STEP_UP_PURPOSES = frozenset(
    {
        PURPOSE_MFA_ENROLL,
        PURPOSE_MFA_DISABLE,
        PURPOSE_MFA_REPLACE,
        PURPOSE_MFA_RECOVERY_RESET,
    }
)

CHALLENGE_KIND_LOGIN = "LOGIN"
CHALLENGE_KIND_STEP_UP = "STEP_UP"
METHOD_TOTP = "totp"
METHOD_RECOVERY_CODE = "recovery_code"
