"""Epic 2.26 — Candidate-owned adaptive interview practice constants."""

from __future__ import annotations

SCHEMA_ID = "twin.candidate_interview_practice/v1"
TURN_SCHEMA_ID = "twin.candidate_interview_practice_turn/v1"
CATALOG_SCHEMA_ID = "twin.candidate_interview_exercise_catalog/v1"
EXERCISE_CATALOG_SCHEMA_ID = CATALOG_SCHEMA_ID
FIRST_VALUE_CONTRACT = "pilot_first_value_v1"

PARALLEL_PRACTICE_STORE = "NONE"
EIGHTH_PRIMARY_NAV = False
GLOBAL_SKILL_SCORES = False
EMPLOYER_RANKING = False
ATS_INTEGRATION = False
PSYCHOMETRICS = False
WEBCAM_PROCTORING = False
KEYSTROKE_BEHAVIORAL = False
PERSONALITY_SCORING = False
EMOTION_SCORING = False

MAX_TURNS_PER_SESSION = 8
MAX_ACTIVE_SESSIONS = 5
MAX_ANSWER_CHARS = 8000

STATE_DRAFT = "DRAFT"
STATE_IN_PROGRESS = "IN_PROGRESS"
STATE_AWAITING_EVALUATION = "AWAITING_EVALUATION"
STATE_EVALUATED = "EVALUATED"
STATE_COMPLETED = "COMPLETED"
STATE_ABANDONED = "ABANDONED"
STATE_DELETED = "DELETED"

SESSION_STATES = frozenset(
    {
        STATE_DRAFT,
        STATE_IN_PROGRESS,
        STATE_AWAITING_EVALUATION,
        STATE_EVALUATED,
        STATE_COMPLETED,
        STATE_ABANDONED,
        STATE_DELETED,
    }
)

TURN_DRAFT = "DRAFT"
TURN_SUBMITTED = "SUBMITTED"
TURN_EVALUATED = "EVALUATED"
TURN_SKIPPED = "SKIPPED"
TURN_SUPERSEDED = "SUPERSEDED"

EVAL_EVALUATED = "EVALUATED"
EVAL_UNAVAILABLE = "EVALUATION_UNAVAILABLE"
EVAL_INSUFFICIENT = "INSUFFICIENT_INFORMATION"

OUTCOME_SUPPORTED = "SUPPORTED_IN_RESPONSE"
OUTCOME_PARTIAL = "PARTIALLY_SUPPORTED"
OUTCOME_NOT_DEMONSTRATED = "NOT_DEMONSTRATED"
OUTCOME_NOT_ASSESSED = "NOT_ASSESSED"
OUTCOME_INSUFFICIENT = "INSUFFICIENT_INFORMATION"
OUTCOME_UNAVAILABLE = "EVALUATION_UNAVAILABLE"

DETERMINISTIC_FALLBACK_LABEL = "DETERMINISTIC_LIBRARY_FALLBACK"

EVIDENCE_LABEL_PRACTICE_WORK_SAMPLE = "PRACTICE_WORK_SAMPLE"
CLAIM_KIND_PRACTICE = "CANDIDATE_CONFIRMED"

# v2 exercise tracks (M2 rewrite); v1 families kept as FAMILIES_V1 for legacy refs
FAMILIES = ("software_backend", "business_data", "customer_b2b")
FAMILIES_V1 = ("behavioral_star", "role_problem", "clarifying_questions")

# Frozenset of all valid criterion outcome values
CRITERION_OUTCOMES = frozenset(
    {
        OUTCOME_SUPPORTED,
        OUTCOME_PARTIAL,
        OUTCOME_NOT_DEMONSTRATED,
        OUTCOME_NOT_ASSESSED,
        OUTCOME_INSUFFICIENT,
        OUTCOME_UNAVAILABLE,
    }
)

# Alembic schema identifier used in build_aggregate / tests (v2 - canonical)
SCHEMA_ID_V2 = "twin.candidate_adaptive_interview_practice/v1"
# Exercise family tuples (also exported as EXERCISE_FAMILIES for legacy refs)
EXERCISE_FAMILIES = FAMILIES

# Evaluation statuses used in practice service (additional to EVAL_*)
EVAL_PENDING = "PENDING"
EVAL_COMPLETE = "COMPLETE"
