"""Epic 2.23 — Candidate account recovery + step-up constants.

Extend password_reset_tokens — do not fork. MFA/passkeys DEFERRED.
PARALLEL_IDENTITY/CREDENTIAL/MANAGED_SESSION/PASSWORD_RESET/RECOVERY_CHANNEL=NONE.
"""

from __future__ import annotations

RECOVERY_SCHEMA_ID = "twin.candidate_account_recovery/v1"
COMPLETION_SCHEMA_ID = "twin.candidate_recovery_completion/v1"
STEP_UP_SCHEMA_ID = "twin.candidate_step_up_reauthentication/v1"
CONTRACT_ID = "candidate_account_recovery_v1"
FIRST_VALUE_CONTRACT = "pilot_first_value_v1"

PARALLEL_IDENTITY_STORE = "NONE"
PARALLEL_CREDENTIAL_STORE = "NONE"
PARALLEL_MANAGED_SESSION_STORE = "NONE"
PARALLEL_PASSWORD_RESET_STORE = "NONE"
PARALLEL_RECOVERY_CHANNEL = "NONE"

CANONICAL_SESSION_AUTHORITY = "twin.candidate_auth_session"
MFA_PASSKEYS = "DEFERRED_NOT_STARTED"  # Epic 2.24 — passkeys remain deferred; TOTP shipped

FIRST_VALUE_SATISFIED_BY_RECOVERY = False
FIRST_VALUE_SATISFIED_BY_STEP_UP = False
BEHAVIORAL_SCORING = False
FINGERPRINTING = False
EIGHTH_PRIMARY_NAV = False
NO_AUTO_MINT_FROM_RECOVERY = True

STATE_ACTIVE = "ACTIVE"
STATE_USED = "USED"
STATE_CANCELLED = "CANCELLED"
STATE_EXPIRED = "EXPIRED"

STEP_UP_TTL_SECONDS = 5 * 60

PURPOSE_SIGN_OUT_EVERYWHERE = "SIGN_OUT_EVERYWHERE"
PURPOSE_CANCEL_RECOVERY = "CANCEL_RECOVERY"
PURPOSE_CANCEL_RECOVERY_PENDING = "CANCEL_RECOVERY_PENDING"
PURPOSE_CHANGE_PASSWORD = "CHANGE_PASSWORD"
PURPOSE_ACCOUNT_DELETION = "ACCOUNT_DELETION"
PURPOSE_FULL_PRIVACY_EXPORT = "FULL_PRIVACY_EXPORT"
PURPOSE_MFA_ENROLL = "MFA_ENROLL"
PURPOSE_MFA_DISABLE = "MFA_DISABLE"
PURPOSE_MFA_REPLACE = "MFA_REPLACE"
PURPOSE_MFA_RECOVERY_RESET = "MFA_RECOVERY_RESET"

STEP_UP_PURPOSES = frozenset(
    {
        PURPOSE_SIGN_OUT_EVERYWHERE,
        PURPOSE_CANCEL_RECOVERY,
        PURPOSE_CANCEL_RECOVERY_PENDING,
        PURPOSE_CHANGE_PASSWORD,
        PURPOSE_ACCOUNT_DELETION,
        PURPOSE_FULL_PRIVACY_EXPORT,
        PURPOSE_MFA_ENROLL,
        PURPOSE_MFA_DISABLE,
        PURPOSE_MFA_REPLACE,
        PURPOSE_MFA_RECOVERY_RESET,
    }
)
