/** German overlay: nav, common, home. */
export const deOverlay: Record<string, unknown> = {
  nav: {
    login: "Anmelden",
    register: "Registrieren",
    profile: "Profil",
    dashboard: "Dashboard",
    calculator: "B2B-ROI-Rechner",
    menu: "Menü",
    ariaCompanyNav: "Unternehmensnavigation",
    ariaAccountNav: "Kontonavigation",
    ariaMobileNav: "Hauptmenü",
  },
  common: {
    language: "Sprache",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "Wird geladen",
    loadingEllipsis: "Wird geladen…",
    errorTitle: "Etwas ist schiefgelaufen",
    errorBody: "Bitte erneut versuchen. Wenn das Problem bleibt, Seite neu laden.",
    tryAgain: "Erneut versuchen",
  },
  meta: {
    titleHome: "TWIN — Karriere-Agent",
    titleAbout: "Über uns — TWIN",
    titleCaseStudies: "Fallstudien — TWIN",
    titleFaq: "FAQ — TWIN",
    titlePartners: "Partner — TWIN",
    titleMedia: "Medien — TWIN",
    titleCareers: "Karriere — TWIN",
    titleContact: "Kontakt — TWIN",
    titleCalculator: "B2B-ROI-Rechner — TWIN",
    titleLogin: "Anmelden — TWIN",
    titleRegister: "Registrieren — TWIN",
    titleProfile: "Profil — TWIN",
    titleDashboard: "Dashboard — TWIN",
    titlePrivacy: "Datenschutz — TWIN",
    titleForgotPassword: "Passwort vergessen — TWIN",
    titleResetPassword: "Neues Passwort — TWIN",
    titleOnboarding: "Workspace-Tour — TWIN",
    titleBilling: "Plan & Abrechnung — TWIN",
    titleAuthCallback: "Anmeldung — TWIN",
  },
  privacy: {
    title: "Datenschutzerklärung (MVP)",
    updated: "Stand: Mai 2026",
    collectTitle: "Welche Daten wir erfassen",
    collect1: "E-Mail-Konto und Passwort (gehasht)",
    collect2: "Karriereprofil: Skills, Erfahrung, Gehaltsvorstellungen, Standort",
    collect3: "Bewerbungs- und Matching-Verlauf in TWIN",
    whyTitle: "Warum wir Daten verarbeiten",
    whyBody:
      "Um Sie mit Stellen von pracuj.pl und rocketjobs.pl zu matchen und den Bewerbungsstatus zu verfolgen. Rechtsgrundlage: Ihre ausdrückliche Einwilligung bei der Registrierung (DSGVO Art. 6 Abs. 1 lit. a).",
    rightsTitle: "Ihre Rechte",
    rightsBody:
      "Sie können Auskunft, Berichtigung oder Löschung beantragen, indem Sie das TWIN-Team kontaktieren. Die Einwilligung können Sie durch Löschen des Kontos widerrufen (Funktion in einer späteren Version).",
    retentionTitle: "Aufbewahrung",
    retentionBody: "Daten werden aufbewahrt, solange das Konto aktiv ist, und auf Anfrage gelöscht.",
    thirdTitle: "Dritte",
    thirdBody:
      "Für das Matching nutzen wir Anthropic Claude. Stellendaten stammen aus öffentlichen Ausschreibungen der genannten Jobbörsen.",
  },
  home: {
    tagline: "Globale Karriereplattform, unterstützt durch KI",
    title: "Ihr KI-Karrierezwilling arbeitet rund um die Uhr am Markt",
    description:
      "TWIN ist ein autonomer Karriere-Agent für Fachkräfte weltweit: Er bündelt Stellen von Jobbörsen und Regionen, die Ihr Workspace freischaltet, bewertet sie gegen Ihr Profil und hält Ihre Pipeline an einem Ort — mit Auto-Bewerbung und Interview-Planung auf der Roadmap.",
    getStarted: "Kostenlos starten",
    logIn: "Einloggen",
    scrape: "Entdecken",
    scrapeDesc: "Börsen und Regionen nach Ihrer Konfiguration — erweiterbar mit Ihrem Wachstum",
    match: "Matching",
    matchDesc: "Bewertet nach Skills, Seniorität und Zielen",
    track: "Verfolgen",
    trackDesc: "Ein Workspace für Suche, Merkliste und Bewerbungen",
    featuresTitle: "Vom Signal zur Pipeline",
    featuresSubtitle:
      "Ein ruhiger Workspace, der spiegelt, wie Sie den Markt schon denken — mit Automatisierung, die Schritt für Schritt kommt.",
    footerHint: "Legen Sie nach der Registrierung ein Profil an, damit das Matching Skills, Titel und Ziele nutzt.",
    twinForYourJob: "Twin für Ihre Rolle",
    focusTitle: "Was soll TWIN für Sie zuerst priorisieren?",
    focusSubtitle:
      "Wählen Sie, was jetzt am wichtigsten ist — nach der Anmeldung landen Sie im Dashboard mit Profil, Feeds und Tracking verbunden.",
    focusPickLabel: "Startfokus wählen",
    focusChipDiscover: "Neue Stellen in einem Feed",
    focusChipMatch: "Gerankte Treffer zu meinem Profil",
    focusChipTrack: "Bewerbungen speichern & verfolgen",
    focusChipAuto: "Auto-Bewerbung (Roadmap)",
    focusCta: "Mit diesen Zielen starten",
    focusFootnote:
      "Das heutige MVP aggregiert Stellen, bewertet sie, wenn Sie ein Profil hinzufügen, und bündelt den Bewerbungsstatus. Stärkere Automatisierung kommt in Etappen — dieselbe ruhige Oberfläche, mehr Autonomie dahinter.",
    faqEyebrow: "FAQ",
    faqTitle: "Fragen & Antworten",
    faqPrivacyLink: "Datenschutz",
    faq01Q: "Was ist TWIN heute?",
    faq01A:
      "Ein Pipeline-Workspace: Listings von freigeschalteten Börsen, optionales Scoring gegen Ihr Profil und ein Ort für Merkliste und Bewerbungen. Tiefere Auto-Bewerbung und Interview-Planung stehen auf der Roadmap.",
    faq02Q: "Für wen ist es?",
    faq02A:
      "Für Menschen, die schon mehrere Jobseiten und Notizen jonglieren und weniger Tabs wollen — ein Ort zum Scannen, Vergleichen und Voranbringen von Bewerbungen ohne Kontextverlust.",
    faq03Q: "Worin unterscheidet sich das von einer einzelnen Jobbörse?",
    faq03A:
      "Börsen bleiben dort, wo Stellen leben; TWIN ist die Schicht, die Discovery, Match-Signale und Follow-up in einer UX normalisiert. Wo nötig, bewerben Sie sich weiter im Arbeitgeber-Flow.",
    faq04Q: "Was ist mit meinen Daten?",
    faq04A:
      "Sie stimmen bei der Registrierung ausdrücklich zu. Profildaten nutzen wir zum Ranking und Betrieb des Produkts. Zu Aufbewahrung, Export und GDPR-Rechten lesen Sie die verlinkte Policy unten.",
  },
};
