/** Spanish overlay: nav, common, home (other sections fall back to English clone). */
export const esOverlay: Record<string, unknown> = {
  nav: {
    login: "Iniciar sesión",
    register: "Registrarse",
    profile: "Perfil",
    dashboard: "Panel",
    calculator: "Calculadora ROI B2B",
    menu: "Menú",
    ariaCompanyNav: "Navegación de empresa",
    ariaAccountNav: "Navegación de cuenta",
    ariaMobileNav: "Menú principal",
  },
  common: {
    language: "Idioma",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "Cargando",
    loadingEllipsis: "Cargando…",
    errorTitle: "Algo salió mal",
    errorBody: "Inténtalo de nuevo. Si el problema continúa, actualiza la página.",
    tryAgain: "Reintentar",
  },
  meta: {
    titleHome: "TWIN — Agente de carrera",
    titleAbout: "Sobre nosotros — TWIN",
    titleCaseStudies: "Casos de estudio — TWIN",
    titleFaq: "FAQ — TWIN",
    titlePartners: "Socios — TWIN",
    titleMedia: "Medios — TWIN",
    titleCareers: "Carreras — TWIN",
    titleContact: "Contacto — TWIN",
    titleCalculator: "Calculadora ROI B2B — TWIN",
    titleLogin: "Iniciar sesión — TWIN",
    titleRegister: "Registrarse — TWIN",
    titleProfile: "Perfil — TWIN",
    titleDashboard: "Panel — TWIN",
    titlePrivacy: "Privacidad — TWIN",
    titleForgotPassword: "Contraseña olvidada — TWIN",
    titleResetPassword: "Nueva contraseña — TWIN",
    titleOnboarding: "Tour del espacio de trabajo — TWIN",
    titleBilling: "Plan y facturación — TWIN",
    titleAuthCallback: "Iniciando sesión — TWIN",
  },
  privacy: {
    title: "Política de privacidad (MVP)",
    updated: "Última actualización: mayo 2026",
    collectTitle: "Qué recopilamos",
    collect1: "Correo de la cuenta y contraseña (hash)",
    collect2: "Perfil profesional: habilidades, experiencia, expectativas salariales, ubicación",
    collect3: "Historial de candidaturas y coincidencias en TWIN",
    whyTitle: "Por qué tratamos los datos",
    whyBody:
      "Para emparejarte con ofertas de pracuj.pl y rocketjobs.pl y seguir el estado de tus candidaturas. Base legal: tu consentimiento explícito al registrarte (RGPD art. 6(1)(a)).",
    rightsTitle: "Tus derechos",
    rightsBody:
      "Puedes solicitar acceso, rectificación o supresión contactando al equipo de TWIN. Puedes retirar el consentimiento eliminando tu cuenta (función en una versión posterior).",
    retentionTitle: "Conservación",
    retentionBody: "Conservamos los datos mientras la cuenta esté activa; los eliminamos bajo solicitud.",
    thirdTitle: "Terceros",
    thirdBody:
      "Usamos Anthropic Claude para el emparejamiento de ofertas. Los datos de empleo provienen de anuncios públicos en los portales mencionados.",
  },
  home: {
    tagline: "Plataforma global de carrera, impulsada por IA",
    title: "Tu gemelo de carrera con IA trabaja el mercado las 24 horas",
    description:
      "TWIN es un agente de carrera autónomo para profesionales de todo el mundo: agrega ofertas de los portales y regiones que habilita tu espacio de trabajo, las puntúa frente a tu perfil y mantiene tu pipeline en un solo lugar — con autoaplicación y agendado de entrevistas en la hoja de ruta.",
    getStarted: "Empezar gratis",
    logIn: "Entrar",
    scrape: "Descubrir",
    scrapeDesc: "Portales y regiones que configures — ampliable a medida que creces",
    match: "Emparejar",
    matchDesc: "Puntuación según tus habilidades, seniority y objetivos",
    track: "Seguimiento",
    trackDesc: "Un espacio para búsqueda, guardados y candidaturas",
    featuresTitle: "De la señal al pipeline",
    featuresSubtitle:
      "Un espacio de trabajo sereno que refleja cómo ya piensas en el mercado — con automatización que llega paso a paso.",
    footerHint: "Crea un perfil tras registrarte para que el emparejamiento use tus habilidades, títulos y objetivos.",
    twinForYourJob: "Gemelo para tu puesto",
    focusTitle: "¿Qué debería priorizar TWIN para ti primero?",
    focusSubtitle:
      "Elige lo que más importa ahora — tras registrarte irás al panel con perfil, feeds y seguimiento conectados.",
    focusPickLabel: "Elige un foco inicial",
    focusChipDiscover: "Nuevas ofertas en un solo feed",
    focusChipMatch: "Coincidencias ordenadas con mi perfil",
    focusChipTrack: "Guardar y seguir candidaturas",
    focusChipAuto: "Autoaplicación (en la hoja de ruta)",
    focusCta: "Empezar con estos objetivos",
    focusFootnote:
      "El MVP de hoy agrega ofertas, las puntúa cuando añades un perfil y centraliza el estado de candidaturas. La automatización más pesada llegará por fases — la misma superficie tranquila, más autonomía detrás.",
    faqEyebrow: "FAQ",
    faqTitle: "Preguntas y respuestas",
    faqPrivacyLink: "Política de privacidad",
    faq01Q: "¿Qué es TWIN hoy?",
    faq01A:
      "Un espacio de pipeline: listados de portales que habilita tu espacio de trabajo, puntuación opcional frente a tu perfil y un solo lugar para guardados y candidaturas. Autoaplicación profunda y agendado de entrevistas están en la hoja de ruta.",
    faq02Q: "¿Para quién es?",
    faq02A:
      "Para quienes ya combinan varios portales y notas y quieren menos pestañas — un lugar para revisar, comparar y avanzar candidaturas sin perder contexto.",
    faq03Q: "¿En qué se diferencia de usar un solo portal?",
    faq03A:
      "Los portales siguen alojando las ofertas; TWIN es la capa que normaliza descubrimiento, señales de encaje y seguimiento en una sola UX. Sigues aplicando en el flujo del empleador cuando haga falta.",
    faq04Q: "¿Qué pasa con mis datos?",
    faq04A:
      "Das tu consentimiento explícito al registrarte. Usamos los datos del perfil para ordenar ofertas y operar el producto. Para retención, exportaciones y derechos RGPD, lee la política enlazada abajo.",
  },
};
