/** French overlay: nav, common, home. */
export const frOverlay: Record<string, unknown> = {
  nav: {
    login: "Connexion",
    register: "Créer un compte",
    profile: "Profil",
    dashboard: "Tableau de bord",
    calculator: "Calculateur ROI B2B",
    menu: "Menu",
    ariaCompanyNav: "Navigation entreprise",
    ariaAccountNav: "Navigation du compte",
    ariaMobileNav: "Menu principal",
  },
  common: {
    language: "Langue",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "Chargement",
    loadingEllipsis: "Chargement…",
    errorTitle: "Une erreur s’est produite",
    errorBody: "Réessayez. Si le problème persiste, actualisez la page.",
    tryAgain: "Réessayer",
  },
  meta: {
    titleHome: "TWIN — Agent carrière",
    titleAbout: "À propos — TWIN",
    titleCaseStudies: "Études de cas — TWIN",
    titleFaq: "FAQ — TWIN",
    titlePartners: "Partenaires — TWIN",
    titleMedia: "Médias — TWIN",
    titleCareers: "Carrières — TWIN",
    titleContact: "Contact — TWIN",
    titleCalculator: "Calculateur ROI B2B — TWIN",
    titleLogin: "Connexion — TWIN",
    titleRegister: "Inscription — TWIN",
    titleProfile: "Profil — TWIN",
    titleDashboard: "Tableau de bord — TWIN",
    titlePrivacy: "Confidentialité — TWIN",
    titleForgotPassword: "Mot de passe oublié — TWIN",
    titleResetPassword: "Nouveau mot de passe — TWIN",
    titleOnboarding: "Visite de l’espace de travail — TWIN",
    titleBilling: "Forfait & facturation — TWIN",
    titleAuthCallback: "Connexion — TWIN",
  },
  privacy: {
    title: "Politique de confidentialité (MVP)",
    updated: "Dernière mise à jour : mai 2026",
    collectTitle: "Ce que nous collectons",
    collect1: "E-mail du compte et mot de passe (haché)",
    collect2: "Profil carrière : compétences, expérience, attentes salariales, lieu",
    collect3: "Historique des candidatures et correspondances dans TWIN",
    whyTitle: "Pourquoi nous traitons les données",
    whyBody:
      "Pour vous proposer des offres issues de pracuj.pl et rocketjobs.pl et suivre le statut des candidatures. Base légale : votre consentement explicite à l’inscription (RGPD art. 6(1)(a)).",
    rightsTitle: "Vos droits",
    rightsBody:
      "Vous pouvez demander l’accès, la rectification ou la suppression en contactant l’équipe TWIN. Vous pouvez retirer votre consentement en supprimant votre compte (fonctionnalité à venir).",
    retentionTitle: "Conservation",
    retentionBody: "Les données sont conservées tant que le compte est actif et supprimées sur demande.",
    thirdTitle: "Tiers",
    thirdBody:
      "Nous utilisons Anthropic Claude pour le matching. Les données d’emploi proviennent d’annonces publiques sur les sites mentionnés.",
  },
  home: {
    tagline: "Plateforme carrière mondiale, propulsée par l’IA",
    title: "Votre jumeau carrière IA travaille le marché en continu",
    description:
      "TWIN est un agent carrière autonome pour les professionnels partout : il agrège les offres des job boards et régions activés dans votre espace, les score par rapport à votre profil et garde votre pipeline au même endroit — avec candidature auto et planification d’entretiens sur la feuille de route.",
    getStarted: "Commencer gratuitement",
    logIn: "Se connecter",
    scrape: "Découvrir",
    scrapeDesc: "Sites et régions que vous configurez — extensibles à mesure de votre croissance",
    match: "Correspondance",
    matchDesc: "Noté selon vos compétences, séniorité et objectifs",
    track: "Suivi",
    trackDesc: "Un espace pour recherche, favoris et candidatures",
    featuresTitle: "Du signal au pipeline",
    featuresSubtitle:
      "Un espace de travail posé qui reflète comment vous pensez déjà au marché — avec une automatisation qui arrive progressivement.",
    footerHint: "Créez un profil après inscription pour que le matching utilise compétences, intitulés et objectifs.",
    twinForYourJob: "Jumeau pour votre poste",
    focusTitle: "Que doit prioriser TWIN pour vous en premier ?",
    focusSubtitle:
      "Choisissez ce qui compte le plus maintenant — après inscription vous arrivez sur le tableau de bord avec profil, flux et suivi reliés.",
    focusPickLabel: "Choisir un focus de départ",
    focusChipDiscover: "Nouvelles offres dans un seul fil",
    focusChipMatch: "Correspondances classées à mon profil",
    focusChipTrack: "Enregistrer et suivre les candidatures",
    focusChipAuto: "Candidature auto (feuille de route)",
    focusCta: "Démarrer avec ces objectifs",
    focusFootnote:
      "Le MVP d’aujourd’hui agrège les offres, les score quand vous ajoutez un profil et centralise le statut des candidatures. Une automatisation plus lourde arrive par étapes — la même surface calme, plus d’autonomie derrière.",
    faqEyebrow: "FAQ",
    faqTitle: "Questions et réponses",
    faqPrivacyLink: "Politique de confidentialité",
    faq01Q: "Qu’est-ce que TWIN aujourd’hui ?",
    faq01A:
      "Un espace pipeline : annonces des sites activés, scoring optionnel par rapport au profil et un seul endroit pour favoris et candidatures. Auto-candidature poussée et planification d’entretiens sont sur la feuille de route.",
    faq02Q: "Pour qui ?",
    faq02A:
      "Pour ceux qui jonglent déjà entre plusieurs sites et notes et veulent moins d’onglets — un lieu pour parcourir, comparer et faire avancer les candidatures sans perdre le contexte.",
    faq03Q: "En quoi est-ce différent d’un seul job board ?",
    faq03A:
      "Les boards restent là où vivent les annonces ; TWIN est la couche qui normalise découverte, signaux de match et suivi dans une même UX. Vous postulez encore sur le parcours employeur quand c’est requis.",
    faq04Q: "Et mes données ?",
    faq04A:
      "Vous consentez explicitement à l’inscription. Nous utilisons le profil pour classer les offres et faire tourner le produit. Pour conservation, exports et droits RGPD, lisez la politique liée ci-dessous.",
  },
};
