import type { Locale } from "../i18n";

type InvestorRoomOverlay = { investorRoom: Record<string, string> };

const es: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "Sala del inversor",
    title: "TWIN — vista ejecutiva honesta",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "Verificación de placement",
    statusItem_placementVerification_body: "Máquina de estados asistida — escala piloto; sin ingresos fabricados.",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const it: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "Investor room",
    title: "TWIN — vista executive onesta",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "Verifica placement",
    statusItem_placementVerification_body: "Macchina a stati assistita — scala pilota; nessun ricavo inventato.",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const fr: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "Salle investisseur",
    title: "TWIN — vue exécutive honnête",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "Vérification de placement",
    statusItem_placementVerification_body: "Machine à états assistée — échelle pilote ; pas de revenus inventés.",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const de: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "Investor Room",
    title: "TWIN — ehrliche Executive-Ansicht",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "Placement-Verifizierung",
    statusItem_placementVerification_body: "Maschinell unterstützte Zustandsmaschine — Pilotmaßstab; keine erfundenen Umsätze.",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const zh: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "投资者室",
    title: "TWIN — 诚实的执行层视图",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "入职验证",
    statusItem_placementVerification_body: "机器辅助状态机 — 试点规模；无虚构收入。",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const ar: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "غرفة المستثمر",
    title: "TWIN — رؤية تنفيذية صادقة",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "التحقق من التوظيف",
    statusItem_placementVerification_body: "آلة حالات بمساعدة آلية — نطاق تجريبي؛ بلا إيرادات مُختلَقة.",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

const ja: InvestorRoomOverlay = {
  investorRoom: {
    eyebrow: "インベスタールーム",
    title: "TWIN — 正直なエグゼクティブビュー",
    thesis: "A short calendar of acceptance — not more inbox noise.",
    lead: "Autonomous career agent: matching, consent, and async work while away → ranked pipeline → accept / decline / reschedule → calendar sync. Phase 1 MVP — Polish boards first, multi-persona platform.",
    launchStanceTitle: "Public launch stance",
    launchStanceBody: "Public launch NO-GO. Controlled pilot only: recruiter inbox verified, auto-apply PAUSED, delegated apply NOT LIVE, external recruiter invitations not sent.",
    problemTitle: "Problem",
    problemBody: "After time away, candidates and recruiters return to interview spam or thousands of unfiltered CVs. Time goes to noise, not moments worth showing up for.",
    wedgeTitle: "Market wedge",
    wedgeBody: "Matching + consent + offline work → pre-qualified pipeline → batch acceptance UI → calendar export / sync.",
    personasTitle: "Three personas",
    personasLead: "Same platform — distinct surfaces. No cohort scale claims.",
    persona_candidate_title: "Candidate",
    persona_candidate_body: "Job ranking, application transparency, Google / Microsoft calendar (candidate verified). Auto-apply PAUSED on production.",
    persona_recruiter_title: "Recruiter",
    persona_recruiter_body: "Decision console, match score, accept / decline. Manual scheduling and message drafts (copy-to-clipboard). Recruiter calendar sync NOT LIVE.",
    persona_company_title: "Company",
    persona_company_body: "B2B SKU in marketing; machine-assisted placement verification. No revenue or closed enterprise customer claims.",
    demoMapTitle: "Product demo map",
    demoMapLead: "Public or pilot routes — honestly labeled in status below.",
    demoMapInteractive: "Interactive demo (simulation)",
    demoMapMetrics: "Live MVP metrics",
    demoMapStatus: "Production status",
    demoMapCalculator: "Scenario calculator (illustrative)",
    demoMapDataRoom: "Data room (public pack)",
    demoMapRecruiterInbox: "Recruiter inbox (pilot)",
    demoMapPlacement: "Placement verification timeline",
    statusTitle: "Current status",
    statusLead: "Aligned with production reality matrices — June 2026.",
    statusSectionLive: "Live today",
    statusSectionDemo: "Demo / simulation",
    statusSectionNotLive: "Not live",
    statusLive: "Live",
    statusDemo: "Demo",
    statusNotLive: "Not live",
    statusItem_marketingPilot_title: "Marketing & pilot waitlist",
    statusItem_marketingPilot_body: "Homepage, waitlist, compare — pilot-safe; public launch NO-GO.",
    statusItem_candidateCore_title: "Candidate core",
    statusItem_candidateCore_body: "OAuth login, dashboard, ranking, application transparency — LIVE in pilot.",
    statusItem_jobCorpus_title: "Job corpus & matching",
    statusItem_jobCorpus_body: "Scraping pracuj.pl / rocketjobs.pl; coverage below long-term target.",
    statusItem_interactiveDemo_title: "Interactive demo /demo",
    statusItem_interactiveDemo_body: "8-step simulation — no production data in tour UI.",
    statusItem_candidateCalendar_title: "Candidate calendar",
    statusItem_candidateCalendar_body: "Google Calendar verified; Microsoft LIVE; Apple / ICS partial with disclosure.",
    statusItem_recruiterInbox_title: "Recruiter inbox",
    statusItem_recruiterInbox_body: "Decision console LIVE in pilot — H5b PASS; external cohort HOLD.",
    statusItem_recruiterScheduling_title: "Manual scheduling (inbox)",
    statusItem_recruiterScheduling_body: "Slot fields and copyable invite — no calendar sync, no email send.",
    statusItem_recruiterMessageDrafts_title: "Message drafts",
    statusItem_recruiterMessageDrafts_body: "Copy-to-clipboard templates — TWIN does not send email.",
    statusItem_placementVerification_title: "プレースメント検証",
    statusItem_placementVerification_body: "機械支援ステートマシン — パイロット規模；架空の収益なし。",
    statusItem_investorSurfaces_title: "Investor surfaces",
    statusItem_investorSurfaces_body: "Metrics, illustrative calculator, data room — beta aggregates.",
    statusItem_stripeBilling_title: "Stripe Checkout",
    statusItem_stripeBilling_body: "Infra LIVE; pre-revenue MRR until founder activates subscriptions.",
    statusItem_autoApply_title: "Nightly auto-apply",
    statusItem_autoApply_body: "PAUSED (ops) on production — beat disabled.",
    statusItem_delegatedApply_title: "Delegated apply",
    statusItem_delegatedApply_body: "NOT LIVE — no submit on candidate's behalf.",
    statusItem_recruiterCalendarSync_title: "Recruiter calendar sync",
    statusItem_recruiterCalendarSync_body: "Placeholder / roadmap — NOT LIVE.",
    statusItem_recruiterIntegrations_title: "Recruiter integrations",
    statusItem_recruiterIntegrations_body: "ATS planned; LinkedIn, email, calendar — NOT LIVE; no external sync.",
    statusItem_publicLaunch_title: "Public launch announcement",
    statusItem_publicLaunch_body: "BLOCKED — NO-GO until explicit founder decision.",
    roadmapTitle: "Roadmap",
    roadmapLead: "Product priorities — no deck dates or GA promises.",
    roadmap_r1: "Microsoft 365 calendar at scale when Graph is configured.",
    roadmap_r2: "More EU boards and employer ATS webhooks.",
    roadmap_r3: "Recruiter calendar sync and external integrations with honest disclosure.",
    roadmap_r4: "Resume auto-apply only after ops + product gates close.",
    risksTitle: "Risks & mitigations",
    risksLead: "Diligence transparency — no market guarantees.",
    risk_k1_title: "Public launch NO-GO",
    risk_k1_mitigation: "Controlled pilot, updated matrices, copy does not claim GA.",
    risk_k2_title: "Auto-apply paused",
    risk_k2_mitigation: "Server gates + candidate transparency copy; ops beat off on prod.",
    risk_k3_title: "Pre-revenue",
    risk_k3_mitigation: "Illustrative calculator; beta-labeled metrics; no invented MRR.",
    risk_k4_title: "Early recruiter cohort",
    risk_k4_mitigation: "H5c / H5d HOLD; no external invites without signed GO SMALL.",
    contactTitle: "Founder contact",
    contactLead: "Email with fund name and diligence checklist. We prefer concrete product and security questions.",
    contactCta: "Request deck",
    contactFaq: "Investor FAQ",
    contactWorkspace: "Investor workspace",
    contactMailSubject: "TWIN deck request — investor room",
    footerNote: "This page reflects product and gate reality — not fundraising commitments or launch promises.",
  },
};

export const INVESTOR_ROOM_OVERLAYS: Partial<Record<Locale, InvestorRoomOverlay>> = {
  es,
  it,
  fr,
  de,
  zh,
  ar,
  ja,
};
