/** Italian overlay: nav, common, home. */
export const itOverlay: Record<string, unknown> = {
  nav: {
    login: "Accedi",
    register: "Registrati",
    profile: "Profilo",
    dashboard: "Dashboard",
    calculator: "Calcolatore ROI B2B",
    menu: "Menu",
    ariaCompanyNav: "Navigazione aziendale",
    ariaAccountNav: "Navigazione account",
    ariaMobileNav: "Menu principale",
  },
  common: {
    language: "Lingua",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "Caricamento",
    loadingEllipsis: "Caricamento…",
    errorTitle: "Qualcosa è andato storto",
    errorBody: "Riprova. Se il problema persiste, aggiorna la pagina.",
    tryAgain: "Riprova",
  },
  meta: {
    titleHome: "TWIN — Agente di carriera",
    titleAbout: "Chi siamo — TWIN",
    titleCaseStudies: "Casi studio — TWIN",
    titleFaq: "FAQ — TWIN",
    titlePartners: "Partner — TWIN",
    titleMedia: "Media — TWIN",
    titleCareers: "Carriere — TWIN",
    titleContact: "Contatti — TWIN",
    titleCalculator: "Calcolatore ROI B2B — TWIN",
    titleLogin: "Accedi — TWIN",
    titleRegister: "Registrati — TWIN",
    titleProfile: "Profilo — TWIN",
    titleDashboard: "Dashboard — TWIN",
    titlePrivacy: "Privacy — TWIN",
    titleForgotPassword: "Password dimenticata — TWIN",
    titleResetPassword: "Nuova password — TWIN",
    titleOnboarding: "Tour del workspace — TWIN",
    titleBilling: "Piano e fatturazione — TWIN",
    titleAuthCallback: "Accesso — TWIN",
  },
  privacy: {
    title: "Informativa sulla privacy (MVP)",
    updated: "Ultimo aggiornamento: maggio 2026",
    collectTitle: "Cosa raccogliamo",
    collect1: "Email dell’account e password (hash)",
    collect2: "Profilo di carriera: competenze, esperienza, aspettative retributive, località",
    collect3: "Storico di candidature e match in TWIN",
    whyTitle: "Perché trattiamo i dati",
    whyBody:
      "Per abbinarti alle offerte di pracuj.pl e rocketjobs.pl e seguire lo stato delle candidature. Base giuridica: il tuo consenso esplicito alla registrazione (GDPR art. 6(1)(a)).",
    rightsTitle: "I tuoi diritti",
    rightsBody:
      "Puoi richiedere accesso, rettifica o cancellazione contattando il team TWIN. Puoi revocare il consenso eliminando l’account (funzione in un rilascio successivo).",
    retentionTitle: "Conservazione",
    retentionBody: "I dati sono conservati finché l’account è attivo e cancellati su richiesta.",
    thirdTitle: "Terze parti",
    thirdBody:
      "Usiamo Anthropic Claude per il matching. I dati sulle offerte provengono da annunci pubblici sui portali indicati.",
  },
  home: {
    tagline: "Piattaforma globale per la carriera, alimentata dall’IA",
    title: "Il tuo gemello di carriera IA lavora sul mercato 24 ore su 24",
    description:
      "TWIN è un agente di carriera autonomo per professionisti ovunque: aggrega ruoli dai job board e dalle regioni abilitate nel tuo workspace, li valuta rispetto al tuo profilo e tiene la pipeline in un unico posto — con auto-candidatura e pianificazione colloqui in roadmap.",
    getStarted: "Inizia gratis",
    logIn: "Accedi",
    scrape: "Scopri",
    scrapeDesc: "Board e regioni che configuri — espandibili mentre cresci",
    match: "Abbina",
    matchDesc: "Punteggi su competenze, seniority e obiettivi",
    track: "Traccia",
    trackDesc: "Un workspace per ricerca, salvataggi e candidature",
    featuresTitle: "Dal segnale alla pipeline",
    featuresSubtitle:
      "Un workspace calmo che rispecchia come pensi già al mercato — con automazione che arriva passo dopo passo.",
    footerHint: "Crea un profilo dopo la registrazione così l’abbinamento usa competenze, titoli e obiettivi.",
    twinForYourJob: "Gemello per il tuo ruolo",
    focusTitle: "Cosa dovrebbe prioritizzare TWIN per te per primo?",
    focusSubtitle:
      "Scegli cosa conta di più ora — dopo la registrazione atterri nella dashboard con profilo, feed e tracciamento collegati.",
    focusPickLabel: "Scegli un focus iniziale",
    focusChipDiscover: "Nuove offerte in un unico feed",
    focusChipMatch: "Match ordinati al mio profilo",
    focusChipTrack: "Salva e traccia candidature",
    focusChipAuto: "Auto-candidatura (in roadmap)",
    focusCta: "Inizia con questi obiettivi",
    focusFootnote:
      "L’MVP di oggi aggrega annunci, li valuta quando aggiungi un profilo e centralizza lo stato delle candidature. Automazione più pesante arriva a fasi — la stessa superficie calma, più autonomia dietro.",
    faqEyebrow: "FAQ",
    faqTitle: "Domande e risposte",
    faqPrivacyLink: "Informativa sulla privacy",
    faq01Q: "Cos’è TWIN oggi?",
    faq01A:
      "Un workspace di pipeline: annunci dai board abilitati, scoring opzionale sul profilo e un solo posto per salvataggi e candidature. Auto-candidatura profonda e pianificazione colloqui sono in roadmap.",
    faq02Q: "Per chi è?",
    faq02A:
      "Per chi già gestisce più siti di lavoro e note e vuole meno schede — un posto per scansionare, confrontare e far avanzare le candidature senza perdere contesto.",
    faq03Q: "In cosa differisce dall’usare un solo job board?",
    faq03A:
      "I board restano dove vivono gli annunci; TWIN è lo strato che normalizza scoperta, segnali di match e follow-up in un’unica UX. Dove serve, candidi ancora sul flusso del datore.",
    faq04Q: "E i miei dati?",
    faq04A:
      "Acconsenti esplicitamente alla registrazione. Usiamo i dati del profilo per ordinare i lavori e far funzionare il prodotto. Per conservazione, export e diritti GDPR, leggi la policy collegata sotto.",
  },
};
