/** Japanese overlay: nav, common, home. */
export const jaOverlay: Record<string, unknown> = {
  nav: {
    login: "ログイン",
    register: "登録",
    profile: "プロフィール",
    dashboard: "ダッシュボード",
    calculator: "B2B ROI 計算機",
    menu: "メニュー",
    ariaCompanyNav: "企業ナビゲーション",
    ariaAccountNav: "アカウントナビゲーション",
    ariaMobileNav: "メインメニュー",
  },
  common: {
    language: "言語",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "読み込み中",
    loadingEllipsis: "読み込み中…",
    errorTitle: "問題が発生しました",
    errorBody: "もう一度お試しください。解消しない場合はページを更新してください。",
    tryAgain: "再試行",
  },
  meta: {
    titleHome: "TWIN — キャリアエージェント",
    titleAbout: "会社概要 — TWIN",
    titleCaseStudies: "事例 — TWIN",
    titleFaq: "FAQ — TWIN",
    titlePartners: "パートナー — TWIN",
    titleMedia: "メディア — TWIN",
    titleCareers: "採用情報 — TWIN",
    titleContact: "お問い合わせ — TWIN",
    titleCalculator: "B2B ROI 計算機 — TWIN",
    titleLogin: "ログイン — TWIN",
    titleRegister: "登録 — TWIN",
    titleProfile: "プロフィール — TWIN",
    titleDashboard: "ダッシュボード — TWIN",
    titlePrivacy: "プライバシー — TWIN",
    titleForgotPassword: "パスワードを忘れた場合 — TWIN",
    titleResetPassword: "パスワードの再設定 — TWIN",
    titleOnboarding: "ワークスペースツアー — TWIN",
    titleBilling: "プランと請求 — TWIN",
    titleAuthCallback: "サインイン中 — TWIN",
  },
  privacy: {
    title: "プライバシーポリシー（MVP）",
    updated: "最終更新：2026年5月",
    collectTitle: "収集する情報",
    collect1: "アカウントのメールアドレスとパスワード（ハッシュ）",
    collect2: "キャリアプロフィール：スキル、経験、希望年収、所在地",
    collect3: "TWIN 上の応募とマッチングの履歴",
    whyTitle: "データを処理する理由",
    whyBody:
      "pracuj.pl と rocketjobs.pl の求人にマッチし、応募状況を追跡するためです。法的根拠：登録時の明示的な同意（GDPR 第6条1項(a)）。",
    rightsTitle: "あなたの権利",
    rightsBody:
      "TWIN チームに連絡してアクセス、訂正、削除を請求できます。アカウント削除で同意を撤回できます（機能は今後のリリースで提供）。",
    retentionTitle: "保管",
    retentionBody: "アカウントが有効な間データを保管し、依頼に応じて削除します。",
    thirdTitle: "第三者",
    thirdBody:
      "マッチングに Anthropic Claude を使用します。求人データは上記求人サイトの公開募集から取得します。",
  },
  home: {
    tagline: "AI が支えるグローバルなキャリアプラットフォーム",
    title: "あなたの AI キャリアツインが市場を24時間動かす",
    description:
      "TWIN は世界中のプロ向けの自律型キャリアエージェントです。ワークスペースで有効にした求人ボードと地域から求人を集約し、プロフィールに照らしてスコアリングし、パイプラインを一か所にまとめます。自動応募と面接調整はロードマップ上にあります。",
    getStarted: "無料で始める",
    logIn: "サインイン",
    scrape: "発見",
    scrapeDesc: "設定したボードと地域 — 成長に合わせて拡張可能",
    match: "マッチ",
    matchDesc: "スキル、シニアリティ、目標でスコア化",
    track: "追跡",
    trackDesc: "検索、保存、応募をひとつのワークスペースに",
    featuresTitle: "シグナルからパイプラインへ",
    featuresSubtitle:
      "市場の考え方を映す落ち着いたワークスペース — 自動化は段階的に届きます。",
    footerHint: "登録後にプロフィールを作成すると、スキル、職種、目標を使ったマッチングが可能になります。",
    twinForYourJob: "あなたの求人のためのツイン",
    focusTitle: "最初に TWIN に優先してほしいことは？",
    focusSubtitle:
      "今いちばん大事なことを選んでください — 登録後はプロフィール、フィード、追跡がつながったダッシュボードに入ります。",
    focusPickLabel: "最初のフォーカスを選ぶ",
    focusChipDiscover: "新着をひとつのフィードに",
    focusChipMatch: "プロフィールに沿ったランキング",
    focusChipTrack: "応募の保存と追跡",
    focusChipAuto: "自動応募（ロードマップ）",
    focusCta: "これらの目標で始める",
    focusFootnote:
      "現在の MVP は求人を集約し、プロフィール追加後にスコアし、応募状況を一元化します。より重い自動化は段階的に — 同じ落ち着いた画面の背後で自律性が増えます。",
    faqEyebrow: "FAQ",
    faqTitle: "よくある質問",
    faqPrivacyLink: "プライバシーポリシー",
    faq01Q: "今日の TWIN とは？",
    faq01A:
      "パイプラインのワークスペースです。有効なボードからの一覧、プロフィールに対する任意のスコアリング、保存と応募の単一の場所。より深い自動応募と面接調整はロードマップにあります。",
    faq02Q: "誰向け？",
    faq02A:
      "複数の求人サイトとメモを行き来していてタブを減らしたい人向け — 一覧、比較、応募の前進を文脈を失わずに行う場所です。",
    faq03Q: "単一の求人サイトと何が違う？",
    faq03A:
      "求人は各ボードにあります。TWIN は発見、マッチのシグナル、フォローアップをひとつの UX に正規化する層です。必要なら雇用側のフローで応募します。",
    faq04Q: "データはどうなる？",
    faq04A:
      "登録時に明示的に同意します。プロフィールデータは求人の並べ替えと製品運用に使います。保存、エクスポート、GDPR の権利は下のリンクのポリシーをご覧ください。",
  },
};
