/**
 * Below-hero homepage copy: live counter, social proof, rewards band, FAQ teaser.
 * Merged via marketing-home.ts — prevents EN leakage on `/` stats, quotes, outcome table.
 */
import type { Locale } from "../i18n";

type BelowFoldOverlay = {
  home: Record<string, string>;
  candidateRewards: Record<string, string>;
  faq: Record<string, string>;
};

const esRewards = {
  eyebrow: "Gana por resultados",
  headline: "Te pagamos por conseguir tu trabajo ideal — cuando esté verificado",
  lead:
    "Bonos por contrataciones, referidos y victorias en calendario — no por envíos masivos. La empresa paga success fee; tú recibes una parte definida tras verificación.",
  colTrigger: "Disparador",
  colReward: "Recompensa",
  colTiming: "Cuándo se paga",
  placementTitle: "Bono por placement",
  placementTrigger:
    "Contratación vía aplicación TWIN y placement verificado (checks asistidos — sin ping-pong por email)",
  placementReward:
    "{pct}% del primer salario bruto mensual — la empresa paga {feePct}% del salario mensual; la mitad vuelve a ti",
  placementTiming: "Tras placement verificado + reglas en condiciones (normalmente 30 días hábiles)",
  referralTitle: "Recomienda a un amigo",
  referralTrigger:
    "Tu amigo se registra con tu enlace, verifica email, completa perfil y consentimiento RGPD; el cash se desbloquea en su primera suscripción de pago",
  referralReward:
    "{firstPay} en el primer pago · {retained} tras 3 meses pagados · {hired} si consigue trabajo vía TWIN",
  referralTiming: "Seguimiento en panel; cash-out manual en demo (ver condiciones)",
  foundingTitle: "Mil fundadores",
  foundingTrigger: "Únete antes de que se llene el cupo — cuenta candidato verificada",
  foundingReward: "Precio fundador bloqueado (incl. ventana Premium gratis según condiciones de lanzamiento)",
  foundingTiming: "En activación de cuenta — sin placement requerido",
  interviewTitle: "Entrevista en tu calendario",
  interviewTrigger:
    "Slot confirmado por reclutador en tu calendario conectado (Google hoy; Outlook/ICS próximo)",
  interviewReward: "{amount} por slot confirmado — máx. {max} por trimestre (programa demo)",
  interviewTiming: "Tras verificar slot · límites trimestrales",
  mechanicsNote:
    "Economía alineada con modelo inversor: fee empresa 50% salario mensual → 25% neto para ti. Programa LinkedIn puede aumentar tu parte en hires elegibles.",
  disclaimer:
    "Condiciones demo — no ingreso garantizado. Pagos tras checks antifraude, identidad y condiciones vigentes. No disponible donde esté prohibido.",
  fraudLine: "Una cuenta por persona; auto-referidos y registros sintéticos anulan recompensas.",
  ctaReferrals: "Tu panel de referidos",
  ctaTerms: "Condiciones",
  ctaPrivacy: "Privacidad",
  ctaFounding: "Mil fundadores",
  ctaRegister: "Crear cuenta gratis",
};

const deRewards = {
  eyebrow: "Verdiene an Ergebnissen",
  headline: "Wir zahlen dir für deinen Traumjob — wenn verifiziert",
  lead:
    "Boni für Hires, Empfehlungen und Kalender-Erfolge — nicht für Massenbewerbungen. Arbeitgeber zahlt Success Fee; du erhältst definierten Anteil nach Verifikation.",
  colTrigger: "Auslöser",
  colReward: "Belohnung",
  colTiming: "Auszahlung",
  placementTitle: "Placement-Erfolgsbonus",
  placementTrigger:
    "Einstellung über TWIN-getrackte Bewerbung und Placement verified (maschinell unterstützt — kein E-Mail-Ping-Pong)",
  placementReward:
    "{pct}% deines ersten monatlichen Bruttogehalts — Arbeitgeber zahlt {feePct}% Monatsgehalt; die Hälfte geht an dich",
  placementTiming: "Nach Placement verified + Regeln in AGB (typisch innerhalb 30 Werktagen)",
  referralTitle: "Freund empfehlen",
  referralTrigger:
    "Freund registriert sich mit deinem Link, verifiziert E-Mail, vervollständigt Profil und DSGVO-Einwilligung; Auszahlung bei erster bezahlter Subscription",
  referralReward:
    "{firstPay} bei erster Zahlung · {retained} nach 3 bezahlten Monaten · {hired} bei Hire via TWIN",
  referralTiming: "Im Dashboard nachverfolgt; manueller Cash-out in Demo (AGB)",
  foundingTitle: "Gründer-Tausend",
  foundingTrigger: "Beitritt vor vollem Public-Cap — verifiziertes Kandidatenkonto",
  foundingReward: "Gründer-Preis gesperrt (inkl. kostenlosem Premium-Fenster laut Launch-Bedingungen)",
  foundingTiming: "Bei Kontoaktivierung — kein Placement nötig",
  interviewTitle: "Interview im Kalender",
  interviewTrigger:
    "Recruiter-bestätigter Slot landet in verbundenem Kalender (Google heute; Outlook/ICS als Nächstes)",
  interviewReward: "{amount} pro bestätigtem Slot — max. {max} pro Kalenderquartal (Demo-Programm)",
  interviewTiming: "Nach Slot-Verifikation · Limits quartalsweise",
  mechanicsNote:
    "Ökonomie wie Investorenmodell: Standard-Arbeitgebergebühr 50% Monatsgehalt → 25% netto für dich. LinkedIn-Programm kann Anteil bei qualifizierten Hires erhöhen.",
  disclaimer:
    "Demo-Programmbedingungen — kein garantiertes Einkommen. Auszahlungen nach Fraud-Checks, Identität und aktiven AGB. Nicht verfügbar, wo verboten.",
  fraudLine: "Ein Konto pro Person; Selbst-Empfehlungen und synthetische Anmeldungen annullieren Belohnungen.",
  ctaReferrals: "Dein Empfehlungs-Dashboard",
  ctaTerms: "AGB",
  ctaPrivacy: "Datenschutz",
  ctaFounding: "Gründer-Tausend",
  ctaRegister: "Kostenloses Konto erstellen",
};

const frRewards = {
  eyebrow: "Gagnez sur les résultats",
  headline: "Nous vous payons pour décrocher l'emploi idéal — une fois vérifié",
  lead:
    "Bonus pour embauches, parrainages et victoires calendrier — pas pour candidatures en masse. L'employeur paie des frais de placement ; vous recevez une part définie après vérification.",
  colTrigger: "Déclencheur",
  colReward: "Récompense",
  colTiming: "Paiement",
  placementTitle: "Bonus de placement",
  placementTrigger:
    "Embauche via candidature TWIN et placement vérifié (contrôles assistés — pas de ping-pong email)",
  placementReward:
    "{pct}% du premier salaire brut mensuel — l'employeur paie {feePct}% du salaire mensuel ; la moitié vous revient",
  placementTiming: "Après placement vérifié + règles dans les CGU (typiquement sous 30 jours ouvrés)",
  referralTitle: "Parrainer un ami",
  referralTrigger:
    "L'ami s'inscrit avec votre lien, vérifie l'email, complète le profil et le consentement RGPD ; paiement à sa première souscription payante",
  referralReward:
    "{firstPay} au premier paiement · {retained} après 3 mois payés · {hired} s'il est embauché via TWIN",
  referralTiming: "Suivi dans le tableau de bord ; retrait manuel en démo (CGU)",
  foundingTitle: "Mille fondateurs",
  foundingTrigger: "Rejoindre avant le plafond public — compte candidat vérifié",
  foundingReward: "Tarif fondateur verrouillé (incl. fenêtre Premium gratuite selon conditions de lancement)",
  foundingTiming: "À l'activation du compte — pas de placement requis",
  interviewTitle: "Entretien sur votre calendrier",
  interviewTrigger:
    "Créneau confirmé par le recruteur sur votre calendrier connecté (Google aujourd'hui ; Outlook/ICS ensuite)",
  interviewReward: "{amount} par créneau confirmé — max. {max} par trimestre (programme démo)",
  interviewTiming: "Après vérification du créneau · plafonds trimestriels",
  mechanicsNote:
    "Économie alignée sur le modèle investisseur : frais employeur 50% salaire mensuel → 25% net pour vous. Le programme LinkedIn peut augmenter votre part sur les embauches éligibles.",
  disclaimer:
    "Conditions programme démo — pas de revenu garanti. Paiements après contrôles fraude, identité et CGU actives. Indisponible où interdit.",
  fraudLine: "Un compte par personne ; auto-parrainages et inscriptions synthétiques annulent les récompenses.",
  ctaReferrals: "Votre tableau de bord parrainage",
  ctaTerms: "CGU",
  ctaPrivacy: "Confidentialité",
  ctaFounding: "Mille fondateurs",
  ctaRegister: "Créer un compte gratuit",
};

const itRewards = {
  eyebrow: "Guadagna sui risultati",
  headline: "Ti paghiamo per il lavoro ideale — quando è verificato",
  lead:
    "Bonus per assunzioni, referral e vittorie in calendario — non per candidature a raffica. L'azienda paga una success fee; ricevi una quota definita dopo la verifica.",
  colTrigger: "Condizione",
  colReward: "Ricompensa",
  colTiming: "Pagamento",
  placementTitle: "Bonus placement",
  placementTrigger:
    "Assunzione tramite candidatura TWIN e placement verificato (controlli assistiti — niente ping-pong email)",
  placementReward:
    "{pct}% del primo stipendio lordo mensile — l'azienda paga {feePct}% dello stipendio mensile; metà torna a te",
  placementTiming: "Dopo placement verificato + regole nei Termini (di solito entro 30 giorni lavorativi)",
  referralTitle: "Invita un amico",
  referralTrigger:
    "L'amico si registra con il tuo link, verifica email, completa profilo e consenso GDPR; pagamento alla prima sottoscrizione pagata",
  referralReward:
    "{firstPay} al primo pagamento · {retained} dopo 3 mesi pagati · {hired} se viene assunto via TWIN",
  referralTiming: "Tracciato in dashboard; cash-out manuale in demo (Termini)",
  foundingTitle: "Mille fondatori",
  foundingTrigger: "Iscrizione prima del cap pubblico — account candidato verificato",
  foundingReward: "Prezzo fondatore bloccato (incl. finestra Premium gratuita secondo termini di lancio)",
  foundingTiming: "All'attivazione account — nessun placement richiesto",
  interviewTitle: "Colloquio sul calendario",
  interviewTrigger:
    "Slot confermato dal recruiter sul calendario connesso (Google oggi; Outlook/ICS prossimamente)",
  interviewReward: "{amount} per slot confermato — max {max} per trimestre (programma demo)",
  interviewTiming: "Dopo verifica slot · limiti trimestrali",
  mechanicsNote:
    "Economia allineata al modello investitori: fee azienda 50% stipendio mensile → 25% netto per te. Il programma LinkedIn può aumentare la quota su hire idonei.",
  disclaimer:
    "Termini programma demo — non reddito garantito. Pagamenti dopo controlli frode, identità e Termini attivi. Non disponibile dove vietato.",
  fraudLine: "Un account a persona; auto-referral e iscrizioni sintetiche annullano le ricompense.",
  ctaReferrals: "La tua dashboard referral",
  ctaTerms: "Termini",
  ctaPrivacy: "Riservatezza",
  ctaFounding: "Mille fondatori",
  ctaRegister: "Crea account gratuito",
};

const zhRewards = {
  eyebrow: "按结果赚取",
  headline: "帮你拿到理想工作后我们付钱 — 经核实后",
  lead:
    "奖金奖励录用、推荐和日历成果 — 不是海投。雇主支付安置成功费；TWIN 核实录用后你获得约定份额。",
  colTrigger: "触发条件",
  colReward: "奖励",
  colTiming: "支付时间",
  placementTitle: "安置成功奖金",
  placementTrigger: "通过 TWIN 跟踪的申请录用且安置状态已核实（机器辅助核查 — 非邮件来回）",
  placementReward: "首月税前月薪的 {pct}% — 雇主支付月薪的 {feePct}%；其中一半返还给你",
  placementTiming: "安置核实后 + 条款中的支付规则（通常 30 个工作日内）",
  referralTitle: "推荐朋友",
  referralTrigger: "朋友用你的链接注册、验证邮箱、完善档案和 GDPR 同意；在其首次付费订阅时解锁现金",
  referralReward: "首次付款 {firstPay} · 连续付费 3 个月后 {retained} · 通过 TWIN 录用 {hired}",
  referralTiming: "在面板中跟踪；演示环境手动提现（见条款）",
  foundingTitle: "创始千人",
  foundingTrigger: "在公开上限满额前加入 — 已验证候选人账户",
  foundingReward: "锁定创始定价（含上线条款规定的免费 Premium 窗口）",
  foundingTiming: "账户激活时 — 无需安置",
  interviewTitle: "日历上的面试",
  interviewTrigger: "招聘方确认的面试时段写入已连接日历（当前 Google；即将 Outlook/ICS）",
  interviewReward: "每个确认时段 {amount} — 每季度最多 {max}（演示计划）",
  interviewTiming: "时段核实后 · 季度上限重置",
  mechanicsNote:
    "经济与投资者模型一致：默认雇主费为月薪 50% → 你净得 25%。LinkedIn 分享计划可能提高合格录用的份额。",
  disclaimer: "演示计划条款 — 非保证收入。支付需通过反欺诈、身份核查及有效条款。禁止地区不可用。",
  fraudLine: "每人一个账户；自推荐和虚假注册使奖励失效。",
  ctaReferrals: "你的推荐面板",
  ctaTerms: "条款",
  ctaPrivacy: "隐私",
  ctaFounding: "创始千人",
  ctaRegister: "创建免费账户",
};

const jaRewards = {
  eyebrow: "成果で稼ぐ",
  headline: "理想の仕事が決まったらお支払い — 検証後",
  lead:
    "採用・紹介・カレンダー成果へのボーナス — 乱発応募ではありません。雇用主がプレースメント成功料を支払い、TWIN が採用を検証した後、定められた割合を受け取ります。",
  colTrigger: "条件",
  colReward: "報酬",
  colTiming: "支払い",
  placementTitle: "プレースメント成功ボーナス",
  placementTrigger: "TWIN 経由の応募で採用され placement が verified（機械支援チェック — メール往復なし）",
  placementReward: "初月総支給の {pct}% — 雇用主は月給の {feePct}% を支払い、その半分があなたへ",
  placementTiming: "placement verified 後 + 規約の支払いルール（通常 30 営業日以内）",
  referralTitle: "友人を紹介",
  referralTrigger:
    "友人があなたのリンクで登録し、メール確認・プロフィール・GDPR 同意を完了；初回有料サブスクで現金解放",
  referralReward: "初回支払い {firstPay} · 3 か月継続 {retained} · TWIN 経由採用で {hired}",
  referralTiming: "ダッシュボードで追跡；デモでは手動出金（規約参照）",
  foundingTitle: "創設千人",
  foundingTrigger: "公開上限が埋まる前に参加 — 検証済み候補者アカウント",
  foundingReward: "創設価格をロック（ローンチ規約に基づく無料 Premium 期間を含む）",
  foundingTiming: "アカウント有効化時 — プレースメント不要",
  interviewTitle: "カレンダー上の面接",
  interviewTrigger: "採用担当が確認した面接枠が接続カレンダーに反映（現状 Google；Outlook/ICS 予定）",
  interviewReward: "確認枠あたり {amount} — 四半期最大 {max}（デモプログラム）",
  interviewTiming: "枠検証後 · 四半期上限リセット",
  mechanicsNote:
    "投資家モデルと同じ経済：標準雇用主手数料は月給 50% → あなたの純得 25%。LinkedIn プログラムで対象採用の割合が上がる場合あり。",
  disclaimer: "デモプログラム規約 — 収入保証なし。不正・本人確認・有効規約後に支払い。禁止地域では利用不可。",
  fraudLine: "1 人 1 アカウント；自己紹介と合成登録は報酬無効。",
  ctaReferrals: "紹介ダッシュボード",
  ctaTerms: "規約",
  ctaPrivacy: "プライバシー",
  ctaFounding: "創設千人",
  ctaRegister: "無料アカウント作成",
};

const arRewards = {
  eyebrow: "اكسب على النتائج",
  headline: "ندفع لك عند الحصول على وظيفتك المثالية — بعد التحقق",
  lead:
    "مكافآت للتوظيف والإحالات وانتصارات التقويم — وليس للتقديم العشوائي. صاحب العمل يدفع رسوم نجاح التوظيف؛ تحصل على حصة محددة بعد تحقق TWIN.",
  colTrigger: "المحفّز",
  colReward: "المكافأة",
  colTiming: "موعد الدفع",
  placementTitle: "مكافأة نجاح التوظيف",
  placementTrigger: "توظيف عبر طلب متتبع في TWIN وحالة placement verified (فحوصات آلية — لا مراسلة بريدية)",
  placementReward: "{pct}% من أول راتب شهري إجمالي — صاحب العمل يدفع {feePct}% من الراتب الشهري؛ نصف الرسوم يعود إليك",
  placementTiming: "بعد placement verified + قواعد الدفع في الشروط (عادة خلال 30 يوم عمل)",
  referralTitle: "أحِل صديقاً",
  referralTrigger:
    "يسجل صديقك برابطك، يتحقق من البريد، يكمل الملف والموافقة GDPR؛ الدفع عند أول اشتراك مدفوع",
  referralReward: "{firstPay} عند أول دفعة · {retained} بعد 3 أشهر مدفوعة · {hired} إذا توظف عبر TWIN",
  referralTiming: "تتبع في لوحة التحكم؛ سحب يدوي في العرض التجريبي (انظر الشروط)",
  foundingTitle: "ألف مؤسس",
  foundingTrigger: "انضم قبل امتلاء السقف العام — حساب مرشح موثّق",
  foundingReward: "تسعير مؤسسين مقفل (يشمل نافذة Premium مجانية حسب شروط الإطلاق)",
  foundingTiming: "عند تفعيل الحساب — لا يلزم placement",
  interviewTitle: "مقابلة في تقويمك",
  interviewTrigger: "موعد مؤكد من المُوظّف يصل إلى تقويمك المتصل (Google اليوم؛ Outlook/ICS قريباً)",
  interviewReward: "{amount} لكل موعد مؤكد — حد أقصى {max} لكل ربع سنة (برنامج تجريبي)",
  interviewTiming: "بعد التحقق من الموعد · حدود ربع سنوية",
  mechanicsNote:
    "اقتصاد مطابق لنموذج المستثمرين: رسوم صاحب العمل 50% من الراتب الشهري → 25% صافي لك. برنامج LinkedIn قد يزيد حصتك في التوظيفات المؤهلة.",
  disclaimer: "شروط البرنامج التجريبي — ليس دخلاً مضموناً. الدفع بعد فحوصات الاحتيال والهوية والشروط السارية. غير متاح حيث يُحظر.",
  fraudLine: "حساب واحد لكل شخص؛ الإحالات الذاتية والتسجيلات الاصطناعية تلغي المكافآت.",
  ctaReferrals: "لوحة الإحالات",
  ctaTerms: "الشروط",
  ctaPrivacy: "الخصوصية",
  ctaFounding: "ألف مؤسس",
  ctaRegister: "إنشاء حساب مجاني",
};

const esFaq = {
  homeTeaserLead:
    "{count} respuestas en general, candidatos, reclutadores, empresas e inversores — abre el FAQ completo con pestañas por persona.",
  homeCta: "Ver las {count} respuestas",
  homeCtaHint: "Pestañas por persona en la página FAQ completa",
  sectionGeneral: "Temas generales",
  sectionCandidates: "Candidatos",
  sectionRecruiters: "Reclutadores",
  sectionCompanies: "Empresas",
  sectionInvestors: "Inversores",
  general01Q: "¿Qué es TWIN hoy?",
  general01A:
    "Un agente de carrera que reduce el caos de pestañas: descubrimiento agregado, ranking consciente del perfil, seguimiento de candidaturas y automatización por fases (solo preparación en producción hoy). La estrella del norte: un calendario corto de momentos listos para aceptar — no más spam.",
  general02Q: "¿Para quién es TWIN?",
  general02A:
    "Cuatro carriles en una plataforma: candidatos, reclutadores, empresas e inversores. Elige el carril al registrarte — SKU y facturación difieren por persona.",
  general03Q: "¿En qué se diferencia de un solo portal?",
  general03A:
    "Los portales alojan las ofertas; TWIN normaliza descubrimiento, señales de encaje y seguimiento en una UX. Sigues los flujos del empleador cuando el portal lo exige.",
};

const deFaq = {
  homeTeaserLead:
    "{count} Antworten zu Allgemein, Kandidaten, Recruiter, Unternehmen und Investoren — vollständiges FAQ mit Persona-Tabs öffnen.",
  homeCta: "Alle {count} Antworten ansehen",
  homeCtaHint: "Persona-Tabs auf der vollständigen FAQ-Seite",
  sectionGeneral: "Allgemein",
  sectionCandidates: "Kandidaten",
  sectionRecruiters: "Recruiter",
  sectionCompanies: "Unternehmen",
  sectionInvestors: "Investoren",
  general01Q: "Was ist TWIN heute?",
  general01A:
    "Ein Karriereagent, der Tab-Chaos reduziert: aggregierte Jobsuche, profilbewusstes Ranking, Bewerbungs-Tracking und frühe phasenweise Automatisierung (heute nur Vorbereitung in Produktion). North Star: kurzer Kalender akzeptanzbereiter Momente — kein Inbox-Spam.",
  general02Q: "Für wen ist TWIN?",
  general02A:
    "Vier Lanes auf einer Plattform: Kandidaten, Recruiter, Unternehmen, Investoren. Wähle die Lane bei der Anmeldung — SKUs und Billing unterscheiden sich.",
  general03Q: "Worin unterscheidet sich das von einer Jobbörse?",
  general03A:
    "Börsen hosten Stellen; TWIN normalisiert Entdeckung, Match-Signale und Tracking in einer UX. Employer-Flows bleiben, wenn die Börse es verlangt.",
};

const frFaq = {
  homeTeaserLead:
    "{count} réponses — général, candidats, recruteurs, entreprises, investisseurs — ouvrez la FAQ complète avec onglets par persona.",
  homeCta: "Voir les {count} réponses",
  homeCtaHint: "Onglets persona sur la page FAQ complète",
  sectionGeneral: "Général",
  sectionCandidates: "Candidats",
  sectionRecruiters: "Recruteurs",
  sectionCompanies: "Entreprises",
  sectionInvestors: "Investisseurs",
  general01Q: "Qu'est-ce que TWIN aujourd'hui ?",
  general01A:
    "Un agent de carrière qui réduit le chaos d'onglets : découverte agrégée, classement profil-aware, suivi des candidatures et automatisation par phases (préparation seule en production aujourd'hui). North Star : un calendrier court de moments prêts à accepter — pas de spam.",
  general02Q: "Pour qui est TWIN ?",
  general02A:
    "Quatre voies sur une plateforme : candidats, recruteurs, entreprises, investisseurs. Choisissez la voie à l'inscription — SKU et facturation diffèrent.",
  general03Q: "En quoi diffère-t-il d'un seul job board ?",
  general03A:
    "Les boards hébergent les offres ; TWIN normalise découverte, signaux de match et suivi dans une UX. Vous suivez les flux employeur quand le board l'exige.",
};

const itFaq = {
  homeTeaserLead:
    "{count} risposte su generale, candidati, recruiter, aziende e investitori — apri la FAQ completa con schede per persona.",
  homeCta: "Vedi tutte le {count} risposte",
  homeCtaHint: "Schede persona nella pagina FAQ completa",
  sectionGeneral: "Generale",
  sectionCandidates: "Candidati",
  sectionRecruiters: "Recruiter",
  sectionCompanies: "Aziende",
  sectionInvestors: "Investitori",
  general01Q: "Cos'è TWIN oggi?",
  general01A:
    "Un agente di carriera che riduce il caos di schede: scoperta aggregata, ranking profil-aware, tracking candidature e automazione a fasi (solo preparazione in produzione oggi). North Star: un calendario corto di momenti pronti all'accettazione — non spam.",
  general02Q: "Per chi è TWIN?",
  general02A:
    "Quattro corsie su una piattaforma: candidati, recruiter, aziende, investitori. Scegli la corsia alla registrazione — SKU e fatturazione differiscono.",
  general03Q: "In cosa differisce da un solo portale?",
  general03A:
    "I portali ospitano le offerte; TWIN normalizza scoperta, segnali di match e tracking in una UX. Segui i flussi employer quando il portale lo richiede.",
};

const zhFaq = {
  homeTeaserLead: "{count} 个答案涵盖通用、候选人、招聘方、企业与投资者 — 打开完整 FAQ 并按角色浏览。",
  homeCta: "查看全部 {count} 个答案",
  homeCtaHint: "完整 FAQ 页面的角色标签",
  sectionGeneral: "通用",
  sectionCandidates: "候选人",
  sectionRecruiters: "招聘方",
  sectionCompanies: "企业",
  sectionInvestors: "投资者",
  general01Q: "TWIN 今天是什么？",
  general01A:
    "减少标签混乱的职业代理：聚合发现、档案感知排序、申请跟踪与分阶段自动化（生产环境目前仅准备）。北极星：简短的待接受时刻日历 — 而非垃圾邮件。",
  general02Q: "TWIN 面向谁？",
  general02A: "一个平台上的四条赛道：候选人、招聘方、企业、投资者。注册时选择赛道 — SKU 与计费因角色而异。",
  general03Q: "与单一招聘板有何不同？",
  general03A: "招聘板托管职位；TWIN 在统一体验中规范化发现、匹配信号与跟踪。招聘板要求时仍遵循雇主流程。",
};

const jaFaq = {
  homeTeaserLead:
    "{count} 件の回答 — 一般、候補者、リクルーター、企業、投資家 — ペルソナ別タブの完全 FAQ を開く。",
  homeCta: "全 {count} 件の回答を見る",
  homeCtaHint: "完全 FAQ ページのペルソナタブ",
  sectionGeneral: "一般",
  sectionCandidates: "候補者",
  sectionRecruiters: "リクルーター",
  sectionCompanies: "企業",
  sectionInvestors: "投資家",
  general01Q: "TWIN は今日何ですか？",
  general01A:
    "タブの混沌を減らすキャリアエージェント：集約ディスカバリー、プロフィール連動ランキング、応募追跡、段階的オートメーション（本番は今日は準備のみ）。North Star：受け入れ準備の短いカレンダー — スパムではない。",
  general02Q: "TWIN は誰向け？",
  general02A: "1 プラットフォームに 4 レーン：候補者、リクルーター、企業、投資家。登録時にレーンを選択 — SKU と課金は異なる。",
  general03Q: "単一求人ボードとの違いは？",
  general03A: "ボードは求人をホスト；TWIN は発見・マッチシグナル・追跡を 1 UX に正規化。ボードが求めるときは雇用主フローに従う。",
};

const arFaq = {
  homeTeaserLead:
    "{count} إجابات — عام، مرشحون، مُوظّفون، شركات، مستثمرون — افتح الأسئلة الشائعة الكاملة بعلامات تبويب لكل دور.",
  homeCta: "عرض كل {count} إجابة",
  homeCtaHint: "علامات تبويب الأدوار في صفحة الأسئلة الشائعة الكاملة",
  sectionGeneral: "عام",
  sectionCandidates: "المرشحون",
  sectionRecruiters: "المُوظّفون",
  sectionCompanies: "الشركات",
  sectionInvestors: "المستثمرون",
  general01Q: "ما هو TWIN اليوم؟",
  general01A:
    "وكيل مهني يقلل فوضى التبويبات: اكتشاف مجمّع، ترتيب واعٍ بالملف، تتبع الطلبات وأتمتة على مراحل (التحضير فقط في الإنتاج اليوم). North Star: تقويم قصير للحظات الجاهزة للقبول — لا بريد عشوائي.",
  general02Q: "لمن TWIN؟",
  general02A: "أربعة مسارات على منصة واحدة: مرشحون، مُوظّفون، شركات، مستثمرون. اختر المسار عند التسجيل — SKU والفوترة تختلف.",
  general03Q: "كيف يختلف عن لوحة وظائف واحدة؟",
  general03A: "اللوحات تستضيف الوظائف؛ TWIN يوحّد الاكتشاف وإشارات التطابق والتتبع في تجربة واحدة. تتبع تدفقات صاحب العمل عندما تتطلب اللوحة ذلك.",
};

const sharedHomeBelowFold = {
  es: {
    liveCounter: "{count}+ roles escaneados en portales activados",
    liveCounterUnavailable: "—",
    socialProofJoin:
      "Únete a candidatos que construyen un calendario de aceptación — no otro cementerio de pestañas.",
    socialProofQuote: "«Por fin un pipeline en lugar de veinte pestañas.»",
    faqEyebrow: "Preguntas frecuentes",
    faqTitle: "Preguntas y respuestas",
    faqPrivacyLink: "Política de privacidad",
    teaserCard1Title: "Staff engineer · plataforma",
    teaserCard1Meta: "Remoto UE · 92% coincidencia",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "Híbrido · 88% coincidencia",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "Varsovia · 85% coincidencia",
  },
  de: {
    liveCounter: "{count}+ Rollen auf aktivierten Börsen gescannt",
    liveCounterUnavailable: "—",
    socialProofJoin:
      "Schließe dich Kandidat:innen an, die einen Akzeptanz-Kalender bauen — kein weiteres Tab-Friedhof.",
    socialProofQuote: "„Endlich ein Pipeline statt zwanzig Tabs.“",
    faqEyebrow: "Häufige Fragen",
    faqTitle: "Fragen & Antworten",
    faqPrivacyLink: "Datenschutz",
    teaserCard1Title: "Staff Engineer · Plattform",
    teaserCard1Meta: "Remote EU · 92 % Match",
    teaserCard2Title: "Product Lead · B2B SaaS",
    teaserCard2Meta: "Hybrid · 88 % Match",
    teaserCard3Title: "Engineering Manager",
    teaserCard3Meta: "Warschau · 85 % Match",
  },
  fr: {
    liveCounter: "{count}+ rôles scannés sur les sites activés",
    liveCounterUnavailable: "—",
    socialProofJoin:
      "Rejoignez des candidats qui construisent un calendrier d'acceptation — pas un autre cimetière d'onglets.",
    socialProofQuote: "« Enfin un pipeline au lieu de vingt onglets. »",
    faqEyebrow: "Questions fréquentes",
    faqTitle: "Questions & réponses",
    faqPrivacyLink: "Confidentialité",
    teaserTitle: "Votre fil de matchs et pipeline — aperçu",
    teaserUnlock: "Débloquer après inscription",
    teaserCard1Title: "Staff engineer · plateforme",
    teaserCard1Meta: "Remote UE · 92 % match",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "Hybride · 88 % match",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "Varsovie · 85 % match",
  },
  it: {
    liveCounter: "{count}+ ruoli scansionati sui portali attivi",
    liveCounterUnavailable: "—",
    socialProofJoin:
      "Unisciti a candidati che costruiscono un calendario di accettazione — non un altro cimitero di schede.",
    socialProofQuote: "«Finalmente un pipeline invece di venti schede.»",
    faqEyebrow: "Domande frequenti",
    faqTitle: "Domande & risposte",
    faqPrivacyLink: "Privacy",
    teaserTitle: "Il tuo feed di match e pipeline — anteprima",
    teaserUnlock: "Sblocca dopo la registrazione",
    teaserCard1Title: "Staff engineer · piattaforma",
    teaserCard1Meta: "Remote EU · 92% match",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "Ibrido · 88% match",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "Varsavia · 85% match",
    statsAria: "Attività della piattaforma",
    statJobs: "Offerte validate",
    statUsers: "Membri",
    statApps: "Candidature",
    statBoards: "Portali nel registro",
    scrape: "Scopri",
    scrapeDesc: "Aggrega annunci dai portali attivati.",
    match: "Abbina",
    matchDesc: "Punteggi su profilo, competenze e obiettivi.",
    track: "Traccia",
    trackDesc: "Ricerca, salvataggi e stati in un workspace.",
    featuresTitle: "Pipeline a colpo d'occhio",
    featuresSubtitle: "Anteprima live: scopri → abbina → traccia.",
    howStep1Title: "Connetti",
    howStep1Line: "Attiva job board e regioni che contano per te.",
    howStep2Title: "Abbina",
    howStep2Line: "Ruoli valutati sul profilo all'arrivo degli annunci.",
    howStep3Title: "Traccia",
    howStep3Line: "Ogni salvataggio e stato in un cockpit.",
    howStep4Title: "Automatizza",
    howStep4Line: "Auto-apply e sync calendario arrivano per fasi pubbliche.",
    feature1Title: "Feed unificato",
    feature1Line: "Basta screenshot su più siti.",
    feature2Title: "Ranking profil-aware",
    feature2Line: "Punteggi che rispettano seniority e skill.",
    feature3Title: "Intelligenza CV",
    feature3Line: "Affina il segnale prima di candidarti.",
    feature4Title: "Registro candidature",
    feature4Line: "Una timeline per ogni cambio di stato.",
    feature5Title: "Consenso & GDPR",
    feature5Line: "Opt-in esplicito; export quando servono.",
  },
  zh: {
    liveCounter: "已在启用的招聘板上扫描 {count}+ 个职位",
    liveCounterUnavailable: "—",
    socialProofJoin: "加入正在构建接受日历的候选人 — 而不是又一个标签坟场。",
    socialProofQuote: "「终于是一个管道，而不是二十个标签。」",
    faqEyebrow: "常见问题",
    faqTitle: "常见问题",
    faqPrivacyLink: "隐私政策",
    teaserTitle: "你的匹配信息流与管道 — 预览",
    teaserUnlock: "注册后解锁",
    teaserCard1Title: "Staff engineer · 平台",
    teaserCard1Meta: "远程 EU · 92% 匹配",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "混合 · 88% 匹配",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "华沙 · 85% 匹配",
    statsAria: "平台活动",
    statJobs: "已验证职位",
    statUsers: "成员",
    statApps: "申请",
    statBoards: "注册招聘板",
    scrape: "发现",
    scrapeDesc: "聚合你启用的招聘板职位。",
    match: "匹配",
    matchDesc: "按档案、技能与目标评分。",
    track: "跟踪",
    trackDesc: "搜索、收藏与状态在同一工作区。",
    featuresTitle: "管道一览",
    featuresSubtitle: "实时预览：发现 → 匹配 → 跟踪。",
    howStep1Title: "连接",
    howStep1Line: "启用你关心的招聘板与地区。",
    howStep2Title: "匹配",
    howStep2Line: "新职位按档案评分。",
    howStep3Title: "跟踪",
    howStep3Line: "每次保存与申请状态在一个驾驶舱。",
    howStep4Title: "自动化",
    howStep4Line: "自动投递与日历同步将分阶段上线。",
    feature1Title: "统一信息流",
    feature1Line: "不再在多个网站截图。",
    feature2Title: "档案感知排序",
    feature2Line: "尊重资历与技能的评分。",
    feature3Title: "简历智能",
    feature3Line: "投递前优化信号。",
    feature4Title: "申请台账",
    feature4Line: "每次状态变更一条时间线。",
    feature5Title: "同意与 GDPR",
    feature5Line: "明确选择加入；需要时可导出。",
  },
  ja: {
    liveCounter: "有効なボードで {count}+ 件のロールをスキャン",
    liveCounterUnavailable: "—",
    socialProofJoin: "受け入れカレンダーを築く候補者に参加 — またのタブの墓場ではなく。",
    socialProofQuote: "「二十のタブではなく、ひとつのパイプライン。」",
    faqEyebrow: "よくある質問",
    faqTitle: "よくある質問",
    faqPrivacyLink: "プライバシー",
    teaserTitle: "マッチフィードとパイプライン — プレビュー",
    teaserUnlock: "登録後にアンロック",
    teaserCard1Title: "Staff engineer · プラットフォーム",
    teaserCard1Meta: "リモート EU · 92% マッチ",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "ハイブリッド · 88% マッチ",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "ワルシャワ · 85% マッチ",
    statsAria: "プラットフォーム活動",
    statJobs: "検証済み求人",
    statUsers: "メンバー",
    statApps: "応募",
    statBoards: "登録ボード",
    scrape: "発見",
    scrapeDesc: "有効化したボードの求人を集約。",
    match: "マッチ",
    matchDesc: "プロフィール・スキル・目標でスコア。",
    track: "追跡",
    trackDesc: "検索・保存・ステータスを1ワークスペースに。",
    featuresTitle: "パイプライン概要",
    featuresSubtitle: "ライブプレビュー：発見 → マッチ → 追跡。",
    howStep1Title: "接続",
    howStep1Line: "重要なボードと地域を有効化。",
    howStep2Title: "マッチ",
    howStep2Line: "新着求人をプロフィールにスコア。",
    howStep3Title: "追跡",
    howStep3Line: "保存と応募ステータスを1コックピットに。",
    howStep4Title: "自動化",
    howStep4Line: "自動応募とカレンダー同期は公開フェーズで。",
    feature1Title: "統一フィード",
    feature1Line: "複数サイトのスクショは不要。",
    feature2Title: "プロフィール連動ランキング",
    feature2Line: "シニアリティとスキルを尊重するスコア。",
    feature3Title: "CVインテリジェンス",
    feature3Line: "応募前にシグナルを磨く。",
    feature4Title: "応募台帳",
    feature4Line: "ステータス変更ごとに1本のタイムライン。",
    feature5Title: "同意とGDPR",
    feature5Line: "明示的オプトイン；必要時にエクスポート。",
  },
  ar: {
    liveCounter: "تم فحص {count}+ دور على اللوحات المفعّلة",
    liveCounterUnavailable: "—",
    socialProofJoin: "انضم إلى مرشحين يبنون تقويم قبول — لا مقبرة تبويبات أخرى.",
    socialProofQuote: "«أخيراً خط أنابيب واحد بدلاً من عشرين تبويباً.»",
    faqEyebrow: "الأسئلة الشائعة",
    faqTitle: "الأسئلة الشائعة",
    faqPrivacyLink: "سياسة الخصوصية",
    teaserTitle: "خلاصة التطابق والمسار — معاينة",
    teaserUnlock: "افتح بعد التسجيل",
    teaserCard1Title: "Staff engineer · منصة",
    teaserCard1Meta: "عن بُعد EU · 92% تطابق",
    teaserCard2Title: "Product lead · B2B SaaS",
    teaserCard2Meta: "هجين · 88% تطابق",
    teaserCard3Title: "Engineering manager",
    teaserCard3Meta: "وارسو · 85% تطابق",
    statsAria: "نشاط المنصة",
    statJobs: "وظائف مُحققة",
    statUsers: "أعضاء",
    statApps: "طلبات",
    statBoards: "لوحات في السجل",
    scrape: "اكتشف",
    scrapeDesc: "اجمع الإعلانات من اللوحات المفعّلة.",
    match: "طابق",
    matchDesc: "درجات حسب الملف والمهارات والأهداف.",
    track: "تتبع",
    trackDesc: "بحث وحفظ وحالات في مساحة واحدة.",
    featuresTitle: "نظرة على المسار",
    featuresSubtitle: "معاينة مباشرة: اكتشف → طابق → تتبع.",
    howStep1Title: "اتصل",
    howStep1Line: "فعّل اللوحات والمناطق المهمة لك.",
    howStep2Title: "طابق",
    howStep2Line: "أدوار تُقيَّم لملفك عند وصول الإعلانات.",
    howStep3Title: "تتبع",
    howStep3Line: "كل حفظ وحالة طلب في قمرة واحدة.",
    howStep4Title: "أتمت",
    howStep4Line: "التقديم التلقائي ومزامنة التقويم تأتي على مراحل عامة.",
    feature1Title: "خلاصة موحدة",
    feature1Line: "توقف عن لقطات الشاشة عبر المواقع.",
    feature2Title: "ترتيب واعٍ بالملف",
    feature2Line: "درجات تحترم الأقدمية والمهارات.",
    feature3Title: "ذكاء السيرة",
    feature3Line: "اضبط الإشارة قبل التقديم.",
    feature4Title: "سجل الطلبات",
    feature4Line: "جدول زمني لكل تغيير حالة.",
    feature5Title: "الموافقة وGDPR",
    feature5Line: "اشتراك صريح؛ تصدير عند الحاجة.",
  },
};

/** Below-fold overlay chunks keyed by locale — spread into marketing-home overlays. */
export const MARKETING_HOME_BELOW_FOLD: Partial<Record<Locale, BelowFoldOverlay>> = {
  es: {
    home: sharedHomeBelowFold.es,
    candidateRewards: esRewards,
    faq: esFaq,
  },
  de: {
    home: sharedHomeBelowFold.de,
    candidateRewards: deRewards,
    faq: deFaq,
  },
  fr: {
    home: sharedHomeBelowFold.fr,
    candidateRewards: frRewards,
    faq: frFaq,
  },
  it: {
    home: sharedHomeBelowFold.it,
    candidateRewards: itRewards,
    faq: itFaq,
  },
  zh: {
    home: sharedHomeBelowFold.zh,
    candidateRewards: zhRewards,
    faq: zhFaq,
  },
  ja: {
    home: sharedHomeBelowFold.ja,
    candidateRewards: jaRewards,
    faq: jaFaq,
  },
  ar: {
    home: sharedHomeBelowFold.ar,
    candidateRewards: arRewards,
    faq: arFaq,
  },
};
