/**
 * Homepage / marketing hero copy for non-EN/PL locales.
 * Merged at dictionary build — prevents English leakage on `/` CTAs and inside steps.
 */
import type { Locale } from "../i18n";
import { MARKETING_HOME_BELOW_FOLD } from "./marketing-home-below-fold";
import { mergeDeep } from "../merge-messages";

type MarketingHomeOverlay = Record<string, unknown>;

const es: MarketingHomeOverlay = {
  home: {
    tagline: "Gemelo de carrera con IA",
    curiosityEyebrow: "Mira qué hay dentro",
    title: "Vuelve a entrevistas que valen la pena — no al spam del buzón.",
    heroHook:
      "La lista fundadora reserva beneficios de acceso anticipado para los primeros 1.000 — aplican condiciones fundadoras, uso razonable y Términos de lanzamiento (ver /first-1000). O abre una cuenta gratuita para ver coincidencias hoy.",
    description:
      "TWIN escanea los portales que activas y muestra roles que merecen tu tiempo: tras ausentarte abres una lista corta de huecos, no ruido aleatorio.",
    getStarted: "Crear cuenta gratis",
    ctaRegisterMicro: "Ve tus coincidencias en ~2 min",
    ctaDemoSecondary: "Ver demo interactiva",
    ctaDemoCardSubtitle: "Recorrido interactivo de 8 pasos · sin cuenta",
    ctaDemoCardLead: "Cómo encajan ranking, feedback y calendario",
    logInPrompt: "¿Ya tienes cuenta?",
    socialProofEyebrow: "Candidatos exploran roles en empresas como",
    teaserEyebrow: "Dentro de tu espacio de trabajo",
    teaserTitle: "Tu feed de coincidencias y pipeline — vista previa",
    teaserUnlock: "Desbloquear tras registrarte",
    insideEyebrow: "Qué obtienes dentro",
    insideTitle:
      "Tu pipeline puede trabajar mientras duermes — cuando la automatización que activas esté disponible",
    insideStep1Title: "Feed clasificado",
    insideStep1Line: "Roles puntuados según tu perfil — no un chorro de cada anuncio.",
    insideStep2Title: "Registro de candidaturas",
    insideStep2Line: "Cada guardado y estado en una línea de tiempo en la que los reclutadores confían.",
    insideStep3Title: "Calendario de entrevistas",
    insideStep3Line: "Huecos que merecen asistir, sincronizados al conectar el calendario.",
    stickyCtaLabel: "Únete a la lista fundadora",
    stickyCtaMicro: "Acceso anticipado fundador · solo email · aplican Términos",
    joinWishlist: "Únete a la lista fundadora",
    joinWishlistMicro: "Primeros 1.000 · beneficios de cohorte fundadora · sin tarjeta · aplican Términos",
    foundingCounterAria: "Plazas restantes en la lista fundadora",
    foundingCounterEyebrow: "Plazas fundadoras restantes",
    foundingCounterOf: "de {cap}",
    foundingCounterLoading: "Cargando contador en vivo…",
    foundingCounterLive: "Datos de lista en vivo",
    foundingCounterOffline: "Contador retrasado — el registro en la siguiente página sigue funcionando.",
    ctaBandWishlistEyebrow: "Mil fundadores",
    ctaBandWishlistTitle:
      "Reserva acceso anticipado fundador antes del precio público — beneficios sujetos a Términos.",
    ctaBandWishlistMicro:
      "Misma oferta fundadora que /first-1000 y la lista — primero el email; aplican condiciones fundadoras y uso razonable.",
    logIn: "Iniciar sesión",
    scrape: "Descubrir",
    scrapeDesc: "Agrega anuncios de los portales que activas.",
    match: "Emparejar",
    matchDesc: "Puntuación según perfil, habilidades y objetivos.",
    track: "Seguimiento",
    trackDesc: "Búsqueda, guardados y estados en un solo espacio.",
    featuresTitle: "Pipeline de un vistazo",
    featuresSubtitle: "Vista previa en vivo de descubrir → emparejar → seguir.",
    footerHint: "Añade un perfil tras registrarte para que el ranking tenga señal real.",
    howEyebrow: "Cómo funciona",
    howTitle: "Cuatro pasos hacia una búsqueda más tranquila",
    howDetailLink: "Recorrido completo",
    howStep1Title: "Conectar",
    howStep1Line: "Activa portales y regiones que te importan.",
    howStep2Title: "Emparejar",
    howStep2Line: "Roles puntuados según tu perfil cuando llegan anuncios.",
    howStep3Title: "Seguir",
    howStep3Line: "Cada guardado y estado de candidatura en una sola cabina.",
    howStep4Title: "Automatizar",
    howStep4Line: "Autoaplicación y sincronización de calendario llegan por fases públicas.",
    statsAria: "Actividad de la plataforma",
    statJobs: "Empleos validados",
    statUsers: "Miembros",
    statApps: "Candidaturas",
    statBoards: "Portales en el registro",
    featureGridTitle: "Hecho para el impulso, no el caos de pestañas",
    feature1Title: "Feed unificado",
    feature1Line: "Deja de capturar roles en varios sitios.",
    feature2Title: "Ranking consciente del perfil",
    feature2Line: "Puntuaciones que respetan seniority y habilidades.",
    feature3Title: "Inteligencia de CV",
    feature3Line: "Ajusta la señal antes de aplicar.",
    feature4Title: "Registro de candidaturas",
    feature4Line: "Una línea de tiempo para cada cambio de estado.",
    feature5Title: "Consentimiento y RGPD",
    feature5Line: "Opt-in explícito; exportaciones cuando las necesites.",
    feature6Title: "Automatización por fases (en pausa hoy)",
    feature6Line:
      "Prepara paquetes de candidatura para revisión — la autoaplicación sigue en pausa en producción hasta que las condiciones lo permitan.",
  },
};

const de: MarketingHomeOverlay = {
  home: {
    tagline: "KI-Karrierezwilling",
    curiosityEyebrow: "Sieh dir an, was drin ist",
    title: "Kehre zu Interviews zurück, die sich lohnen — nicht zum Postfach-Spam.",
    heroHook:
      "Die Gründerliste reserviert Frühzugangsvorteile für die ersten 1.000 — Gründerbedingungen, Fair-Use und Start-AGB gelten (siehe /first-1000). Oder öffne ein kostenloses Konto für Matches heute.",
    description:
      "TWIN durchsucht die von dir aktivierten Jobbörsen und zeigt Rollen, die deine Zeit wert sind — nach der Pause öffnest du eine kurze Slot-Liste, kein Zufallsrauschen.",
    getStarted: "Kostenloses Konto erstellen",
    ctaRegisterMicro: "Deine Matches in ~2 Min.",
    ctaDemoSecondary: "Interaktive Demo ansehen",
    ctaDemoCardSubtitle: "8-stufiger interaktiver Rundgang · ohne Konto",
    ctaDemoCardLead: "So greifen Ranking, Feedback und Kalender ineinander",
    logInPrompt: "Bereits ein Konto?",
    socialProofEyebrow: "Kandidat:innen erkunden Rollen bei Unternehmen wie",
    teaserEyebrow: "In deinem Workspace",
    teaserTitle: "Dein Match-Feed und Pipeline — Vorschau",
    teaserUnlock: "Nach Anmeldung freischalten",
    insideEyebrow: "Was du drin bekommst",
    insideTitle:
      "Deine Pipeline kann arbeiten, während du schläfst — wenn die von dir aktivierte Automatisierung verfügbar ist",
    insideStep1Title: "Gerankter Feed",
    insideStep1Line: "Rollen passend zu deinem Profil bewertet — kein Feuerwehrstrahl jedes Inserats.",
    insideStep2Title: "Bewerbungsbuch",
    insideStep2Line: "Jeder Save und Status in einer Timeline, der Recruiter vertrauen.",
    insideStep3Title: "Interview-Kalender",
    insideStep3Line: "Slots, die sich lohnen — synchronisiert, wenn du den Kalender verbindest.",
    stickyCtaLabel: "Zur Gründerliste anmelden",
    stickyCtaMicro: "Gründer-Frühzugang · nur E-Mail · AGB gelten",
    joinWishlist: "Zur Gründerliste anmelden",
    joinWishlistMicro: "Erste 1.000 · Gründerkohorten-Vorteile · keine Karte · AGB gelten",
    foundingCounterAria: "Verbleibende Gründerlisten-Plätze",
    foundingCounterEyebrow: "Gründerplätze übrig",
    foundingCounterOf: "von {cap}",
    foundingCounterLoading: "Live-Zähler wird geladen…",
    foundingCounterLive: "Live-Listen-Daten",
    foundingCounterOffline: "Zähler verzögert — Anmeldung auf der nächsten Seite funktioniert weiter.",
    ctaBandWishlistEyebrow: "Gründer-Tausend",
    ctaBandWishlistTitle:
      "Gründer-Frühzugang vor öffentlichem Preis sichern — Vorteile gemäß AGB.",
    ctaBandWishlistMicro:
      "Gleiches Gründerangebot wie /first-1000 und Gründerliste — zuerst E-Mail; Gründerbedingungen und Fair-Use gelten.",
    logIn: "Anmelden",
    scrape: "Entdecken",
    scrapeDesc: "Inserate von aktivierten Börsen bündeln.",
    match: "Matching",
    matchDesc: "Bewertung nach Profil, Skills und Zielen.",
    track: "Verfolgen",
    trackDesc: "Suche, Merkliste und Status in einem Workspace.",
    featuresTitle: "Pipeline auf einen Blick",
    featuresSubtitle: "Live-Vorschau: Entdecken → Matchen → Verfolgen.",
    footerHint: "Profil nach Anmeldung ergänzen, damit Ranking echte Signale hat.",
    howEyebrow: "So funktioniert's",
    howTitle: "Vier Schritte zu einer ruhigeren Suche",
    howDetailLink: "Kompletter Rundgang",
    howStep1Title: "Verbinden",
    howStep1Line: "Jobbörsen und Regionen aktivieren, die dir wichtig sind.",
    howStep2Title: "Matchen",
    howStep2Line: "Rollen werden bei neuen Inseraten gegen dein Profil bewertet.",
    howStep3Title: "Verfolgen",
    howStep3Line: "Jeder Save und Bewerbungsstatus in einem Cockpit.",
    howStep4Title: "Automatisieren",
    howStep4Line: "Auto-Bewerbung und Kalender-Sync kommen in öffentlichen Phasen.",
    statsAria: "Plattformaktivität",
    statJobs: "Validierte Jobs",
    statUsers: "Mitglieder",
    statApps: "Bewerbungen",
    statBoards: "Börsen im Register",
    featureGridTitle: "Für Schwung gebaut, nicht Tab-Chaos",
    feature1Title: "Einheitlicher Feed",
    feature1Line: "Schluss mit Screenshots über mehrere Seiten.",
    feature2Title: "Profilbewusstes Ranking",
    feature2Line: "Scores, die Seniorität und Skills respektieren.",
    feature3Title: "CV-Intelligenz",
    feature3Line: "Signal vor der Bewerbung schärfen.",
    feature4Title: "Bewerbungsbuch",
    feature4Line: "Eine Timeline für jeden Statuswechsel.",
    feature5Title: "Einwilligung & DSGVO",
    feature5Line: "Explizites Opt-in; Exporte bei Bedarf.",
    feature6Title: "Phasenweise Automatisierung (heute pausiert)",
    feature6Line:
      "Bewerbungspakete zur Prüfung vorbereiten — Auto-Apply bleibt in Produktion pausiert, bis Freigaben es erlauben.",
  },
};

const fr: MarketingHomeOverlay = {
  home: {
    tagline: "Jumeau carrière IA",
    curiosityEyebrow: "Voir ce qu'il y a à l'intérieur",
    title: "Revenez à des entretiens qui valent le coup — pas au spam de la boîte mail.",
    heroHook:
      "La liste des fondateurs réserve les avantages d'accès anticipé pour les 1 000 premiers — conditions fondateurs, fair-use et CGU de lancement (voir /first-1000). Ou ouvrez un compte gratuit pour prévisualiser les matchs aujourd'hui.",
    description:
      "TWIN parcourt les sites que vous activez et fait remonter les rôles qui valent votre temps — après une absence vous ouvrez une courte liste de créneaux, pas du bruit.",
    getStarted: "Créer un compte gratuit",
    ctaRegisterMicro: "Vos matchs en ~2 min",
    ctaDemoSecondary: "Voir la démo interactive",
    ctaDemoCardSubtitle: "Parcours interactif en 8 étapes · sans compte",
    ctaDemoCardLead: "Comment classement, retours et calendrier s'articulent",
    logInPrompt: "Déjà un compte ?",
    socialProofEyebrow: "Des candidats explorent des rôles chez des entreprises comme",
    teaserEyebrow: "Dans votre espace de travail",
    teaserTitle: "Votre fil de matchs et pipeline — aperçu",
    teaserUnlock: "Débloquer après inscription",
    insideEyebrow: "Ce que vous obtenez à l'intérieur",
    insideTitle:
      "Votre pipeline peut travailler pendant que vous dormez — quand l'automatisation activée est disponible",
    insideStep1Title: "Fil classé",
    insideStep1Line: "Rôles notés selon votre profil — pas un déluge de chaque annonce.",
    insideStep2Title: "Registre des candidatures",
    insideStep2Line: "Chaque sauvegarde et statut dans une timeline fiable pour les recruteurs.",
    insideStep3Title: "Calendrier d'entretiens",
    insideStep3Line: "Créneaux qui valent le déplacement, synchronisés à la connexion du calendrier.",
    stickyCtaLabel: "Rejoindre la liste des fondateurs",
    stickyCtaMicro: "Accès anticipé fondateur · e-mail seulement · CGU applicables",
    joinWishlist: "Rejoindre la liste des fondateurs",
    joinWishlistMicro: "1 000 premiers · avantages cohorte fondatrice · sans carte · CGU applicables",
    foundingCounterAria: "Places restantes sur la liste des fondateurs",
    foundingCounterEyebrow: "Places fondatrices restantes",
    foundingCounterOf: "sur {cap}",
    foundingCounterLoading: "Chargement du compteur en direct…",
    foundingCounterLive: "Données de liste en direct",
    foundingCounterOffline: "Compteur retardé — l'inscription sur la page suivante fonctionne toujours.",
    ctaBandWishlistEyebrow: "Mille fondateurs",
    ctaBandWishlistTitle:
      "Réservez l'accès anticipé fondateur avant les tarifs publics — avantages soumis aux CGU.",
    ctaBandWishlistMicro:
      "Même offre fondatrice que /first-1000 et la liste — e-mail d'abord ; conditions fondateurs et fair-use applicables.",
    logIn: "Se connecter",
    howEyebrow: "Comment ça marche",
    howTitle: "Quatre étapes vers une recherche plus calme",
    howDetailLink: "Parcours complet",
    howStep1Title: "Connecter",
    howStep1Line: "Activez les job boards et régions qui comptent pour vous.",
    howStep2Title: "Matcher",
    howStep2Line: "Rôles notés selon votre profil à l'arrivée des annonces.",
    howStep3Title: "Suivre",
    howStep3Line: "Chaque sauvegarde et statut de candidature dans un seul cockpit.",
    howStep4Title: "Automatiser",
    howStep4Line: "Candidature auto et sync calendrier arrivent par phases publiques.",
    statsAria: "Activité de la plateforme",
    statJobs: "Offres validées",
    statUsers: "Membres",
    statApps: "Candidatures",
    statBoards: "Sites dans le registre",
    featureGridTitle: "Conçu pour l'élan, pas le chaos d'onglets",
    feature1Title: "Fil unifié",
    feature1Line: "Fini les captures d'écran sur plusieurs sites.",
    feature2Title: "Classement profil-aware",
    feature2Line: "Scores qui respectent séniorité et compétences.",
    feature3Title: "Intelligence CV",
    feature3Line: "Affinez le signal avant de postuler.",
    feature4Title: "Registre des candidatures",
    feature4Line: "Une timeline pour chaque changement de statut.",
    feature5Title: "Consentement & RGPD",
    feature5Line: "Opt-in explicite ; exports quand vous en avez besoin.",
    feature6Title: "Automatisation par phases (en pause aujourd'hui)",
    feature6Line:
      "Préparez des dossiers de candidature pour relecture — l'auto-candidature reste en pause en production jusqu'aux validations.",
    featuresTitle: "Pipeline en un coup d'œil",
    featuresSubtitle: "Aperçu live : découvrir → matcher → suivre.",
    footerHint: "Ajoutez un profil après inscription pour un ranking avec signal réel.",
    scrape: "Découvrir",
    scrapeDesc: "Agrège les annonces des sites activés.",
    match: "Matcher",
    matchDesc: "Notes selon profil, compétences et objectifs.",
    track: "Suivre",
    trackDesc: "Recherche, favoris et statuts dans un espace.",
  },
};

const it: MarketingHomeOverlay = {
  home: {
    getStarted: "Inizia gratis",
    ctaRegisterMicro: "Vedi i tuoi match in ~2 min",
    curiosityEyebrow: "Guarda cosa c'è dentro",
    joinWishlist: "Unisciti alla lista dei fondatori",
    joinWishlistMicro: "Primi 1.000 · vantaggi della cohorte iniziale · nessuna carta · si applicano i Termini",
    stickyCtaLabel: "Unisciti alla lista dei fondatori",
    insideEyebrow: "Cosa ottieni dentro",
    insideTitle: "La tua pipeline può lavorare mentre dormi — quando l'automazione attivata è disponibile",
    insideStep1Title: "Feed classificato",
    insideStep1Line: "Ruoli valutati sul tuo profilo — non un torrente di ogni annuncio.",
    insideStep2Title: "Registro candidature",
    insideStep2Line: "Ogni salvataggio e stato in una timeline di cui i recruiter si fidano.",
    insideStep3Title: "Calendario colloqui",
    insideStep3Line: "Slot che valgono la pena, sincronizzati col calendario connesso.",
    heroHook:
      "La lista dei fondatori riserva vantaggi di accesso anticipato per i primi 1.000 — termini fondatori, fair-use e Termini di lancio (vedi /first-1000). Oppure apri un account gratuito per vedere i match oggi.",
    ctaBandWishlistTitle: "Prenota l'accesso anticipato da fondatore prima dei prezzi pubblici — vantaggi soggetti ai Termini.",
    ctaBandWishlistMicro:
      "Stessa offerta di /first-1000 e della lista iniziale — prima l'email; si applicano termini fondatori e fair-use.",
    foundingCounterEyebrow: "Posti fondatori rimasti",
    feature6Title: "Automazione a fasi (in pausa oggi)",
    feature6Line:
      "Prepara pacchetti candidatura per revisione — l'auto-apply resta in pausa in produzione finché i gate non lo consentono.",
    ctaDemoSecondary: "Guarda la demo interattiva",
    howTitle: "Quattro passi verso una ricerca più tranquilla",
    featureGridTitle: "Fatto per lo slancio, non il caos di schede",
  },
};

const zh: MarketingHomeOverlay = {
  home: {
    getStarted: "免费开始",
    ctaRegisterMicro: "约 2 分钟内查看匹配",
    curiosityEyebrow: "看看里面有什么",
    joinWishlist: "加入创始候补名单",
    joinWishlistMicro: "前 1,000 名 · 创始队列权益 · 无需信用卡 · 适用条款",
    stickyCtaLabel: "加入创始候补名单",
    insideEyebrow: "你将获得的内容",
    insideTitle: "你睡觉时管道仍可运转 — 在你启用的自动化可用时",
    insideStep1Title: "排序信息流",
    insideStep1Line: "按个人档案评分的职位 — 不是每个列表的洪流。",
    insideStep2Title: "申请台账",
    insideStep2Line: "每次保存和状态都在招聘方信任的一条时间线上。",
    insideStep3Title: "面试日历",
    insideStep3Line: "值得赴约的时段，连接日历后同步。",
    heroHook:
      "创始候补为前 1,000 名保留提前访问权益 — 适用创始条款、合理使用及上线条款（见 /first-1000）。或免费开户今日预览匹配。",
    ctaBandWishlistTitle: "在公开定价前预留创始提前访问 — 权益受条款约束。",
    foundingCounterEyebrow: "剩余创始名额",
    ctaBandWishlistMicro: "与 /first-1000 及创始候补相同优惠 — 先留邮箱；适用创始条款与合理使用。",
    feature6Title: "分阶段自动化（当前暂停）",
    feature6Line: "准备申请包供审阅 — 生产环境自动投递保持暂停，直至闸门允许。",
    ctaDemoSecondary: "观看交互式演示",
    howTitle: "四步走向更从容的求职",
    featureGridTitle: "为节奏而建，而非标签混乱",
  },
};

const ja: MarketingHomeOverlay = {
  home: {
    getStarted: "無料で始める",
    ctaRegisterMicro: "約2分でマッチを確認",
    curiosityEyebrow: "中身を見る",
    joinWishlist: "創設者リストに参加",
    joinWishlistMicro: "先着1,000名 · 創設コホート特典 · カード不要 · 規約が適用",
    stickyCtaLabel: "創設者リストに参加",
    insideEyebrow: "中で得られるもの",
    insideTitle: "眠っている間もパイプラインが動く — 有効化した自動化が利用可能なとき",
    insideStep1Title: "ランキングフィード",
    insideStep1Line: "プロフィールに合わせてスコア付け — 全求人の洪水ではない。",
    insideStep2Title: "応募台帳",
    insideStep2Line: "保存とステータスを採用担当が信頼できる1本のタイムラインに。",
    insideStep3Title: "面接カレンダー",
    insideStep3Line: "赴く価値のある枠を、カレンダー連携で同期。",
    heroHook:
      "創設者リストは最初の1,000名に早期アクセス特典を確保 — 創設条件・フェアユース・ローンチ規約が適用（/first-1000 参照）。または無料アカウントで今日マッチをプレビュー。",
    ctaBandWishlistTitle: "公開価格前に創設早期アクセスを確保 — 特典は規約に従う。",
    foundingCounterEyebrow: "残り創設枠",
    ctaBandWishlistMicro: "/first-1000 と創設者リストと同じ特典 — まずメール；創設条件とフェアユースが適用。",
    feature6Title: "段階的な自動化（現在は一時停止）",
    feature6Line: "審査用の応募パッケージを準備 — 本番の自動応募はゲートが許可するまで停止。",
    ctaDemoSecondary: "インタラクティブデモを見る",
    howTitle: "より穏やかな転職活動への4ステップ",
    featureGridTitle: "タブの混沌ではなく、勢いのために",
  },
};

const ar: MarketingHomeOverlay = {
  home: {
    getStarted: "ابدأ مجاناً",
    ctaRegisterMicro: "شاهد تطابقاتك في ~2 دقيقة",
    curiosityEyebrow: "اكتشف ما بالداخل",
    joinWishlist: "انضم إلى قائمة المؤسسين",
    joinWishlistMicro: "أول 1,000 · مزايا مجموعة المؤسسين · بدون بطاقة · تنطبق الشروط",
    stickyCtaLabel: "انضم إلى قائمة المؤسسين",
    insideEyebrow: "ما تحصل عليه بالداخل",
    insideTitle: "خط أنابيبك يعمل وأنت نائم — عندما تكون الأتمتة المفعّلة متاحة",
    insideStep1Title: "خلاصة مرتبة",
    insideStep1Line: "أدوار مُقيّمة لملفك — وليس سيل كل الإعلانات.",
    insideStep2Title: "سجل الطلبات",
    insideStep2Line: "كل حفظ وحالة في جدول زمني يثق به المُوظّفون.",
    insideStep3Title: "تقويم المقابلات",
    insideStep3Line: "مواعيد تستحق الحضور، متزامنة عند ربط التقويم.",
    heroHook:
      "قائمة المؤسسين تحجز مزايا الوصول المبكر لأول 1,000 — شروط المؤسسين والاستخدام العادل وشروط الإطلاق (انظر /first-1000). أو افتح حساباً مجانياً لمعاينة التطابقات اليوم.",
    ctaBandWishlistTitle: "احجز الوصول المبكر للمؤسسين قبل التسعير العام — المزايا خاضعة للشروط.",
    foundingCounterEyebrow: "أماكن المؤسسين المتبقية",
    ctaBandWishlistMicro: "نفس عرض /first-1000 وقائمة المؤسسين — البريد أولاً؛ تنطبق شروط المؤسسين والاستخدام العادل.",
    feature6Title: "أتمتة على مراحل (متوقفة اليوم)",
    feature6Line: "جهّز حزم الطلبات للمراجعة — التقديم التلقائي متوقف في الإنتاج حتى تسمح بوابات الإطلاق.",
    ctaDemoSecondary: "شاهد العرض التفاعلي",
    howTitle: "أربع خطوات نحو بحث أكثر هدوءاً",
    featureGridTitle: "مبني للزخم، لا فوضى التبويبات",
  },
};

function withBelowFold(locale: Locale, overlay: MarketingHomeOverlay): MarketingHomeOverlay {
  const below = MARKETING_HOME_BELOW_FOLD[locale];
  if (!below) return overlay;
  return mergeDeep(overlay, below) as MarketingHomeOverlay;
}

export const MARKETING_HOME_OVERLAYS: Partial<Record<Locale, MarketingHomeOverlay>> = {
  es: withBelowFold("es", es),
  de: withBelowFold("de", de),
  fr: withBelowFold("fr", fr),
  it: withBelowFold("it", it),
  zh: withBelowFold("zh", zh),
  ja: withBelowFold("ja", ja),
  ar: withBelowFold("ar", ar),
};
