/**
 * Global footer, momentum rail, and marketing chrome nav labels.
 * Merged at dictionary build — prevents EN leakage in footer/support sections.
 */
import type { Locale } from "../i18n";

type SiteChromeOverlay = {
  nav: Record<string, string>;
  site: Record<string, string>;
};

const chromeNavEs: SiteChromeOverlay["nav"] = {
  about: "Sobre nosotros",
  howItWorks: "Cómo funciona",
  pricing: "Precios",
  cases: "Casos de estudio",
  contact: "Contacto",
  faq: "FAQ",
  careers: "Carreras",
  media: "Medios",
  partners: "Socios",
  forCandidates: "Candidatos",
  forRecruiters: "Reclutadores",
  forCompanies: "Empresas",
  forInvestors: "Inversor",
  demo: "Demo",
  waitlist: "Lista fundadora",
  calculator: "Calculadora ROI B2B",
  calculatorInvestor: "Calculadora inversor",
};

const chromeSiteEs: SiteChromeOverlay["site"] = {
  footerTagline: "Agente de carrera autónomo",
  footerExplore: "Explorar",
  footerHome: "Inicio",
  footerWishlist: "Lista fundadora (acceso anticipado)",
  footerCompany: "Empresa",
  footerLegal: "Información legal",
  footerPrivacy: "Política de privacidad",
  footerTerms: "Términos de servicio",
  footerStatus: "Estado del sistema",
  footerDevelopers: "Desarrolladores",
  footerCandidateLogin: "Inicio de sesión candidato",
  footerCandidateRegister: "Registro candidato",
  footerRecruiterLogin: "Inicio de sesión reclutador",
  footerInvestorLogin: "Inicio de sesión inversor",
  footerCompanyLogin: "Inicio de sesión empresa",
  footerCompanySignup: "Registro programa empresas",
  footerCookieSettings: "Configuración de cookies",
  footerRights: "© 2026 TWIN. Todos los derechos reservados.",
  footerSocial: "Redes sociales",
  footerLinkedInAria: "TWIN en LinkedIn",
  footerGithubAria: "TWIN en GitHub",
  footerXAria: "TWIN en X",
  headerSocialAria: "TWIN en redes sociales",
  momentumAria: "Consejos y atajos",
  momentumEyebrow: "Mantén el impulso",
  momentumLead: "Los pequeños rituales ganan a las grandes búsquedas semanales de empleo.",
  momentumTip1:
    "Cuando guardas o aplicas desde coincidencias o el flujo de ofertas, las candidaturas van a una línea de tiempo. Trátala como tu registro privado de solicitudes hasta que lleguen entrevistas.",
  momentumTip2:
    "Actualiza los filtros tras editar habilidades o títulos objetivo para que el flujo de ofertas capte la nueva señal.",
  momentumTip3:
    "Estados que reflejan la realidad (enviada, entrevista, rechazada) mantienen creíbles los gráficos semanales.",
  momentumTip4:
    "Si el flujo de ofertas es demasiado amplio, ajusta términos del título; amplía cuando veas roles que realmente quieres.",
  momentumTip5:
    "Premium levanta límites de candidaturas rastreadas cuando la facturación está activa en tu entorno. La versión gratuita sigue siendo sólida para búsquedas enfocadas.",
  momentumTip6:
    "Abre ofertas complicadas en una pestaña nueva; deja que TWIN recuerde tu decisión para no releer la misma descripción del puesto.",
  momentumCtaWorkspace: "Abrir espacio de trabajo",
  momentumCtaProfile: "Perfil y CV",
  momentumCtaHome: "Historia del producto",
  momentumCtaRegister: "Crear cuenta",
  momentumCtaLogin: "Iniciar sesión",
  momentumCtaFaq: "FAQ",
};

const chromeNavDe: SiteChromeOverlay["nav"] = {
  about: "Über uns",
  howItWorks: "So funktioniert's",
  pricing: "Preise",
  cases: "Fallstudien",
  contact: "Kontakt",
  faq: "FAQ",
  careers: "Karriere",
  media: "Medien",
  partners: "Partner",
  forCandidates: "Kandidaten",
  forRecruiters: "Recruiter",
  forCompanies: "Unternehmen",
  forInvestors: "Für Investoren",
  demo: "Demo",
  waitlist: "Gründerliste",
  calculator: "B2B-ROI-Rechner",
  calculatorInvestor: "Investor-Rechner",
};

const chromeSiteDe: SiteChromeOverlay["site"] = {
  footerTagline: "Autonomer Karriere-Agent",
  footerExplore: "Entdecken",
  footerHome: "Startseite",
  footerWishlist: "Gründerliste (früher Zugang)",
  footerCompany: "Unternehmen",
  footerLegal: "Rechtliches",
  footerPrivacy: "Datenschutzerklärung",
  footerTerms: "Nutzungsbedingungen",
  footerStatus: "Systemstatus",
  footerDevelopers: "Entwickler",
  footerCandidateLogin: "Kandidaten-Anmeldung",
  footerCandidateRegister: "Kandidaten-Registrierung",
  footerRecruiterLogin: "Recruiter-Anmeldung",
  footerInvestorLogin: "Investor-Anmeldung",
  footerCompanyLogin: "Unternehmens-Anmeldung",
  footerCompanySignup: "Unternehmensprogramm anmelden",
  footerCookieSettings: "Cookie-Einstellungen",
  footerRights: "© 2026 TWIN. Alle Rechte vorbehalten.",
  footerSocial: "Soziale Netzwerke",
  footerLinkedInAria: "TWIN auf LinkedIn",
  footerGithubAria: "TWIN auf GitHub",
  footerXAria: "TWIN auf X",
  headerSocialAria: "TWIN in sozialen Medien",
  momentumAria: "Tipps und Shortcuts",
  momentumEyebrow: "Schwung beibehalten",
  momentumLead: "Kleine Routinen schlagen heroische Jobsuche einmal pro Woche.",
  momentumTip1:
    "Wenn Sie aus Matches oder dem Stellenstrom speichern oder bewerben, landen Bewerbungen in einer Timeline. Behandeln Sie sie als privates Bewerbungsregister bis Interviews kommen.",
  momentumTip2:
    "Aktualisieren Sie Filter nach Skills oder Zieltiteln, damit der Stellenstrom das neue Signal aufnimmt.",
  momentumTip3:
    "Realistische Status (beworben, Interview, abgelehnt) halten wöchentliche Momentum-Charts glaubwürdig.",
  momentumTip4:
    "Ist der Stellenstrom zu breit, Titelbegriffe enger setzen; wieder weiten, wenn passende Rollen erscheinen.",
  momentumTip5:
    "Premium hebt Limits für verfolgte Bewerbungen, wenn die Abrechnung in Ihrer Umgebung aktiv ist. Die kostenlose Version reicht für fokussierte Suche.",
  momentumTip6:
    "Öffnen Sie knifflige Stellen in einem neuen Tab; TWIN merkt sich Ihre Entscheidung, damit Sie dieselbe Stellenbeschreibung nicht erneut lesen.",
  momentumCtaWorkspace: "Workspace öffnen",
  momentumCtaProfile: "Profil & Lebenslauf",
  momentumCtaHome: "Produktstory",
  momentumCtaRegister: "Konto erstellen",
  momentumCtaLogin: "Anmelden",
  momentumCtaFaq: "FAQ",
};

const chromeNavFr: SiteChromeOverlay["nav"] = {
  about: "À propos",
  howItWorks: "Comment ça marche",
  pricing: "Tarifs",
  cases: "Études de cas",
  contact: "Nous contacter",
  faq: "FAQ",
  careers: "Carrières",
  media: "Médias",
  partners: "Partenaires",
  forCandidates: "Candidats",
  forRecruiters: "Recruteurs",
  forCompanies: "Entreprises",
  forInvestors: "Investisseurs",
  demo: "Démo",
  waitlist: "Liste des fondateurs",
  calculator: "Calculateur ROI B2B",
  calculatorInvestor: "Calculateur investisseur",
};

const chromeSiteFr: SiteChromeOverlay["site"] = {
  footerTagline: "Agent de carrière autonome",
  footerExplore: "Explorer",
  footerHome: "Accueil",
  footerWishlist: "Liste des fondateurs (accès anticipé)",
  footerCompany: "Entreprise",
  footerLegal: "Mentions légales",
  footerPrivacy: "Politique de confidentialité",
  footerTerms: "Conditions d'utilisation",
  footerStatus: "État du système",
  footerDevelopers: "Développeurs",
  footerCandidateLogin: "Connexion candidat",
  footerCandidateRegister: "Inscription candidat",
  footerRecruiterLogin: "Connexion recruteur",
  footerInvestorLogin: "Connexion investisseur",
  footerCompanyLogin: "Connexion entreprise",
  footerCompanySignup: "Inscription programme entreprise",
  footerCookieSettings: "Paramètres des cookies",
  footerRights: "© 2026 TWIN. Tous droits réservés.",
  footerSocial: "Réseaux sociaux",
  footerLinkedInAria: "TWIN sur LinkedIn",
  footerGithubAria: "TWIN sur GitHub",
  footerXAria: "TWIN sur X",
  headerSocialAria: "TWIN sur les réseaux sociaux",
  momentumAria: "Conseils et raccourcis",
  momentumEyebrow: "Gardez l'élan",
  momentumLead: "Les petits rituels battent les grandes chasses à l'emploi hebdomadaires.",
  momentumTip1:
    "Quand vous enregistrez ou postulez depuis les matchs ou le flux d'offres, les candidatures arrivent sur une chronologie. Traitez-la comme votre registre privé de candidatures jusqu'aux entretiens.",
  momentumTip2:
    "Rafraîchissez les filtres après avoir modifié compétences ou titres cibles pour que le flux d'offres capte le nouveau signal.",
  momentumTip3:
    "Des statuts réalistes (postulé, entretien, refusé) gardent des graphiques hebdomadaires crédibles.",
  momentumTip4:
    "Si le flux d'offres est trop large, resserrez les termes de titre ; élargissez quand vous voyez les rôles voulus.",
  momentumTip5:
    "Premium lève les plafonds de candidatures suivies quand la facturation est active dans votre environnement. La version gratuite reste solide pour une recherche ciblée.",
  momentumTip6:
    "Ouvrez les offres délicates dans un nouvel onglet ; TWIN retient votre décision pour ne pas relire la même fiche de poste.",
  momentumCtaWorkspace: "Ouvrir l'espace de travail",
  momentumCtaProfile: "Profil & CV",
  momentumCtaHome: "Histoire produit",
  momentumCtaRegister: "Créer un compte",
  momentumCtaLogin: "Se connecter",
  momentumCtaFaq: "FAQ",
};

const chromeNavIt: SiteChromeOverlay["nav"] = {
  about: "Chi siamo",
  howItWorks: "Come funziona",
  pricing: "Prezzi",
  cases: "Casi studio",
  contact: "Contatto",
  faq: "FAQ",
  careers: "Carriere",
  media: "Stampa e media",
  partners: "Partner",
  forCandidates: "Candidati",
  forRecruiters: "Recruiter",
  forCompanies: "Aziende",
  forInvestors: "Investitore",
  demo: "Demo",
  waitlist: "Lista fondatori",
  calculator: "Calcolatore ROI B2B",
  calculatorInvestor: "Calcolatore investitore",
};

const chromeSiteIt: SiteChromeOverlay["site"] = {
  footerTagline: "Agente di carriera autonomo",
  footerExplore: "Esplora",
  footerHome: "Pagina iniziale",
  footerWishlist: "Lista fondatori (accesso anticipato)",
  footerCompany: "Azienda",
  footerLegal: "Note legali",
  footerPrivacy: "Informativa sulla privacy",
  footerTerms: "Termini di servizio",
  footerStatus: "Stato del sistema",
  footerDevelopers: "Sviluppatori",
  footerCandidateLogin: "Accesso candidato",
  footerCandidateRegister: "Registrazione candidato",
  footerRecruiterLogin: "Accesso recruiter",
  footerInvestorLogin: "Accesso investitore",
  footerCompanyLogin: "Accesso azienda",
  footerCompanySignup: "Iscrizione programma aziende",
  footerCookieSettings: "Impostazioni cookie",
  footerRights: "© 2026 TWIN. Tutti i diritti riservati.",
  footerSocial: "Reti sociali",
  footerLinkedInAria: "TWIN su LinkedIn",
  footerGithubAria: "TWIN su GitHub",
  footerXAria: "TWIN su X",
  headerSocialAria: "TWIN sui social",
  momentumAria: "Suggerimenti e scorciatoie",
  momentumEyebrow: "Mantieni lo slancio",
  momentumLead: "Piccoli rituali battono la grande caccia al lavoro settimanale.",
  momentumTip1:
    "Quando salvi o candidi da match o flusso offerte, le candidature finiscono in una cronologia. Trattala come registro privato delle candidature fino ai colloqui.",
  momentumTip2:
    "Aggiorna i filtri dopo aver modificato competenze o titoli target così il flusso offerte coglie il nuovo segnale.",
  momentumTip3:
    "Stati realistici (inviata, colloquio, rifiutata) rendono credibili i grafici settimanali.",
  momentumTip4:
    "Se il flusso offerte è troppo ampio, restringi i termini del titolo; allarga quando vedi ruoli desiderati.",
  momentumTip5:
    "Premium alza i limiti sulle candidature tracciate quando la fatturazione è attiva nel tuo ambiente. La versione gratuita resta solida per ricerche mirate.",
  momentumTip6:
    "Apri annunci difficili in una nuova scheda; TWIN ricorda la decisione così non rileggi la stessa descrizione del ruolo.",
  momentumCtaWorkspace: "Apri workspace",
  momentumCtaProfile: "Profilo e CV",
  momentumCtaHome: "Storia prodotto",
  momentumCtaRegister: "Crea account",
  momentumCtaLogin: "Accedi",
  momentumCtaFaq: "FAQ",
};

const chromeNavZh: SiteChromeOverlay["nav"] = {
  about: "关于我们",
  howItWorks: "如何运作",
  pricing: "定价",
  cases: "案例研究",
  contact: "联系",
  faq: "常见问题",
  careers: "招聘",
  media: "媒体",
  partners: "合作伙伴",
  forCandidates: "求职者",
  forRecruiters: "招聘方",
  forCompanies: "企业",
  forInvestors: "投资者",
  demo: "演示",
  waitlist: "创始候补名单",
  calculator: "B2B ROI 计算器",
  calculatorInvestor: "投资者计算器",
};

const chromeSiteZh: SiteChromeOverlay["site"] = {
  footerTagline: "自主职业代理",
  footerExplore: "探索",
  footerHome: "首页",
  footerWishlist: "创始候补名单（早期访问）",
  footerCompany: "公司",
  footerLegal: "法律",
  footerPrivacy: "隐私政策",
  footerTerms: "服务条款",
  footerStatus: "系统状态",
  footerDevelopers: "开发者",
  footerCandidateLogin: "候选人登录",
  footerCandidateRegister: "候选人注册",
  footerRecruiterLogin: "招聘方登录",
  footerInvestorLogin: "投资者登录",
  footerCompanyLogin: "企业登录",
  footerCompanySignup: "企业计划注册",
  footerCookieSettings: "Cookie 设置",
  footerRights: "© 2026 TWIN. 保留所有权利。",
  footerSocial: "社交",
  footerLinkedInAria: "TWIN 领英",
  footerGithubAria: "TWIN GitHub",
  footerXAria: "TWIN X",
  headerSocialAria: "TWIN 社交媒体",
  momentumAria: "提示与快捷方式",
  momentumEyebrow: "保持动力",
  momentumLead: "小习惯胜过每周一次的英雄式求职。",
  momentumTip1:
    "从匹配或职位流保存或申请时，申请会进入一条时间线。在面试出现前，把它当作私人申请记录。",
  momentumTip2: "编辑技能或目标职位后刷新筛选，让职位流捕捉新信号。",
  momentumTip3: "符合实际的状态（已申请、面试、拒绝）让每周动力图表更可信。",
  momentumTip4: "若职位流过宽，收紧职位关键词；看到想要的职位后再放宽。",
  momentumTip5: "环境中启用计费时，高级版提高跟踪申请上限。免费版仍适合专注搜索。",
  momentumTip6: "在新标签页打开棘手职位；TWIN 会记住你的决定，避免重复阅读同一份职位描述。",
  momentumCtaWorkspace: "打开工作区",
  momentumCtaProfile: "个人资料与简历",
  momentumCtaHome: "产品故事",
  momentumCtaRegister: "创建账户",
  momentumCtaLogin: "登录",
  momentumCtaFaq: "常见问题",
};

const chromeNavAr: SiteChromeOverlay["nav"] = {
  about: "من نحن",
  howItWorks: "كيف يعمل",
  pricing: "الأسعار",
  cases: "دراسات حالة",
  contact: "اتصل",
  faq: "الأسئلة الشائعة",
  careers: "وظائف",
  media: "الإعلام",
  partners: "شركاء",
  forCandidates: "مرشحون",
  forRecruiters: "مسؤولو التوظيف",
  forCompanies: "شركات",
  forInvestors: "مستثمر",
  demo: "عرض",
  waitlist: "قائمة المؤسسين",
  calculator: "حاسبة عائد B2B",
  calculatorInvestor: "حاسبة المستثمر",
};

const chromeSiteAr: SiteChromeOverlay["site"] = {
  footerTagline: "وكيل مهني مستقل",
  footerExplore: "استكشف",
  footerHome: "الرئيسية",
  footerWishlist: "قائمة المؤسسين (وصول مبكر)",
  footerCompany: "الشركة",
  footerLegal: "قانوني",
  footerPrivacy: "سياسة الخصوصية",
  footerTerms: "شروط الخدمة",
  footerStatus: "حالة النظام",
  footerDevelopers: "المطورون",
  footerCandidateLogin: "تسجيل دخول المرشح",
  footerCandidateRegister: "تسجيل المرشح",
  footerRecruiterLogin: "تسجيل دخول المسؤول",
  footerInvestorLogin: "تسجيل دخول المستثمر",
  footerCompanyLogin: "تسجيل دخول الشركة",
  footerCompanySignup: "تسجيل برنامج الشركات",
  footerCookieSettings: "إعدادات ملفات تعريف الارتباط",
  footerRights: "© 2026 TWIN. جميع الحقوق محفوظة.",
  footerSocial: "التواصل",
  footerLinkedInAria: "TWIN على LinkedIn",
  footerGithubAria: "TWIN على GitHub",
  footerXAria: "TWIN على X",
  headerSocialAria: "TWIN على وسائل التواصل",
  momentumAria: "نصائح واختصارات",
  momentumEyebrow: "حافظ على الزخم",
  momentumLead: "الطقوس الصغيرة تتفوق على مطاردة الوظائف البطولية مرة في الأسبوع.",
  momentumTip1:
    "عند الحفظ أو التقديم من التطابقات أو تدفق الوظائف، تنتقل الطلبات إلى خط زمني واحد. اعتبره سجل طلبات خاصًا حتى تظهر المقابلات.",
  momentumTip2: "حدّث المرشحات بعد تعديل المهارات أو المسميات المستهدفة ليلتقط تدفق الوظائف الإشارة الجديدة.",
  momentumTip3: "حالات واقعية (مُقدَّم، مقابلة، مرفوض) تجعل مخططات الزخم الأسبوعية موثوقة.",
  momentumTip4: "إذا كان تدفق الوظائف واسعًا جدًا، ضيّق عبارات المسمى؛ وسّع عندما ترى أدوارًا تريدها فعلًا.",
  momentumTip5: "الإصدار المميز يرفع حدود الطلبات المتتبعة عند تفعيل الفوترة في بيئتك. المجاني يبقى قويًا للبحث المركّز.",
  momentumTip6: "افتح الإعلانات الصعبة في تبويب جديد؛ TWIN يتذكر قرارك حتى لا تعيد قراءة نفس الوصف.",
  momentumCtaWorkspace: "افتح مساحة العمل",
  momentumCtaProfile: "الملف والسيرة",
  momentumCtaHome: "قصة المنتج",
  momentumCtaRegister: "إنشاء حساب",
  momentumCtaLogin: "تسجيل الدخول",
  momentumCtaFaq: "الأسئلة الشائعة",
};

const chromeNavJa: SiteChromeOverlay["nav"] = {
  about: "会社概要",
  howItWorks: "仕組み",
  pricing: "料金",
  cases: "事例",
  contact: "お問い合わせ",
  faq: "FAQ",
  careers: "採用",
  media: "メディア",
  partners: "パートナー",
  forCandidates: "候補者",
  forRecruiters: "リクルーター",
  forCompanies: "企業",
  forInvestors: "投資家",
  demo: "デモ",
  waitlist: "ファウンダー待機リスト",
  calculator: "B2B ROI 計算機",
  calculatorInvestor: "投資家計算機",
};

const chromeSiteJa: SiteChromeOverlay["site"] = {
  footerTagline: "自律型キャリアエージェント",
  footerExplore: "探索",
  footerHome: "ホーム",
  footerWishlist: "ファウンダー待機リスト（早期アクセス）",
  footerCompany: "会社",
  footerLegal: "法務",
  footerPrivacy: "プライバシーポリシー",
  footerTerms: "利用規約",
  footerStatus: "システム状況",
  footerDevelopers: "開発者",
  footerCandidateLogin: "候補者ログイン",
  footerCandidateRegister: "候補者登録",
  footerRecruiterLogin: "リクルーターログイン",
  footerInvestorLogin: "投資家ログイン",
  footerCompanyLogin: "企業ログイン",
  footerCompanySignup: "企業プログラム登録",
  footerCookieSettings: "Cookie 設定",
  footerRights: "© 2026 TWIN. 無断転載を禁じます。",
  footerSocial: "ソーシャル",
  footerLinkedInAria: "TWIN の LinkedIn",
  footerGithubAria: "TWIN の GitHub",
  footerXAria: "TWIN の X",
  headerSocialAria: "TWIN ソーシャル",
  momentumAria: "ヒントとショートカット",
  momentumEyebrow: "勢いを保つ",
  momentumLead: "小さな習慣が、週に一度の英雄的行動より勝つ。",
  momentumTip1:
    "マッチや求人ストリームから保存・応募すると、応募は1本のタイムラインに集まります。面接が来るまで私用の応募記録として扱ってください。",
  momentumTip2: "スキルや目標職種を編集したらフィルターを更新し、求人ストリームが新しいシグナルを拾えるようにします。",
  momentumTip3: "現実的なステータス（応募済み、面接、不採用）で週次の勢いグラフが信頼できます。",
  momentumTip4: "求人ストリームが広すぎるときはタイトル語を絞り、欲しい職種が見えたら広げます。",
  momentumTip5: "環境で課金が有効なら有料版が追跡応募の上限を上げます。無料版でも集中検索には十分です。",
  momentumTip6: "難しい求人は新しいタブで開き、TWIN に判断を覚えさせて同じ職務記述を読み直さないようにします。",
  momentumCtaWorkspace: "ワークスペースを開く",
  momentumCtaProfile: "プロフィールとCV",
  momentumCtaHome: "プロダクトストーリー",
  momentumCtaRegister: "アカウント作成",
  momentumCtaLogin: "ログイン",
  momentumCtaFaq: "FAQ",
};

export const SITE_CHROME_OVERLAYS: Partial<Record<Locale, SiteChromeOverlay>> = {
  es: { nav: chromeNavEs, site: chromeSiteEs },
  de: { nav: chromeNavDe, site: chromeSiteDe },
  fr: { nav: chromeNavFr, site: chromeSiteFr },
  it: { nav: chromeNavIt, site: chromeSiteIt },
  zh: { nav: chromeNavZh, site: chromeSiteZh },
  ar: { nav: chromeNavAr, site: chromeSiteAr },
  ja: { nav: chromeNavJa, site: chromeSiteJa },
};
