/** Simplified Chinese overlay: nav, common, home (BCP-47: zh-Hans in provider). */
export const zhOverlay: Record<string, unknown> = {
  nav: {
    login: "登录",
    register: "注册",
    profile: "个人资料",
    dashboard: "控制台",
    calculator: "B2B 投资回报计算器",
    menu: "菜单",
    ariaCompanyNav: "企业导航",
    ariaAccountNav: "账户导航",
    ariaMobileNav: "主导航",
  },
  common: {
    language: "语言",
    switchToPl: "PL",
    switchToEn: "EN",
    loading: "加载中",
    loadingEllipsis: "加载中…",
    errorTitle: "出了点问题",
    errorBody: "请重试。若问题仍在，请刷新页面。",
    tryAgain: "重试",
  },
  meta: {
    titleHome: "TWIN — 职业代理",
    titleAbout: "关于我们 — TWIN",
    titleCaseStudies: "案例研究 — TWIN",
    titleFaq: "常见问题 — TWIN",
    titlePartners: "合作伙伴 — TWIN",
    titleMedia: "媒体 — TWIN",
    titleCareers: "招聘 — TWIN",
    titleContact: "联系我们 — TWIN",
    titleCalculator: "B2B 投资回报计算器 — TWIN",
    titleLogin: "登录 — TWIN",
    titleRegister: "注册 — TWIN",
    titleProfile: "个人资料 — TWIN",
    titleDashboard: "控制台 — TWIN",
    titlePrivacy: "隐私 — TWIN",
    titleForgotPassword: "忘记密码 — TWIN",
    titleResetPassword: "重置密码 — TWIN",
    titleOnboarding: "工作区导览 — TWIN",
    titleBilling: "套餐与账单 — TWIN",
    titleAuthCallback: "正在登录 — TWIN",
  },
  privacy: {
    title: "隐私政策（MVP）",
    updated: "最后更新：2026 年 5 月",
    collectTitle: "我们收集的信息",
    collect1: "账户邮箱与密码（哈希存储）",
    collect2: "职业档案：技能、经历、薪资期望、地点",
    collect3: "在 TWIN 中的申请与匹配记录",
    whyTitle: "我们处理数据的原因",
    whyBody:
      "用于将您与 pracuj.pl 与 rocketjobs.pl 的职位匹配并跟踪申请状态。法律依据：注册时您给予的明确同意（GDPR 第 6(1)(a) 条）。",
    rightsTitle: "您的权利",
    rightsBody:
      "您可联系 TWIN 团队请求访问、更正或删除。您可通过删除账户撤回同意（该功能将在后续版本提供）。",
    retentionTitle: "保留期限",
    retentionBody: "在账户存续期间保留数据；应要求删除。",
    thirdTitle: "第三方",
    thirdBody:
      "我们使用 Anthropic Claude 进行职位匹配。职位数据来自上述招聘网站的公开启事。",
  },
  home: {
    tagline: "由 AI 驱动的全球职业发展平台",
    title: "你的 AI 职业分身全天候为你运作市场",
    description:
      "TWIN 是面向各地专业人士的自主职业代理：汇总工作区所启用的招聘网站与地区的职位，对照你的档案打分，并在同一处管理你的求职管道——自动投递与面试排期已在路线图中。",
    getStarted: "免费开始",
    logIn: "登录",
    scrape: "发现",
    scrapeDesc: "你配置的站点与地区——随成长可扩展",
    match: "匹配",
    matchDesc: "按技能、资历与目标评分",
    track: "跟踪",
    trackDesc: "搜索、收藏与申请集中在一处",
    featuresTitle: "从信号到管道",
    featuresSubtitle: "沉稳的工作区，贴合你对市场的思考方式——自动化将逐步到来。",
    footerHint: "注册后请完善档案，以便匹配使用你的技能、职位名称与目标。",
    twinForYourJob: "面向你的职位的 Twin",
    focusTitle: "你希望 TWIN 首先为你优先做什么？",
    focusSubtitle: "选择当下最重要的事项——注册后你将进入控制台，档案、信息流与跟踪已打通。",
    focusPickLabel: "选择起始重点",
    focusChipDiscover: "单一信息流中的最新职位",
    focusChipMatch: "按档案排序的匹配",
    focusChipTrack: "保存并跟踪申请",
    focusChipAuto: "自动投递（路线图中）",
    focusCta: "从这些目标开始",
    focusFootnote:
      "当前 MVP 会汇总职位、在你添加档案后进行评分，并集中申请状态。更重的自动化将分阶段上线——界面依旧简洁，背后更自主。",
    faqEyebrow: "常见问题",
    faqTitle: "问答",
    faqPrivacyLink: "隐私政策",
    faq01Q: "今天的 TWIN 是什么？",
    faq01A:
      "一个求职管道工作区：来自已启用站点的列表、可选的档案评分，以及收藏与申请的单一入口。更深度的自动投递与面试排期在路线图中。",
    faq02Q: "适合谁？",
    faq02A:
      "适合已在多个招聘网站与笔记之间切换、希望减少标签页的人——在一处浏览、比较并推进申请而不丢失上下文。",
    faq03Q: "与只用一个招聘网站有何不同？",
    faq03A:
      "招聘网站仍是职位发布所在；TWIN 是在其上统一发现、匹配信号与跟进的体验层。在需要时，你仍会在雇主的流程中投递。",
    faq04Q: "我的数据怎么办？",
    faq04A:
      "注册时你会明确同意。我们使用档案数据为职位排序并运行产品。关于保留、导出与 GDPR 权利，请阅读下方链接的政策。",
  },
};
