#!/usr/bin/env bash
# Copy Railway Raw Editor block to clipboard (macOS pbcopy). Run from repo root after .env.railway is filled.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.env.railway}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE" >&2
  exit 1
fi
read_var() {
  grep -E "^${1}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true
}
OPS_ADMIN_TOKEN=$(read_var OPS_ADMIN_TOKEN)
BETA_ADMIN_TOKEN=$(read_var BETA_ADMIN_TOKEN)
RECRUITER_INBOX_TOKEN=$(read_var RECRUITER_INBOX_TOKEN)
PARTNER_EXPORT_TOKEN=$(read_var PARTNER_EXPORT_TOKEN)
RESEND_API_KEY=$(read_var RESEND_API_KEY)
MAIL_FROM=$(read_var MAIL_FROM)
GOOGLE_CLIENT_ID=$(read_var GOOGLE_CLIENT_ID)
GOOGLE_CLIENT_SECRET=$(read_var GOOGLE_CLIENT_SECRET)
GOOGLE_CALENDAR_REDIRECT_URI=$(read_var GOOGLE_CALENDAR_REDIRECT_URI)
MICROSOFT_CLIENT_ID=$(read_var MICROSOFT_CLIENT_ID)
MICROSOFT_CLIENT_SECRET=$(read_var MICROSOFT_CLIENT_SECRET)
MICROSOFT_CALENDAR_REDIRECT_URI=$(read_var MICROSOFT_CALENDAR_REDIRECT_URI)
MICROSOFT_TENANT=$(read_var MICROSOFT_TENANT)
FRONTEND_URL=$(read_var FRONTEND_URL)
CORS_ORIGINS=$(read_var CORS_ORIGINS)
RAILWAY_API_URL=$(read_var RAILWAY_API_URL)
MS_REDIRECT="${MICROSOFT_CALENDAR_REDIRECT_URI:-$RAILWAY_API_URL/api/v1/calendar/microsoft/callback}"
GCAL_REDIRECT="${GOOGLE_CALENDAR_REDIRECT_URI:-$RAILWAY_API_URL/api/v1/calendar/google/callback}"
REDIS_REF="${CELERY_BROKER_URL:-\${{Redis.REDIS_URL}}}"
API_URL_VAR=$(read_var API_URL)
SECRET_KEY=$(read_var SECRET_KEY)
block=$(cat <<EOF
API_URL=${API_URL_VAR:-${RAILWAY_API_URL:-https://twin-production-bcd9.up.railway.app}}
ENVIRONMENT=production
SECRET_KEY=${SECRET_KEY:-}
FRONTEND_URL=${FRONTEND_URL:-https://twin-sooty.vercel.app}
CORS_ORIGINS=${CORS_ORIGINS:-https://twin-sooty.vercel.app}
OPS_ADMIN_TOKEN=${OPS_ADMIN_TOKEN:-}
BETA_ADMIN_TOKEN=${BETA_ADMIN_TOKEN:-${OPS_ADMIN_TOKEN:-}}
RECRUITER_INBOX_TOKEN=${RECRUITER_INBOX_TOKEN:-}
PARTNER_EXPORT_TOKEN=${PARTNER_EXPORT_TOKEN:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
MAIL_FROM=${MAIL_FROM:-}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GOOGLE_CALENDAR_REDIRECT_URI=${GCAL_REDIRECT}
MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-}
MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-}
MICROSOFT_CALENDAR_REDIRECT_URI=${MS_REDIRECT}
MICROSOFT_TENANT=${MICROSOFT_TENANT:-common}
CELERY_BROKER_URL=${REDIS_REF}
CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-$REDIS_REF}
CELERY_TASK_ALWAYS_EAGER=false
SCRAPE_WORKER_READY=true
SCRAPE_BEAT_ENABLED=true
AUTO_APPLY_HEADLESS=true
PARTNER_EXPORT_TOKEN=${PARTNER_EXPORT_TOKEN:-}
EOF
)
printf '%s' "$block" | pbcopy
echo "Skopiowano zmienne do schowka (Railway → API service → Variables → Raw Editor → wklej → Deploy)."
open "https://railway.com" 2>/dev/null || true
