"""Autonomous Planner — goal, batch, contract, Product Agent prompt (no founder copy)."""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from app.services.founder_command.constants import (
    AutonomyLevel,
    DEFAULT_BASE_BRANCH,
    DEFAULT_MAX_BATCHES,
    DEFAULT_MAX_RUNTIME_MINUTES,
    DEFAULT_REPO_URL,
    GATE_F_STATUS,
    LAUNCH_STANCE,
)


_DIAGNOSTIC = re.compile(
    r"\b(diagnos\w*|inspect\w*|audit\w*|analy[sz]\w*|read[\s-]?only|bezpieczn\w*|diagnostycz\w*)\b",
    re.I,
)
_DEPLOY = re.compile(r"\b(deploy|railway|vercel|production|produkcj)\b", re.I)
_BUILD = re.compile(r"\b(build|implement|fix|ship|pr\b|commit|napraw|zbuduj)\b", re.I)
_CONTINUOUS = re.compile(r"\b(continu|ciągł|keep (going|shipping)|wystarczy|loop)\b", re.I)


def _infer_mode(command_text: str, autonomy_level: int) -> str:
    # Diagnostic / read-only language always forces analysis, even at L2–L4.
    if _DIAGNOSTIC.search(command_text) or autonomy_level <= AutonomyLevel.ANALYSIS.value:
        return "analysis"
    if autonomy_level >= AutonomyLevel.CONTINUOUS.value and _CONTINUOUS.search(command_text):
        return "continuous"
    if autonomy_level >= AutonomyLevel.DEPLOY.value and _DEPLOY.search(command_text):
        return "deploy"
    if autonomy_level >= AutonomyLevel.BUILD.value and _BUILD.search(command_text):
        return "build"
    if autonomy_level >= AutonomyLevel.DEPLOY.value:
        return "deploy"
    if autonomy_level >= AutonomyLevel.BUILD.value:
        return "build"
    return "analysis"


def _execution_contract_for_mode(mode: str) -> dict[str, Any]:
    """Explicit False preservation for non-required mutation flags."""
    if mode == "analysis":
        return {
            "execution_mode": "read_only",
            "read_only": True,
            "mutation_required": False,
            "commit_required": False,
            "pr_required": False,
            "merge_required": False,
            "deployment_required": False,
            "production_regression_required": False,
            "operator_execution_required": False,
        }
    if mode == "build":
        return {
            "execution_mode": "mutating",
            "read_only": False,
            "mutation_required": True,
            "commit_required": True,
            "pr_required": True,
            "merge_required": False,
            "deployment_required": False,
            "production_regression_required": False,
            "operator_execution_required": True,
        }
    # deploy + continuous: mutating with operator; merge stays manual
    return {
        "execution_mode": "mutating",
        "read_only": False,
        "mutation_required": True,
        "commit_required": True,
        "pr_required": True,
        "merge_required": False,
        "deployment_required": False,
        "production_regression_required": True,
        "operator_execution_required": True,
    }


def _product_agent_prompt(
    *,
    command_text: str,
    goal: str,
    batch_objective: str,
    mode: str,
    contract: dict[str, Any],
    project_state: dict[str, Any],
    acceptance: list[str],
    stop_conditions: list[str],
) -> str:
    prod = project_state.get("production") or {}
    counters = project_state.get("counters") or {}
    if mode == "analysis":
        constraints = [
            "- Inspection-only diagnostic — no git writes and no production changes.",
            "- Use existing Agent Dispatcher / Operator diagnose paths when needed.",
            "- No secrets in reports; no fake PASS; no `|| true`.",
            "- Reply with ONE Polish consolidated report including LINKS.",
        ]
    else:
        constraints = [
            "- Integrate with existing Agent Dispatcher / Operator — do not rebuild them.",
            "- No secrets in reports; no fake PASS; no `|| true`.",
            "- Prefer ONE main PR; manual merge after CI.",
            "- Reply with ONE Polish consolidated report including LINKS.",
        ]
    lines = [
        "# TWIN Product Agent — auto-generated by Founder Command Center",
        "# Founder must NEVER copy this prompt manually.",
        "",
        f"## Goal\n{goal}",
        f"## Batch objective\n{batch_objective}",
        f"## Execution mode\n{mode}",
        "## Execution contract (explicit; preserve False)",
        "```json",
        json.dumps(contract, indent=2, sort_keys=True),
        "```",
        "## Project state (canonical)",
        f"- api_git_commit: {prod.get('api_git_commit')}",
        f"- alignment: {prod.get('alignment_status')}",
        f"- Gate F: {GATE_F_STATUS} (preserve)",
        f"- Launch: {LAUNCH_STANCE} (preserve)",
        f"- counters: {json.dumps(counters, sort_keys=True)}",
        "",
        "## Founder direction",
        command_text.strip(),
        "",
        "## Acceptance",
        *[f"- {a}" for a in acceptance],
        "",
        "## Stop conditions",
        *[f"- {s}" for s in stop_conditions],
        "",
        "## Constraints",
        *constraints,
    ]
    return "\n".join(lines)


def plan_from_command(
    *,
    command_text: str,
    project_state: dict[str, Any],
    autonomy_level: int,
    max_batches: int | None,
    max_runtime_minutes: int | None,
    action: str = "start",
) -> dict[str, Any]:
    mode = _infer_mode(command_text, autonomy_level)
    if action == "analyze":
        mode = "analysis"
        autonomy_level = min(autonomy_level, AutonomyLevel.ANALYSIS.value)

    if autonomy_level >= AutonomyLevel.CONTINUOUS.value:
        if not max_batches or not max_runtime_minutes:
            raise ValueError("level_4_requires_max_batches_and_max_runtime")
    batches = int(max_batches or DEFAULT_MAX_BATCHES)
    runtime = int(max_runtime_minutes or DEFAULT_MAX_RUNTIME_MINUTES)

    contract = _execution_contract_for_mode(mode)
    goal = (
        "Diagnose TWIN production readiness without mutations"
        if mode == "analysis"
        else "Ship the next safe MVP batch toward Founder Command autonomy"
    )
    batch_objective = (
        "Safe diagnostic batch: health, dispatcher, Gate F/Launch, counters → PASS handoff"
        if mode == "analysis"
        else f"Execute one bounded {mode} batch with explicit contract and auto handoff"
    )
    acceptance = [
        "No manual founder copy of prompts/reports/run IDs",
        "Cursor Agent URL present in Founder Command UI when dispatched",
        "Final summary + handoff links recorded",
        "Counters return to zero or documented residual with decision",
        f"Gate F remains {GATE_F_STATUS}; Launch remains {LAUNCH_STANCE}",
    ]
    stop_conditions = [
        f"max_batches={batches}",
        f"max_runtime_minutes={runtime}",
        "max_consecutive_failures reached",
        "pending high-risk decision without approval",
        "Gate F or Launch regression detected",
    ]
    approval_needs = []
    if mode in {"deploy", "continuous"}:
        approval_needs.append("production_deploy")
    if autonomy_level >= AutonomyLevel.CONTINUOUS.value:
        approval_needs.append("continuous_loop")

    repo = (project_state.get("repo") or {}).get("url") or DEFAULT_REPO_URL
    base = (project_state.get("repo") or {}).get("base_branch") or DEFAULT_BASE_BRANCH
    prompt = _product_agent_prompt(
        command_text=command_text,
        goal=goal,
        batch_objective=batch_objective,
        mode=mode,
        contract=contract,
        project_state=project_state,
        acceptance=acceptance,
        stop_conditions=stop_conditions,
    )
    plan = {
        "goal": goal,
        "batch_objective": batch_objective,
        "execution_mode": mode,
        "autonomy_level": autonomy_level,
        "execution_contract": contract,
        "acceptance": acceptance,
        "stop_conditions": stop_conditions,
        "approval_needs": approval_needs,
        "next_batch_proposal": {
            "task_name": f"founder-cmd-{mode}",
            "repository_url": repo,
            "base_branch": base,
            "auto_create_pr": bool(contract.get("pr_required")),
        },
        "limits": {
            "max_batches": batches,
            "max_runtime_minutes": runtime,
        },
        "product_agent_prompt": prompt,
        "product_agent_prompt_hash": hashlib.sha256(prompt.encode()).hexdigest(),
    }
    return plan
