"""Skill synonyms and role signals for flexible matching (PL sales focus)."""

SKILL_SYNONYMS: dict[str, list[str]] = {
    "sales": [
        "sales",
        "sprzedaż",
        "sprzedaz",
        "sprzedaw",
        "handlow",
        "handlowc",
        "pre-sales",
        "presales",
        "account executive",
        "account manager",
        "business development",
        "bd ",
        "new business",
        "revenue",
        "obroty",
        "przychod",
    ],
    "b2b": [
        "b2b",
        "b-to-b",
        "korporacj",
        "enterprise",
        "klient biznesow",
        "firmow",
    ],
    "b2c": ["b2c", "detal", "retail", "konsumenck"],
    "key account": [
        "key account",
        "kam",
        "account manager",
        "opiekun klienta",
        "portfel klient",
        "major account",
    ],
    "negotiation": [
        "negocjac",
        "negotiat",
        "umow",
        "warunk",
        "ofert",
    ],
    "crm": [
        "crm",
        "salesforce",
        "hubspot",
        "pipedrive",
        "zoho",
        "microsoft dynamics",
        "dynamics 365",
    ],
    "management": [
        "management",
        "manager",
        "kierownik",
        "lead",
        "head of",
        "dyrektor",
        "director",
        "owner",
        "product owner",
        "project manager",
        "koordynator",
        "team leader",
        "supervisor",
        "superwizor",
    ],
    "business": [
        "business",
        "biznes",
        "commercial",
        "klien",
        "customer",
        "product",
        "strategi",
        "rozwoj",
        "growth",
    ],
    "communication": [
        "communication",
        "communicaton",
        "komunikacja",
        "marketing",
        "relations",
        "pr ",
        "content",
        "prezentac",
    ],
    "fmcg": ["fmcg", "cg ", "consumer goods", "artykułów spożywczych"],
    "pharma": ["pharma", "farmaceut", "medyczny", "healthcare"],
    "it sales": [
        "it sales",
        "technolog",
        "saas",
        "software",
        "licencj",
        "wdrożen",
    ],
    "python": ["python", "django", "fastapi", "backend", "developer"],
    "react": ["react", "frontend", "typescript", "javascript"],
}

SKILL_ALIASES: dict[str, str] = {
    "communicaton": "communication",
    "managment": "management",
    "bussiness": "business",
    "sale": "sales",
    "sprzedaz": "sales",
    "sprzedaż": "sales",
    "handlowiec": "sales",
    "keyaccount": "key account",
    "kam": "key account",
    "b2b sales": "b2b",
    "account management": "key account",
    "negocjacje": "negotiation",
    "salesforce crm": "crm",
}

# Title keywords that signal a sales role (boost in matcher)
SALES_TITLE_SIGNALS: tuple[str, ...] = (
    "sales",
    "sprzed",
    "handlow",
    "account",
    "business development",
    "kam",
    "key account",
    "commercial",
    "dyrektor sprzedaży",
    "dyrektor sprzedazy",
    "regional manager",
    "area manager",
)
