import { CANDIDATE_CANONICAL_ROUTES } from "@/lib/candidate-canonical-routes";
import {
  CAREER_COMPASS_SHIP_STATUS,
  EVIDENCE_VAULT_SHIP_STATUS,
  INTERVIEW_PREP_SHIP_STATUS,
  REFERRALS_SHIP_STATUS,
  TRUST_CENTER_ROADMAP_STATUS,
  TRUST_CENTER_SHIP_STATUS,
} from "@/lib/seven-day-d2-candidate";
import type { WorkspaceModuleDef } from "@/lib/workspace-module-status";

/** Candidate dashboard module cards — honest readiness, no fake live claims. */
export const CANDIDATE_WORKSPACE_MODULES: readonly WorkspaceModuleDef[] = [
  {
    id: "profile",
    href: CANDIDATE_CANONICAL_ROUTES.profile,
    titleKey: "workspaceModules.candidateProfileTitle",
    valuePropKey: "workspaceModules.candidateProfileValue",
    hintKey: "workspaceModules.candidateProfileHint",
    ctaKey: "workspaceModules.candidateProfileCta",
    status: "live",
  },
  {
    id: "jobs",
    href: CANDIDATE_CANONICAL_ROUTES.jobs,
    titleKey: "workspaceModules.candidateJobsTitle",
    valuePropKey: "workspaceModules.candidateJobsValue",
    hintKey: "workspaceModules.candidateJobsHint",
    ctaKey: "workspaceModules.candidateJobsCta",
    status: "live",
  },
  {
    id: "matches",
    href: CANDIDATE_CANONICAL_ROUTES.matches,
    titleKey: "workspaceModules.candidateMatchesTitle",
    valuePropKey: "workspaceModules.candidateMatchesValue",
    hintKey: "workspaceModules.candidateMatchesHint",
    ctaKey: "workspaceModules.candidateMatchesCta",
    status: "live",
  },
  {
    id: "career_compass",
    href: "/dashboard/career",
    titleKey: "workspaceModules.candidateCareerTitle",
    valuePropKey: "workspaceModules.candidateCareerValue",
    hintKey: "workspaceModules.candidateCareerHint",
    ctaKey: "workspaceModules.candidateCareerCta",
    status: CAREER_COMPASS_SHIP_STATUS,
  },
  {
    id: "plan_payments",
    href: "/dashboard/billing",
    titleKey: "workspaceModules.candidatePlanTitle",
    valuePropKey: "workspaceModules.candidatePlanValue",
    hintKey: "workspaceModules.candidatePlanHint",
    ctaKey: "workspaceModules.candidatePlanCta",
    status: "pilot",
  },
  {
    id: "referrals",
    href: "/dashboard/referrals",
    titleKey: "workspaceModules.candidateReferralsTitle",
    valuePropKey: "workspaceModules.candidateReferralsValue",
    ctaKey: "workspaceModules.candidateReferralsCta",
    status: REFERRALS_SHIP_STATUS,
  },
  {
    id: "identity",
    href: "/dashboard/identity",
    titleKey: "workspaceModules.candidateIdentityTitle",
    valuePropKey: "workspaceModules.candidateIdentityValue",
    hintKey: "workspaceModules.candidateIdentityHint",
    ctaKey: "workspaceModules.candidateIdentityCta",
    status: "live",
  },
  {
    id: "trust_center",
    href: CANDIDATE_CANONICAL_ROUTES.trust,
    titleKey: "workspaceModules.candidateTrustCenterTitle",
    valuePropKey: "workspaceModules.candidateTrustCenterValue",
    hintKey: "workspaceModules.candidateTrustCenterHint",
    ctaKey: "workspaceModules.candidateTrustCenterCta",
    status: TRUST_CENTER_SHIP_STATUS,
  },
  {
    id: "calendar",
    href: "/dashboard/calendar",
    titleKey: "workspaceModules.candidateCalendarTitle",
    valuePropKey: "workspaceModules.candidateCalendarValue",
    hintKey: "workspaceModules.candidateCalendarHint",
    ctaKey: "workspaceModules.candidateCalendarCta",
    status: "live",
  },
  {
    id: "applications",
    href: "/dashboard/applications",
    titleKey: "workspaceModules.candidateApplicationsTitle",
    valuePropKey: "workspaceModules.candidateApplicationsValue",
    ctaKey: "workspaceModules.candidateApplicationsCta",
    status: "live",
  },
  {
    id: "evidence",
    href: "/dashboard/evidence",
    titleKey: "workspaceModules.candidateEvidenceTitle",
    valuePropKey: "workspaceModules.candidateEvidenceValue",
    ctaKey: "workspaceModules.candidateEvidenceCta",
    status: EVIDENCE_VAULT_SHIP_STATUS,
  },
  {
    id: "interview_prep",
    href: "/dashboard/interview-prep",
    titleKey: "workspaceModules.candidateInterviewTitle",
    valuePropKey: "workspaceModules.candidateInterviewValue",
    ctaKey: "workspaceModules.candidateInterviewCta",
    status: INTERVIEW_PREP_SHIP_STATUS,
  },
  {
    id: "auto_apply",
    href: "/dashboard",
    anchor: "#auto-apply-readiness",
    titleKey: "workspaceModules.candidateAutoApplyTitle",
    valuePropKey: "workspaceModules.candidateAutoApplyValue",
    hintKey: "workspaceModules.candidateAutoApplyHint",
    ctaKey: "workspaceModules.candidateAutoApplyCta",
    status: "paused",
  },
];

export const CANDIDATE_MODULE_NAV_COLLAPSED_COUNT = 7;
