/**
 * Canonical candidate workspace routes — single map for tiles, nav, aliases, and QA guards.
 */

export const CANDIDATE_CANONICAL_ROUTES = {
  panel: "/dashboard",
  home: "/dashboard",
  calendar: "/dashboard/calendar",
  jobs: "/dashboard/jobs",
  matches: "/dashboard/matches",
  opportunities: "/dashboard/matches",
  profile: "/profile",
  cv: "/dashboard/cv",
  applications: "/dashboard/applications",
  evidence: "/dashboard/portfolio",
  portfolio: "/dashboard/portfolio",
  interviewPrep: "/dashboard/interview-prep",
  plan: "/dashboard/execution-calendar",
  executionCalendar: "/dashboard/execution-calendar",
  approvals: "/dashboard/approvals",
  decisions: "/dashboard/approvals",
  privacy: "/dashboard/privacy-center",
  settings: "/dashboard/privacy-center",
  identity: "/dashboard/identity",
  trust: "/dashboard/trust",
  trustControls: "/dashboard/trust/controls",
  trustExportPreview: "/dashboard/trust/export-preview",
  trustCorrections: "/dashboard/trust/corrections",
  dataTrust: "/dashboard/data-trust",
  careerPack: "/dashboard/career-pack",
  trustIdentityVerification: "/dashboard/trust/identity-verification",
  trustPortability: "/dashboard/trust/portability",
  trustRevokeDelete: "/dashboard/trust/revoke-delete",
  trustAuditExport: "/dashboard/trust/audit-export",
  trustConsentReceipt: "/dashboard/trust/consent-receipt",
  trustOverview: "/dashboard/trust/overview",
  referrals: "/dashboard/referrals",
  career: "/dashboard/career",
  direction: "/dashboard/career",
  strategy: "/dashboard/strategy",
  billing: "/dashboard/billing",
} as const;
