/**
 * Investor-facing roadmap: live = registry board id exists in TWIN today.
 * One button (“Twin for your job”) runs scrape-all over SCRAPE_ENABLED_BOARD_IDS (or all when unset).
 */
export type InvestorPortal = { name: string; boardId?: string };
export type InvestorCompany = { name: string };

const PORTAL_PAIRS: [string, string | undefined][] = [
  ["Indeed", "indeed"],
  ["LinkedIn", "linkedin"],
  ["Glassdoor", "glassdoor"],
  ["ZipRecruiter", "ziprecruiter"],
  ["Monster", "monster"],
  ["CareerBuilder", "careerbuilder"],
  ["Google for Jobs", undefined],
  ["SimplyHired", "simplyhired"],
  ["Snagajob", undefined],
  ["LinkUp", undefined],
  ["Wellfound (AngelList Talent)", undefined],
  ["Dice", undefined],
  ["We Work Remotely", undefined],
  ["Remote.co", undefined],
  ["FlexJobs", undefined],
  ["Turing", undefined],
  ["Toptal", undefined],
  ["Upwork", undefined],
  ["Fiverr", undefined],
  ["eFinancialCareers", undefined],
  ["BioSpace", undefined],
  ["Rigzone", undefined],
  ["StepStone", "stepstone"],
  ["Totaljobs", undefined],
  ["Reed.co.uk", "reed"],
  ["Welcome to the Jungle", undefined],
  ["Cadremploi", undefined],
  ["InfoJobs", undefined],
  ["Pracuj.pl", "pracuj-sales"],
  ["Jobindex", undefined],
  ["Jobbland", undefined],
  ["HeadHunter (hh.ru)", undefined],
  ["SEEK", "seek"],
  ["Naukri", undefined],
  ["Boss Zhipin", undefined],
  ["Zhaopin", undefined],
  ["58.com", undefined],
  ["Liepin", undefined],
  ["Jobstreet", undefined],
  ["JobsDB", undefined],
  ["Wantedly", undefined],
  ["Daijob", undefined],
  ["Computrabajo", undefined],
  ["OccMundial", undefined],
  ["Catho", undefined],
  ["Bayt", undefined],
  ["GulfTalent", undefined],
  ["Jobberman", undefined],
  ["BrighterMonday", undefined],
  ["Workopolis", undefined],
];

export const INVESTOR_PORTALS: InvestorPortal[] = PORTAL_PAIRS.map(([name, boardId]) => ({
  name,
  boardId,
}));

const COMPANY_NAMES = [
  "Microsoft",
  "Apple",
  "NVIDIA",
  "Alphabet (Google)",
  "Meta Platforms",
  "TSMC",
  "Broadcom",
  "ASML",
  "Oracle",
  "Samsung Electronics",
  "Tencent",
  "Adobe",
  "Salesforce",
  "AMD",
  "Qualcomm",
  "Cisco Systems",
  "SAP",
  "Intel",
  "IBM",
  "Sony",
  "Alibaba Group",
  "Baidu",
  "Xiaomi",
  "Keyence",
  "Infosys",
  "Amazon",
  "Walmart",
  "Costco Wholesale",
  "Home Depot",
  "Meituan",
  "Pinduoduo (PDD Holdings)",
  "JD.com",
  "Target",
  "Lowe's",
  "DHL Group",
  "FedEx",
  "UPS",
  "Inditex (Zara)",
  "MercadoLibre",
  "Fast Retailing (Uniqlo)",
  "Tesla",
  "Toyota Motor",
  "BYD",
  "Porsche",
  "Mercedes-Benz Group",
  "Volkswagen Group",
  "BMW Group",
  "Ferrari",
  "Stellantis",
  "Honda Motor",
  "Berkshire Hathaway",
  "JPMorgan Chase & Co.",
  "Visa",
  "Mastercard",
  "Bank of America",
  "ICBC",
  "China Construction Bank",
  "Agricultural Bank of China",
  "Wells Fargo",
  "HSBC Holdings",
  "Goldman Sachs",
  "Morgan Stanley",
  "Royal Bank of Canada",
  "HDFC Bank",
  "BlackRock",
  "UBS Group",
  "Allianz",
  "Ping An Insurance",
  "Eli Lilly & Co.",
  "Novo Nordisk",
  "UnitedHealth Group",
  "Johnson & Johnson",
  "Merck & Co.",
  "AbbVie",
  "Roche Holding",
  "Novartis",
  "AstraZeneca",
  "Pfizer",
  "Sanofi",
  "Thermo Fisher Scientific",
  "Bristol Myers Squibb",
  "Saudi Aramco",
  "ExxonMobil",
  "Chevron",
  "Shell",
  "TotalEnergies",
  "PetroChina",
  "BHP Group",
  "Rio Tinto",
  "Linde",
  "Caterpillar",
  "General Electric (GE Aerospace)",
  "Siemens",
  "Schneider Electric",
  "Honeywell",
  "LVMH",
  "Procter & Gamble",
  "L'Oréal",
  "Nestlé",
  "Netflix",
];

export const INVESTOR_COMPANIES: InvestorCompany[] = COMPANY_NAMES.map((name) => ({ name }));

export function isLivePortal(boardId: string | undefined): boolean {
  return typeof boardId === "string" && boardId.length > 0;
}
